import json,sys
from pathlib import Path
p=Path('/Users/serinya/Documents/WNC Rental Automation/docs/staging/uat/autonomous_remediation');root=p.parents[3];slug=sys.argv[1]
load=lambda name:json.loads((p/name).read_text())
result=load(f'{slug}_results.json');assessment=load(f'{slug}_assessment.json');status=load('program_status.json')
lines=['# Autonomous Remediation Summary','','This report records the bounded autonomous remediation program on synthetic staging cases. The scenario inputs and original evidence were frozen before changes. Quality scores are direct assistant assessments of the exact outputs, not an independent human evaluation or an added LLM-judge service.','',f"Completed cycles: {status['completed_cycles']}. Final run: {slug}.",'','Historical user-provided baseline: 13 scenarios, 21 turns, 19 drafts, A/B/C/D 6/10/3/0; A+B 84.2%; factual grounding 4.95, tone 3.79, naturalness 4.26, confidence 4.05; work reduction 84.2%; turn coverage 90.5%; continuity 6/7. Those historical assessments are preserved without alteration.','','The fresh baseline and each remediation run below use the current requested rubric. They are scored independently by content hash. Coverage counts accepted persisted drafts; rejected candidates do not enter the accepted-draft grade or safety denominator. Any available rejected candidate text is shown separately with its rejection status.','','## Metrics by run','']
lines+=['| Measure | Historical baseline | Final | Target |','|---|---:|---:|---:|','| Accepted drafts / attempted turns | 19/21 | 19/21 | ≥95% |','| A / B / C / D | 6 / 10 / 3 / 0 | 10 / 9 / 0 / 0 | D=0 |','| A+B, accepted outputs | 84.2% | 100% | ≥90% |','| WNC tone | 3.79 | 4.53 | ≥4.3 |','| Naturalness | 4.26 | 4.53 | ≥4.4 |','| Operator confidence | 4.05 | 4.53 | ≥4.3 |','| Complete multi-turn continuity | 6/7 | 6/7 | 7/7 |','','Three cycles improved the accepted drafts, but the program remains INCOMPLETE. The final run lost one draft to an availability-validator false positive and one turn to a reconciliation response parsing failure before generation. Conservative contextual-guidance delivery also falls below target because these two cases lack accepted outputs for all relevant turns. No fourth cycle was performed.','','The baseline and final scores use the same named dimensions but were assessed at different times; the fresh baseline below supplies a same-program comparison. Work reduction means an A/B draft under the requested editing rubric, not measured operator minutes.','']
for name in ['baseline','cycle1','cycle2','cycle3']:
 f=p/f'{name}_assessment.json'
 if f.exists():lines+=[f'### {name}','','```json',json.dumps(load(f.name)['metrics'],indent=2),'```','']
lines+=['## Targets and final decision','','```json',json.dumps(status.get('final_targets',{'status':'pending final assessment'}),indent=2),'```','']
changes={1:('Internal uncertainty, omitted known answers, unfiltered model input and currency-format false positives.','Explicit ClientGenerationPayload; client-safe Phase 5 kitchen/supplier projection; Phase 4 capacity/technical guidance; blocking idempotent availability tasks; recovered facilitator ownership; no signature; narrow currency and negation normalization.'),2:('Conditional equipment details were lost; follow-ups lost earlier client topics; boilerplate disclaimers persisted; supplier logistics lacked specific internal tasks; rejected text could not be inspected.','Current client-only thread context bound into the contract hash; observed request topics retained for retrieval without promoting them to authority; conditional Phase 4 projector guidance; idempotent loading/handover/arrival tasks; factual guidance separated from send constraints; unrelated class-cancellation terms removed from facilitator retrieval; synthetic staging rejection audit stores exact candidate text.'),3:tuple(status.get('cycle3_description', ['See committed change and final defect analysis.','See committed change and final defect analysis.']))}
for n in range(1,status['completed_cycles']+1):
 why,what=changes[n];lines += [f'# Cycle {n}','','Defect clusters: '+why,'','Changes: '+what,'',f"Commit: `{status.get(f'cycle{n}_commit')}`. Deployment: `{status.get(f'cycle{n}_deploy_id')}`.",'','Tests:','','```json',json.dumps(status.get(f'cycle{n}_tests',status.get('tests',{})),indent=2),'```','','UAT metrics are listed above; complete structured evidence is in the corresponding results, assessment and database-audit files.','']
lines+=['# Final Scenario Outputs','','All accepted subjects and bodies are reproduced verbatim. An accepted draft still requires its normal operator and approval workflow; none was approved or executed during this program.']
events=next(x['evidence'] for x in load(f'{slug}_database_audit.json') if x['kind']=='generation_events') or []
for s in result['results']:
 rej=[e for e in events if e['rental_case_id']==s['rental_case_id'] and e['event_type_code'].endswith('_rejected')];ri=0
 for t in s['turns']:
  lines+=['',f"## {s['scenario_id']} / Turn {t['turn_number']}: {s['title']}"]
  r=t.get('draft',{}).get('draft_revision')
  if r:
   c=r['context_payload'];intent=t['draft']['response_intent'];subject=r['subject'];body=r['body_text'];a=next(x for x in assessment['assessments'] if x['scenario_id']==s['scenario_id'] and x['turn']==t['turn_number']);state='Accepted, persisted; not approved or sent.'
  else:
   is_rejection='CLIENT_RESPONSE_DRAFT_INVALID' in t.get('failure','');e=rej[ri]['structured_payload'] if is_rejection and ri<len(rej) else {};ri+=int(is_rejection);c=e.get('rejected_context',{});intent=e.get('response_intent','Generation failed');subject=e.get('rejected_subject','Unavailable: service did not persist rejected text.');body=e.get('rejected_body','Unavailable: service did not persist rejected text.');a={'grade':'Not included in accepted-draft grades','reason':'Candidate rejected by deterministic validation.','validation_codes':e.get('validation_codes',[]),'request_failure':t.get('failure')};a.update(load(f'{slug}_rejected_assessment.json').get(f"{s['scenario_id']}/{t['turn_number']}",{}) if (p/f'{slug}_rejected_assessment.json').exists() else {});state='Rejected; no DraftRevision or approval created for this candidate.'
   if not is_rejection:
    state='Generation not reached: reconciliation response could not be parsed; no candidate, DraftRevision or approval was created for this turn.'
    intent='Unavailable: generation not reached.';subject='Not generated.';body='Not generated.'
    a={'grade':'N/A: no generated output','scores':{k:'N/A' for k in assessment['assessments'][0]['scores']},'checks':{},'safety_quality_checks':{k:'N/A: no generated output' for k in assessment['assessments'][0]['checks']},'request_failure':t.get('failure')}
    c={k:'No generated contract for this turn; post-failure case state is retained in cycle3_results.json.' for k in ('resolution_items','contextual_guidance','operator_annotations')}
  lines+=['','Status: '+state,'','### Intent','',str(intent),'','### Resolution ownership/items','','```json',json.dumps(c.get('resolution_items',[]),indent=2,ensure_ascii=False),'```','','### Retrieved contextual guidance','','```json',json.dumps(c.get('contextual_guidance',[]),indent=2,ensure_ascii=False),'```','','### Internal operator actions/annotations','','```json',json.dumps(c.get('operator_annotations',[]),indent=2,ensure_ascii=False),'```','','### Subject','','```text',subject,'```','','### Body','','```text',body,'```','','### Grade, scores and safety/quality checks','','```json',json.dumps({**a, 'checks': {k:('Yes' if v else 'No') for k,v in a.get('checks',{}).items()}},indent=2,ensure_ascii=False),'```']
lines+=['','# Before → After Examples','','Every originally B/C-graded turn appears below, preserving the historical and final text exactly. A missing final accepted draft is identified explicitly; no improvement is claimed for a rejected result.']
old=json.loads((root/'docs/staging/uat/real_model_governed_drafting_uat_results.json').read_text())
comparison_notes={'UAT-003':'Known whole-venue capacity is separated from availability. The candidate improves wording but still fails validation, so accepted coverage did not improve.', 'UAT-004':'Conditional Phase 4 projector guidance now includes compatibility/adapters/screenless constraints, while thread context preserves optional hologram status.', 'UAT-005':'Current kitchen and supplier guidance is retrieved alongside separate availability and facilitator tasks; client context retains buffet and requested setup without granting access.', 'UAT-007':'Full timing components explicitly include year; relevant current kitchen guidance accompanies the client-owned catering questions.', 'UAT-008':'Current commercial truth stays distinct from the pending exception, with natural prospective check language.', 'UAT-009':'Current fee authority remains separate from historical waiver precedent; the follow-up uses current client context.', 'UAT-010':'Known capacity and governed access restrictions are answered separately from internal custom technical feasibility.', 'UAT-011':'Current access, supplier, kitchen and conditional AV guidance is retained. Unresolved route/timing checks become internal tasks, and concrete clock-time access assumptions are blocked.', 'UAT-012':'Client-only thread context preserves compound topics; contextual retrieval and full timing questions improve accepted turns. The missing second turn still breaks complete continuity.'}
for s in old['results']:
 for t in s['turns']:
  if t.get('quality_assessment',{}).get('grade') not in {'B','C'}:continue
  r=t['draft']['draft_revision'];fs=next(v for v in result['results'] if v['scenario_id']==s['scenario_id']);ft=next(v for v in fs['turns'] if v['turn_number']==t['turn_number']);fr=ft.get('draft',{}).get('draft_revision');fa=next((v for v in assessment['assessments'] if v['scenario_id']==s['scenario_id'] and v['turn']==t['turn_number']),None)
  lines+=['',f"## {s['scenario_id']} / Turn {t['turn_number']}",'','OLD:','','Subject:','','```text',r['subject'],'```','','Body:','','```text',r['body_text'],'```','','FINAL:']
  if fr:lines+=['','Subject:','','```text',fr['subject'],'```','','Body:','','```text',fr['body_text'],'```','','Assessment: '+fa['reason']]
  else:
   rejection_number=sum('CLIENT_RESPONSE_DRAFT_INVALID' in v.get('failure','') for v in fs['turns'] if v['turn_number']<=ft['turn_number'])-1
   rejections=[e['structured_payload'] for e in events if e['rental_case_id']==fs['rental_case_id'] and e['event_type_code'].endswith('_rejected')]
   candidate=rejections[rejection_number] if 'CLIENT_RESPONSE_DRAFT_INVALID' in ft.get('failure','') and 0<=rejection_number<len(rejections) else {}
   lines+=['','No accepted final draft.']
   if 'rejected_body' in candidate:
    lines+=['','Final rejected candidate (never approved or sent):','','Subject:','','```text',candidate['rejected_subject'],'```','','Body:','','```text',candidate['rejected_body'],'```']
   else:lines+=['','No generated subject/body was retained for this failed turn.']
  lines+=['',f"Systemic change: {comparison_notes.get(s['scenario_id'], 'Client-only payload, specific prospective checks and current governed facts replace generic uncertainty.')}"]
lines+=['','# Earlier Run Outputs (verbatim)','','Full per-turn scores, contexts, actions and request logs are retained in the matching assessment and results JSON files. These earlier runs are preserved for comparison and are not the final deployment result.']
for earlier in ('baseline','cycle1','cycle2'):
 if earlier==slug:continue
 f=p/f'{earlier}_results.json'
 if not f.exists():continue
 earlier_data=load(f.name)
 for case in earlier_data['results']:
  for turn in case['turns']:
   revision=turn.get('draft',{}).get('draft_revision')
   lines+=['',f"## {earlier}: {case['scenario_id']} / Turn {turn['turn_number']}"]
   if revision:lines+=['','Subject:','','```text',revision['subject'],'```','','Body:','','```text',revision['body_text'],'```']
   else:lines+=['','No persisted draft. '+turn.get('failure','Failure details are in structured evidence.')]
lines+=['','# Provider-Free Final Verification','','```json',json.dumps(status['final_verification'],indent=2),'```','','## Reconciliation diagnostics','','```json',json.dumps(load('cycle3_reconciliation_diagnostic.json'),indent=2),'```']
lines+=['','# Final Defect Clusters Remaining','',*status.get('remaining_defects',['Final assessment pending.']),'','# Tests','','Full test totals and deployment commits are recorded per cycle above. JUnit artifacts are saved alongside this report. Frozen scenario and original evidence checksums remain in `frozen_manifest.json`.','# Deployment','',json.dumps({k:v for k,v in status.items() if 'commit' in k or 'deploy' in k},indent=2),'','# Safety','','Graph mutations = 0; Outlook sends = 0; real Asana executions = 0; production activity = 0. No approval or execution routes were called. Staging Outlook remains configured_draft_only and Asana configured_but_disabled. The OpenAI provider and gpt-5.6-sol model were unchanged. Synthetic @example.test cases only.','','Historical recovery actions and approvals were not targeted. All actions created in the UAT are internal workflow records or open approval-bound draft actions; task creation was not treated as external contact.','','## Evidence limits','','Rejected candidate text before Cycle 2 was not retained by the pre-existing service. This gap cannot be reconstructed and is disclosed rather than paraphrased. Freshness checks use captured revision/case bindings; the final database audit verifies current revisions and duplicate action keys. Quality scoring is subjective. A/B work-reduction is a rubric proxy, not a measured operator time study. The failing reconciliation raw response was not captured, so no precise transport cause is claimed. Historical records were not targeted; this program did not capture before/after hashes of every historical record.','',status.get('final_marker','Program still running.')]
(p/'AUTONOMOUS_REMEDIATION_REPORT.md').write_text('\n'.join(lines)+'\n')
print(p/'AUTONOMOUS_REMEDIATION_REPORT.md')
