create table if not exists private.historical_case_embedding_models (
  id bigint generated by default as identity primary key,
  provider_code text not null,
  model_code text not null,
  model_version text,
  embedding_dimensions integer not null,
  config_fingerprint text not null,
  configuration_json jsonb not null default '{}'::jsonb,
  is_retrieval_approved boolean not null default false,
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint historical_case_embedding_models_provider_code_nonempty
    check (btrim(provider_code) <> ''),
  constraint historical_case_embedding_models_model_code_nonempty
    check (btrim(model_code) <> ''),
  constraint historical_case_embedding_models_model_version_nonempty
    check (model_version is null or btrim(model_version) <> ''),
  constraint historical_case_embedding_models_embedding_dimensions_positive
    check (embedding_dimensions > 0),
  constraint historical_case_embedding_models_config_fingerprint_nonempty
    check (btrim(config_fingerprint) <> ''),
  constraint historical_case_embedding_models_configuration_json_object
    check (jsonb_typeof(configuration_json) = 'object')
);

create unique index if not exists historical_case_embedding_models_registry_identity_idx
  on private.historical_case_embedding_models (
    provider_code,
    model_code,
    coalesce(model_version, ''),
    config_fingerprint
  );

create unique index if not exists historical_case_embedding_models_one_active_retrieval_model_idx
  on private.historical_case_embedding_models ((1))
  where is_retrieval_approved
    and is_active;

create table if not exists private.historical_case_embeddings (
  id bigint generated by default as identity primary key,
  historical_case_search_unit_id bigint not null references private.historical_case_search_units(id) on delete cascade,
  embedding_model_id bigint not null references private.historical_case_embedding_models(id) on delete restrict,
  input_content_hash text not null,
  generated_at timestamptz not null,
  embedding extensions.vector not null,
  created_at timestamptz not null default timezone('utc', now()),
  constraint historical_case_embeddings_input_content_hash_nonempty
    check (btrim(input_content_hash) <> ''),
  constraint historical_case_embeddings_unique_unit_model_input
    unique (historical_case_search_unit_id, embedding_model_id, input_content_hash)
);

create index if not exists historical_case_embeddings_model_unit_lookup_idx
  on private.historical_case_embeddings (
    embedding_model_id,
    historical_case_search_unit_id,
    input_content_hash
  );

create or replace function private.build_historical_case_search_unit_embedding_input(
  p_case_title text,
  p_case_code text,
  p_unit_type text,
  p_actor_type text,
  p_lesson_kind text,
  p_search_text text
)
returns text
language sql
immutable
as $$
select concat_ws(
  E'\n\n',
  concat('Case: ', coalesce(p_case_title, '')),
  case
    when nullif(btrim(p_case_code), '') is not null then
      concat('Case code: ', nullif(btrim(p_case_code), ''))
    else null
  end,
  case
    when nullif(btrim(p_unit_type), '') is not null then
      concat('Unit type: ', nullif(btrim(p_unit_type), ''))
    else null
  end,
  case
    when nullif(btrim(p_actor_type), '') is not null then
      concat('Actor type: ', nullif(btrim(p_actor_type), ''))
    else null
  end,
  case
    when nullif(btrim(p_lesson_kind), '') is not null then
      concat('Lesson kind: ', nullif(btrim(p_lesson_kind), ''))
    else null
  end,
  coalesce(p_search_text, '')
);
$$;

create or replace function private.build_historical_case_search_unit_embedding_input_hash(
  p_case_title text,
  p_case_code text,
  p_unit_type text,
  p_actor_type text,
  p_lesson_kind text,
  p_search_text text
)
returns text
language sql
immutable
as $$
select md5(
  private.build_historical_case_search_unit_embedding_input(
    p_case_title,
    p_case_code,
    p_unit_type,
    p_actor_type,
    p_lesson_kind,
    p_search_text
  )
);
$$;

create or replace view private.current_historical_case_embedding_inputs as
select
  chcsu.search_unit_id,
  chcsu.source_key,
  chcsu.source_layer_role,
  chcsu.historical_case_id,
  chcsu.historical_case_version_id,
  chcsu.case_code,
  chcsu.case_title,
  chcsu.unit_type,
  chcsu.precedent_type,
  chcsu.precedent_availability,
  chcsu.case_evidence_strength,
  chcsu.unit_evidence_strength,
  chcsu.search_text,
  chcsu.actor_type,
  chcsu.lesson_kind,
  chcsu.historical_value_only,
  chcsu.contamination_risk_level,
  chcsu.current_authority_disposition,
  chcsu.case_contains_historical_value_only_content,
  chcsu.case_personal_information_status,
  chcsu.source_object_personal_information_status,
  chcsu.effective_confidentiality_level_id,
  chcsu.effective_confidentiality_level_code,
  chcsu.primary_historical_case_version_source_object_id,
  chcsu.primary_source_object_id,
  chcsu.primary_source_locator,
  chcsu.source_link_count,
  chcsu.responsibility_id,
  chcsu.decision_id,
  chcsu.lesson_id,
  private.build_historical_case_search_unit_embedding_input(
    chcsu.case_title,
    chcsu.case_code,
    chcsu.unit_type,
    chcsu.actor_type,
    chcsu.lesson_kind,
    chcsu.search_text
  ) as embedding_input_text,
  private.build_historical_case_search_unit_embedding_input_hash(
    chcsu.case_title,
    chcsu.case_code,
    chcsu.unit_type,
    chcsu.actor_type,
    chcsu.lesson_kind,
    chcsu.search_text
  ) as embedding_input_hash
from private.current_historical_case_search_units chcsu;

create or replace view private.current_historical_case_embedding_coverage as
with approved_models as (
  select
    hcem.id as embedding_model_id,
    hcem.provider_code,
    hcem.model_code,
    hcem.model_version,
    hcem.embedding_dimensions,
    hcem.config_fingerprint
  from private.historical_case_embedding_models hcem
  where hcem.is_retrieval_approved
    and hcem.is_active
),
eligible_inputs as (
  select *
  from private.current_historical_case_embedding_inputs
),
current_matches as (
  select
    am.embedding_model_id,
    ei.search_unit_id
  from approved_models am
  join eligible_inputs ei
    on true
  join private.historical_case_embeddings hce
    on hce.historical_case_search_unit_id = ei.search_unit_id
   and hce.embedding_model_id = am.embedding_model_id
   and hce.input_content_hash = ei.embedding_input_hash
  group by am.embedding_model_id, ei.search_unit_id
),
stale_units as (
  select
    am.embedding_model_id,
    ei.search_unit_id
  from approved_models am
  join eligible_inputs ei
    on true
  where not exists (
    select 1
    from private.historical_case_embeddings hce_current
    where hce_current.historical_case_search_unit_id = ei.search_unit_id
      and hce_current.embedding_model_id = am.embedding_model_id
      and hce_current.input_content_hash = ei.embedding_input_hash
  )
    and exists (
      select 1
      from private.historical_case_embeddings hce_stale
      where hce_stale.historical_case_search_unit_id = ei.search_unit_id
        and hce_stale.embedding_model_id = am.embedding_model_id
    )
),
all_model_rows as (
  select
    am.embedding_model_id,
    am.provider_code,
    am.model_code,
    am.model_version,
    am.embedding_dimensions,
    am.config_fingerprint,
    (select count(*)::bigint from eligible_inputs) as eligible_unit_count,
    (select count(*)::bigint from current_matches cm where cm.embedding_model_id = am.embedding_model_id) as current_embedding_count,
    (select count(*)::bigint from stale_units su where su.embedding_model_id = am.embedding_model_id) as stale_unit_count
  from approved_models am
)
select
  amr.embedding_model_id,
  amr.provider_code,
  amr.model_code,
  amr.model_version,
  amr.embedding_dimensions,
  amr.config_fingerprint,
  amr.eligible_unit_count,
  amr.current_embedding_count,
  amr.eligible_unit_count - amr.current_embedding_count as missing_unit_count,
  amr.stale_unit_count
from all_model_rows amr;

create or replace function private.validate_historical_case_embedding()
returns trigger
language plpgsql
as $$
declare
  expected_dimensions integer;
  actual_dimensions integer;
begin
  select hcem.embedding_dimensions
  into expected_dimensions
  from private.historical_case_embedding_models hcem
  where hcem.id = new.embedding_model_id;

  if expected_dimensions is null then
    return new;
  end if;

  actual_dimensions := extensions.vector_dims(new.embedding);

  if actual_dimensions <> expected_dimensions then
    raise exception 'embedding dimensions % do not match historical embedding model % dimensions %',
      actual_dimensions,
      new.embedding_model_id,
      expected_dimensions
      using errcode = '23514';
  end if;

  return new;
end;
$$;

create or replace function private.search_historical_case_units_semantic(
  p_query_embedding extensions.vector,
  p_result_limit integer default 10,
  p_embedding_model_id bigint default null,
  p_case_code text default null,
  p_unit_type text default null,
  p_precedent_availability text default null,
  p_precedent_type text default null,
  p_lesson_kind text default null,
  p_historical_value_only boolean default null,
  p_contamination_risk_level text default null
)
returns table (
  search_unit_id bigint,
  source_layer_role text,
  source_key text,
  unit_type text,
  search_text text,
  similarity_score double precision,
  cosine_distance double precision,
  input_content_hash text,
  historical_case_id bigint,
  historical_case_version_id bigint,
  case_code text,
  case_title text,
  precedent_type text,
  precedent_availability text,
  case_evidence_strength text,
  unit_evidence_strength text,
  actor_type text,
  lesson_kind text,
  historical_value_only boolean,
  contamination_risk_level text,
  current_authority_disposition text,
  case_contains_historical_value_only_content boolean,
  effective_confidentiality_level_id bigint,
  effective_confidentiality_level_code text,
  case_personal_information_status text,
  source_object_personal_information_status text,
  primary_historical_case_version_source_object_id bigint,
  primary_source_object_id bigint,
  primary_source_locator text,
  source_link_count bigint,
  responsibility_id bigint,
  decision_id bigint,
  lesson_id bigint,
  embedding_model_id bigint,
  provider_code text,
  model_code text,
  model_version text
)
language plpgsql
stable
security invoker
set search_path = pg_catalog, private, public, extensions
as $$
declare
  resolved_embedding_model_id bigint;
  resolved_embedding_dimensions integer;
  approved_model_count integer;
  actual_query_dimensions integer;
  bounded_limit integer;
  normalized_case_code text;
  normalized_unit_type text;
  normalized_precedent_availability text;
  normalized_precedent_type text;
  normalized_lesson_kind text;
  normalized_contamination_risk_level text;
begin
  if p_query_embedding is null then
    raise exception 'query embedding is required'
      using errcode = '22004';
  end if;

  bounded_limit := least(greatest(coalesce(p_result_limit, 10), 1), 50);
  normalized_case_code := nullif(upper(btrim(coalesce(p_case_code, ''))), '');
  normalized_unit_type := nullif(lower(btrim(coalesce(p_unit_type, ''))), '');
  normalized_precedent_availability := nullif(lower(btrim(coalesce(p_precedent_availability, ''))), '');
  normalized_precedent_type := nullif(lower(btrim(coalesce(p_precedent_type, ''))), '');
  normalized_lesson_kind := nullif(lower(btrim(coalesce(p_lesson_kind, ''))), '');
  normalized_contamination_risk_level := nullif(lower(btrim(coalesce(p_contamination_risk_level, ''))), '');

  if normalized_unit_type is not null
     and normalized_unit_type not in ('case_narrative', 'responsibility', 'decision', 'lesson') then
    raise exception 'unsupported historical unit_type filter: %', normalized_unit_type
      using errcode = '22023';
  end if;

  if normalized_precedent_availability is not null
     and normalized_precedent_availability not in ('active', 'limited') then
    raise exception 'unsupported historical precedent_availability filter: %', normalized_precedent_availability
      using errcode = '22023';
  end if;

  if normalized_precedent_type is not null
     and normalized_precedent_type not in ('full_case', 'limited_precedent', 'cautionary_precedent') then
    raise exception 'unsupported historical precedent_type filter: %', normalized_precedent_type
      using errcode = '22023';
  end if;

  if normalized_lesson_kind is not null
     and normalized_lesson_kind not in ('source_explicit', 'curated_lesson', 'analyst_inference', 'caution_warning') then
    raise exception 'unsupported historical lesson_kind filter: %', normalized_lesson_kind
      using errcode = '22023';
  end if;

  if normalized_contamination_risk_level is not null
     and normalized_contamination_risk_level not in ('low', 'medium', 'high') then
    raise exception 'unsupported historical contamination_risk_level filter: %', normalized_contamination_risk_level
      using errcode = '22023';
  end if;

  if p_embedding_model_id is null then
    select count(*)
    into approved_model_count
    from private.historical_case_embedding_models hcem
    where hcem.is_retrieval_approved
      and hcem.is_active;

    if approved_model_count = 0 then
      raise exception 'no active retrieval-approved historical embedding model is registered'
        using errcode = 'P0001';
    end if;

    if approved_model_count > 1 then
      raise exception 'multiple active retrieval-approved historical embedding models are registered'
        using errcode = 'P0001';
    end if;

    select
      hcem.id,
      hcem.embedding_dimensions
    into resolved_embedding_model_id, resolved_embedding_dimensions
    from private.historical_case_embedding_models hcem
    where hcem.is_retrieval_approved
      and hcem.is_active;
  else
    select
      hcem.id,
      hcem.embedding_dimensions
    into resolved_embedding_model_id, resolved_embedding_dimensions
    from private.historical_case_embedding_models hcem
    where hcem.id = p_embedding_model_id
      and hcem.is_active;

    if resolved_embedding_model_id is null then
      raise exception 'historical embedding model % is not an active registered model',
        p_embedding_model_id
        using errcode = '23503';
    end if;
  end if;

  actual_query_dimensions := vector_dims(p_query_embedding);

  if actual_query_dimensions <> resolved_embedding_dimensions then
    raise exception 'query embedding dimensions % do not match historical embedding model % dimensions %',
      actual_query_dimensions,
      resolved_embedding_model_id,
      resolved_embedding_dimensions
      using errcode = '23514';
  end if;

  return query
  with scored as (
    select
      chcei.search_unit_id,
      chcei.source_layer_role,
      chcei.source_key,
      chcei.unit_type,
      chcei.search_text,
      1 - (hce.embedding <=> p_query_embedding) as similarity_score,
      hce.embedding <=> p_query_embedding as cosine_distance,
      hce.input_content_hash,
      chcei.historical_case_id,
      chcei.historical_case_version_id,
      chcei.case_code,
      chcei.case_title,
      chcei.precedent_type,
      chcei.precedent_availability,
      chcei.case_evidence_strength,
      chcei.unit_evidence_strength,
      chcei.actor_type,
      chcei.lesson_kind,
      chcei.historical_value_only,
      chcei.contamination_risk_level,
      chcei.current_authority_disposition,
      chcei.case_contains_historical_value_only_content,
      chcei.effective_confidentiality_level_id,
      chcei.effective_confidentiality_level_code,
      chcei.case_personal_information_status,
      chcei.source_object_personal_information_status,
      chcei.primary_historical_case_version_source_object_id,
      chcei.primary_source_object_id,
      chcei.primary_source_locator,
      chcei.source_link_count,
      chcei.responsibility_id,
      chcei.decision_id,
      chcei.lesson_id,
      hcem.id as embedding_model_id,
      hcem.provider_code,
      hcem.model_code,
      hcem.model_version
    from private.current_historical_case_embedding_inputs chcei
    join private.historical_case_embeddings hce
      on hce.historical_case_search_unit_id = chcei.search_unit_id
     and hce.embedding_model_id = resolved_embedding_model_id
     and hce.input_content_hash = chcei.embedding_input_hash
    join private.historical_case_embedding_models hcem
      on hcem.id = hce.embedding_model_id
    where (normalized_case_code is null or chcei.case_code = normalized_case_code)
      and (normalized_unit_type is null or chcei.unit_type = normalized_unit_type)
      and (
        normalized_precedent_availability is null
        or chcei.precedent_availability = normalized_precedent_availability
      )
      and (
        normalized_precedent_type is null
        or chcei.precedent_type = normalized_precedent_type
      )
      and (
        normalized_lesson_kind is null
        or chcei.lesson_kind = normalized_lesson_kind
      )
      and (
        p_historical_value_only is null
        or chcei.historical_value_only = p_historical_value_only
      )
      and (
        normalized_contamination_risk_level is null
        or chcei.contamination_risk_level = normalized_contamination_risk_level
      )
  )
  select
    scored.search_unit_id,
    scored.source_layer_role,
    scored.source_key,
    scored.unit_type,
    scored.search_text,
    scored.similarity_score,
    scored.cosine_distance,
    scored.input_content_hash,
    scored.historical_case_id,
    scored.historical_case_version_id,
    scored.case_code,
    scored.case_title,
    scored.precedent_type,
    scored.precedent_availability,
    scored.case_evidence_strength,
    scored.unit_evidence_strength,
    scored.actor_type,
    scored.lesson_kind,
    scored.historical_value_only,
    scored.contamination_risk_level,
    scored.current_authority_disposition,
    scored.case_contains_historical_value_only_content,
    scored.effective_confidentiality_level_id,
    scored.effective_confidentiality_level_code,
    scored.case_personal_information_status,
    scored.source_object_personal_information_status,
    scored.primary_historical_case_version_source_object_id,
    scored.primary_source_object_id,
    scored.primary_source_locator,
    scored.source_link_count,
    scored.responsibility_id,
    scored.decision_id,
    scored.lesson_id,
    scored.embedding_model_id,
    scored.provider_code,
    scored.model_code,
    scored.model_version
  from scored
  order by scored.cosine_distance asc, scored.case_code, scored.unit_type, scored.search_unit_id
  limit bounded_limit;
end;
$$;

drop trigger if exists trg_historical_case_embedding_models_touch_updated_at on private.historical_case_embedding_models;
create trigger trg_historical_case_embedding_models_touch_updated_at
before update on private.historical_case_embedding_models
for each row
execute function private.touch_updated_at();

drop trigger if exists trg_historical_case_embeddings_validate_embedding on private.historical_case_embeddings;
create trigger trg_historical_case_embeddings_validate_embedding
before insert or update of embedding_model_id, embedding on private.historical_case_embeddings
for each row
execute function private.validate_historical_case_embedding();

alter table private.historical_case_embedding_models enable row level security;
alter table private.historical_case_embeddings enable row level security;

revoke all on table private.historical_case_embedding_models from public, anon, authenticated, service_role;
revoke all on table private.historical_case_embeddings from public, anon, authenticated, service_role;
revoke all on table private.current_historical_case_embedding_inputs from public, anon, authenticated, service_role;
revoke all on table private.current_historical_case_embedding_coverage from public, anon, authenticated, service_role;
revoke execute on function private.build_historical_case_search_unit_embedding_input(text, text, text, text, text, text)
  from public, anon, authenticated, service_role;
revoke execute on function private.build_historical_case_search_unit_embedding_input_hash(text, text, text, text, text, text)
  from public, anon, authenticated, service_role;
revoke execute on function private.search_historical_case_units_semantic(
  extensions.vector,
  integer,
  bigint,
  text,
  text,
  text,
  text,
  text,
  boolean,
  text
)
  from public, anon, authenticated, service_role;
