create table if not exists public.knowledge_source_object_roles (
  id bigint generated by default as identity primary key,
  role_code text not null unique,
  display_name text not null,
  description text not null,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint knowledge_source_object_roles_code_nonempty check (btrim(role_code) <> ''),
  constraint knowledge_source_object_roles_display_name_nonempty check (btrim(display_name) <> ''),
  constraint knowledge_source_object_roles_description_nonempty check (btrim(description) <> ''),
  constraint knowledge_source_object_roles_sort_order_nonnegative check (sort_order >= 0)
);

create table if not exists public.knowledge_rule_relationship_types (
  id bigint generated by default as identity primary key,
  relationship_type_code text not null unique,
  target_kind text not null,
  display_name text not null,
  description text not null,
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint knowledge_rule_relationship_types_code_nonempty check (btrim(relationship_type_code) <> ''),
  constraint knowledge_rule_relationship_types_target_kind_check
    check (target_kind in ('logical_rule', 'rule_version')),
  constraint knowledge_rule_relationship_types_display_name_nonempty check (btrim(display_name) <> ''),
  constraint knowledge_rule_relationship_types_description_nonempty check (btrim(description) <> '')
);

create table if not exists public.knowledge_source_objects (
  id bigint generated by default as identity primary key,
  source_registry_id bigint references public.source_registry(id) on delete restrict,
  origin_type text not null,
  external_uri text,
  repository_relative_path text,
  storage_bucket text,
  storage_object_key text,
  manual_reference_key text,
  original_filename text,
  mime_type text,
  file_size_bytes bigint,
  checksum_sha256 text,
  personal_information_status text not null default 'unknown',
  personal_information_notes text,
  imported_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint knowledge_source_objects_origin_type_check
    check (origin_type in ('repository_file', 'supabase_storage', 'external_uri', 'manual_reference')),
  constraint knowledge_source_objects_personal_information_status_check
    check (personal_information_status in ('yes', 'no', 'unknown')),
  constraint knowledge_source_objects_file_size_nonnegative
    check (file_size_bytes is null or file_size_bytes >= 0),
  constraint knowledge_source_objects_external_uri_nonempty
    check (external_uri is null or btrim(external_uri) <> ''),
  constraint knowledge_source_objects_repository_relative_path_nonempty
    check (repository_relative_path is null or btrim(repository_relative_path) <> ''),
  constraint knowledge_source_objects_storage_bucket_nonempty
    check (storage_bucket is null or btrim(storage_bucket) <> ''),
  constraint knowledge_source_objects_storage_object_key_nonempty
    check (storage_object_key is null or btrim(storage_object_key) <> ''),
  constraint knowledge_source_objects_manual_reference_key_nonempty
    check (manual_reference_key is null or btrim(manual_reference_key) <> ''),
  constraint knowledge_source_objects_original_filename_nonempty
    check (original_filename is null or btrim(original_filename) <> ''),
  constraint knowledge_source_objects_mime_type_nonempty
    check (mime_type is null or btrim(mime_type) <> ''),
  constraint knowledge_source_objects_checksum_sha256_nonempty
    check (checksum_sha256 is null or btrim(checksum_sha256) <> ''),
  constraint knowledge_source_objects_personal_information_notes_nonempty
    check (personal_information_notes is null or btrim(personal_information_notes) <> ''),
  constraint knowledge_source_objects_origin_locator_check
    check (
      (
        origin_type = 'repository_file'
        and repository_relative_path is not null
        and storage_bucket is null
        and storage_object_key is null
        and external_uri is null
        and manual_reference_key is null
      )
      or (
        origin_type = 'supabase_storage'
        and storage_bucket is not null
        and storage_object_key is not null
        and repository_relative_path is null
        and external_uri is null
        and manual_reference_key is null
      )
      or (
        origin_type = 'external_uri'
        and external_uri is not null
        and repository_relative_path is null
        and storage_bucket is null
        and storage_object_key is null
        and manual_reference_key is null
      )
      or (
        origin_type = 'manual_reference'
        and manual_reference_key is not null
        and repository_relative_path is null
        and storage_bucket is null
        and storage_object_key is null
        and external_uri is null
      )
    )
);

create unique index if not exists knowledge_source_objects_repository_file_unique_idx
  on public.knowledge_source_objects (repository_relative_path)
  where origin_type = 'repository_file';

create unique index if not exists knowledge_source_objects_supabase_storage_unique_idx
  on public.knowledge_source_objects (storage_bucket, storage_object_key)
  where origin_type = 'supabase_storage';

create unique index if not exists knowledge_source_objects_external_uri_unique_idx
  on public.knowledge_source_objects (external_uri)
  where origin_type = 'external_uri';

create unique index if not exists knowledge_source_objects_manual_reference_unique_idx
  on public.knowledge_source_objects (manual_reference_key)
  where origin_type = 'manual_reference';

create index if not exists knowledge_source_objects_checksum_sha256_idx
  on public.knowledge_source_objects (checksum_sha256)
  where checksum_sha256 is not null;

create table if not exists public.knowledge_document_version_source_objects (
  id bigint generated by default as identity primary key,
  document_version_id bigint not null references public.knowledge_document_versions(id) on delete cascade,
  source_object_id bigint not null references public.knowledge_source_objects(id) on delete restrict,
  source_object_role_id bigint not null references public.knowledge_source_object_roles(id) on delete restrict,
  source_usage_disposition text not null,
  is_preferred_extraction_source boolean not null default false,
  is_primary_representation boolean not null default false,
  representation_notes text,
  created_at timestamptz not null default timezone('utc', now()),
  constraint knowledge_document_version_source_objects_disposition_check
    check (source_usage_disposition in ('eligible_for_extraction', 'supporting_only', 'excluded_from_extraction')),
  constraint knowledge_document_version_source_objects_notes_nonempty
    check (representation_notes is null or btrim(representation_notes) <> ''),
  constraint knowledge_document_version_source_objects_unique
    unique (document_version_id, source_object_id, source_object_role_id),
  constraint kdv_source_objects_preferred_requires_eligible
    check (
      not is_preferred_extraction_source
      or source_usage_disposition = 'eligible_for_extraction'
    )
);

create unique index if not exists knowledge_document_version_source_objects_one_preferred_idx
  on public.knowledge_document_version_source_objects (document_version_id)
  where is_preferred_extraction_source;

create unique index if not exists knowledge_document_version_source_objects_one_primary_idx
  on public.knowledge_document_version_source_objects (document_version_id)
  where is_primary_representation;

create table if not exists public.knowledge_document_version_logical_rules (
  id bigint generated by default as identity primary key,
  document_version_id bigint not null references public.knowledge_document_versions(id) on delete cascade,
  rule_code text not null references public.logical_rules(rule_code) on delete restrict,
  relationship_type_id bigint not null references public.knowledge_rule_relationship_types(id) on delete restrict,
  notes text,
  created_at timestamptz not null default timezone('utc', now()),
  constraint knowledge_document_version_logical_rules_notes_nonempty
    check (notes is null or btrim(notes) <> ''),
  constraint knowledge_document_version_logical_rules_unique
    unique (document_version_id, rule_code, relationship_type_id)
);

create table if not exists public.knowledge_document_version_rule_versions (
  id bigint generated by default as identity primary key,
  document_version_id bigint not null references public.knowledge_document_versions(id) on delete cascade,
  rule_version_id bigint not null references public.rule_catalogue(id) on delete restrict,
  relationship_type_id bigint not null references public.knowledge_rule_relationship_types(id) on delete restrict,
  notes text,
  created_at timestamptz not null default timezone('utc', now()),
  constraint knowledge_document_version_rule_versions_notes_nonempty
    check (notes is null or btrim(notes) <> ''),
  constraint knowledge_document_version_rule_versions_unique
    unique (document_version_id, rule_version_id, relationship_type_id)
);

create or replace function private.validate_knowledge_rule_relationship_target_kind()
returns trigger
language plpgsql
as $$
declare
  actual_target_kind text;
  relationship_code text;
  expected_target_kind text := tg_argv[0];
begin
  select krt.target_kind, krt.relationship_type_code
  into actual_target_kind, relationship_code
  from public.knowledge_rule_relationship_types krt
  where krt.id = new.relationship_type_id;

  if actual_target_kind is not null and actual_target_kind <> expected_target_kind then
    raise exception 'relationship type % must target %, not %',
      relationship_code,
      expected_target_kind,
      actual_target_kind
      using errcode = '23514';
  end if;

  return new;
end;
$$;

drop trigger if exists trg_knowledge_source_object_roles_touch_updated_at on public.knowledge_source_object_roles;
create trigger trg_knowledge_source_object_roles_touch_updated_at
before update on public.knowledge_source_object_roles
for each row
execute function private.touch_updated_at();

drop trigger if exists trg_knowledge_rule_relationship_types_touch_updated_at on public.knowledge_rule_relationship_types;
create trigger trg_knowledge_rule_relationship_types_touch_updated_at
before update on public.knowledge_rule_relationship_types
for each row
execute function private.touch_updated_at();

drop trigger if exists trg_knowledge_source_objects_touch_updated_at on public.knowledge_source_objects;
create trigger trg_knowledge_source_objects_touch_updated_at
before update on public.knowledge_source_objects
for each row
execute function private.touch_updated_at();

drop trigger if exists trg_kdv_logical_rules_validate_target_kind on public.knowledge_document_version_logical_rules;
create trigger trg_kdv_logical_rules_validate_target_kind
before insert or update of relationship_type_id on public.knowledge_document_version_logical_rules
for each row
execute function private.validate_knowledge_rule_relationship_target_kind('logical_rule');

drop trigger if exists trg_kdv_rule_versions_validate_target_kind on public.knowledge_document_version_rule_versions;
create trigger trg_kdv_rule_versions_validate_target_kind
before insert or update of relationship_type_id on public.knowledge_document_version_rule_versions
for each row
execute function private.validate_knowledge_rule_relationship_target_kind('rule_version');

insert into public.knowledge_source_object_roles (
  role_code,
  display_name,
  description,
  sort_order
)
values
  (
    'authoritative_editable_source',
    'Authoritative Editable Source',
    'Primary editable representation treated as the authoritative governed source for the document version.',
    10
  ),
  (
    'export',
    'Export',
    'Derived export representation of the governed document version, such as a generated PDF.',
    20
  ),
  (
    'attachment',
    'Attachment',
    'Associated attachment that belongs to the governed document version without being the main document body.',
    30
  ),
  (
    'supporting_source',
    'Supporting Source',
    'Supporting representation or reference retained for provenance without being the authoritative editable source.',
    40
  )
on conflict (role_code) do update
set display_name = excluded.display_name,
    description = excluded.description,
    sort_order = excluded.sort_order,
    is_active = true;

insert into public.knowledge_rule_relationship_types (
  relationship_type_code,
  target_kind,
  display_name,
  description
)
values
  (
    'governed_by',
    'logical_rule',
    'Governed By',
    'The knowledge content concerns an operational concept whose deterministic truth is governed by the referenced logical rule.'
  ),
  (
    'explains',
    'logical_rule',
    'Explains',
    'The knowledge content explains the concept represented by the logical rule without itself owning deterministic truth.'
  ),
  (
    'operational_context_for',
    'logical_rule',
    'Operational Context For',
    'The knowledge content provides operating procedure or context surrounding the logical rule without becoming the rule itself.'
  ),
  (
    'specifically_reflects',
    'rule_version',
    'Specifically Reflects',
    'The knowledge content specifically reflects the exact referenced rule version.'
  ),
  (
    'historically_explains',
    'rule_version',
    'Historically Explains',
    'The knowledge content historically explains the exact referenced rule version.'
  ),
  (
    'superseded_because_rule_changed',
    'rule_version',
    'Superseded Because Rule Changed',
    'The knowledge content was superseded because the exact referenced rule version changed.'
  )
on conflict (relationship_type_code) do update
set target_kind = excluded.target_kind,
    display_name = excluded.display_name,
    description = excluded.description,
    is_active = true;

alter table public.knowledge_source_object_roles enable row level security;
alter table public.knowledge_rule_relationship_types enable row level security;
alter table public.knowledge_source_objects enable row level security;
alter table public.knowledge_document_version_source_objects enable row level security;
alter table public.knowledge_document_version_logical_rules enable row level security;
alter table public.knowledge_document_version_rule_versions enable row level security;

revoke all on table public.knowledge_source_object_roles from public, anon, authenticated, service_role;
revoke all on table public.knowledge_rule_relationship_types from public, anon, authenticated, service_role;
revoke all on table public.knowledge_source_objects from public, anon, authenticated, service_role;
revoke all on table public.knowledge_document_version_source_objects from public, anon, authenticated, service_role;
revoke all on table public.knowledge_document_version_logical_rules from public, anon, authenticated, service_role;
revoke all on table public.knowledge_document_version_rule_versions from public, anon, authenticated, service_role;
