create or replace function private.historical_case_statement_contamination_metadata_valid(
  p_historical_value_only boolean,
  p_contamination_risk_level text,
  p_current_authority_disposition text
)
returns boolean
language sql
immutable
as $$
  select
    p_historical_value_only is not null
    and p_contamination_risk_level in ('low', 'medium', 'high')
    and p_current_authority_disposition in (
      'no_current_rule_implication',
      'check_phase_4',
      'check_phase_5',
      'check_phase_4_and_5',
      'potential_conflict_with_current_knowledge',
      'current_status_unknown'
    )
    and not (
      p_contamination_risk_level = 'high'
      and p_current_authority_disposition = 'no_current_rule_implication'
    );
$$;

create table if not exists public.historical_case_version_responsibilities (
  id bigint generated by default as identity primary key,
  historical_case_version_id bigint not null references public.historical_case_versions(id) on delete cascade,
  actor_type text not null,
  responsibility_statement text not null,
  evidence_strength text not null,
  historical_value_only boolean not null default false,
  contamination_risk_level text not null,
  current_authority_disposition text not null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint historical_case_version_responsibilities_actor_type_check
    check (actor_type in ('wnc', 'client', 'external_supplier')),
  constraint historical_case_version_responsibilities_statement_nonempty
    check (btrim(responsibility_statement) <> ''),
  constraint historical_case_version_responsibilities_evidence_strength_check
    check (evidence_strength in ('strong', 'moderate', 'limited')),
  constraint historical_case_version_responsibilities_contamination_metadata_check
    check (
      private.historical_case_statement_contamination_metadata_valid(
        historical_value_only,
        contamination_risk_level,
        current_authority_disposition
      )
    )
);

create unique index if not exists historical_case_version_responsibilities_id_version_unique_idx
  on public.historical_case_version_responsibilities (id, historical_case_version_id);

create index if not exists historical_case_version_responsibilities_version_idx
  on public.historical_case_version_responsibilities (historical_case_version_id);

create table if not exists public.historical_case_version_decisions (
  id bigint generated by default as identity primary key,
  historical_case_version_id bigint not null references public.historical_case_versions(id) on delete cascade,
  decision_statement text not null,
  historical_context text,
  evidence_strength text not null,
  historical_value_only boolean not null default false,
  contamination_risk_level text not null,
  current_authority_disposition text not null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint historical_case_version_decisions_statement_nonempty
    check (btrim(decision_statement) <> ''),
  constraint historical_case_version_decisions_context_nonempty
    check (historical_context is null or btrim(historical_context) <> ''),
  constraint historical_case_version_decisions_evidence_strength_check
    check (evidence_strength in ('strong', 'moderate', 'limited')),
  constraint historical_case_version_decisions_contamination_metadata_check
    check (
      private.historical_case_statement_contamination_metadata_valid(
        historical_value_only,
        contamination_risk_level,
        current_authority_disposition
      )
    )
);

create unique index if not exists historical_case_version_decisions_id_version_unique_idx
  on public.historical_case_version_decisions (id, historical_case_version_id);

create index if not exists historical_case_version_decisions_version_idx
  on public.historical_case_version_decisions (historical_case_version_id);

create table if not exists public.historical_case_version_lessons (
  id bigint generated by default as identity primary key,
  historical_case_version_id bigint not null references public.historical_case_versions(id) on delete cascade,
  lesson_kind text not null,
  lesson_statement text not null,
  evidence_strength text not null,
  historical_value_only boolean not null default false,
  contamination_risk_level text not null,
  current_authority_disposition text not null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint historical_case_version_lessons_kind_check
    check (lesson_kind in ('source_explicit', 'curated_lesson', 'analyst_inference', 'caution_warning')),
  constraint historical_case_version_lessons_statement_nonempty
    check (btrim(lesson_statement) <> ''),
  constraint historical_case_version_lessons_evidence_strength_check
    check (evidence_strength in ('strong', 'moderate', 'limited')),
  constraint historical_case_version_lessons_contamination_metadata_check
    check (
      private.historical_case_statement_contamination_metadata_valid(
        historical_value_only,
        contamination_risk_level,
        current_authority_disposition
      )
    )
);

create unique index if not exists historical_case_version_lessons_id_version_unique_idx
  on public.historical_case_version_lessons (id, historical_case_version_id);

create index if not exists historical_case_version_lessons_version_idx
  on public.historical_case_version_lessons (historical_case_version_id);

create unique index if not exists historical_case_version_source_objects_id_version_unique_idx
  on public.historical_case_version_source_objects (id, historical_case_version_id);

create table if not exists public.historical_case_version_responsibility_sources (
  id bigint generated by default as identity primary key,
  historical_case_version_id bigint not null references public.historical_case_versions(id) on delete cascade,
  responsibility_id bigint not null,
  historical_case_version_source_object_id bigint not null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint historical_case_version_responsibility_sources_unique
    unique (responsibility_id, historical_case_version_source_object_id),
  constraint historical_case_version_responsibility_sources_statement_fk
    foreign key (responsibility_id, historical_case_version_id)
    references public.historical_case_version_responsibilities(id, historical_case_version_id)
    on delete cascade,
  constraint historical_case_version_responsibility_sources_source_fk
    foreign key (historical_case_version_source_object_id, historical_case_version_id)
    references public.historical_case_version_source_objects(id, historical_case_version_id)
    on delete cascade
);

create index if not exists historical_case_version_responsibility_sources_version_idx
  on public.historical_case_version_responsibility_sources (historical_case_version_id);

create table if not exists public.historical_case_version_decision_sources (
  id bigint generated by default as identity primary key,
  historical_case_version_id bigint not null references public.historical_case_versions(id) on delete cascade,
  decision_id bigint not null,
  historical_case_version_source_object_id bigint not null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint historical_case_version_decision_sources_unique
    unique (decision_id, historical_case_version_source_object_id),
  constraint historical_case_version_decision_sources_statement_fk
    foreign key (decision_id, historical_case_version_id)
    references public.historical_case_version_decisions(id, historical_case_version_id)
    on delete cascade,
  constraint historical_case_version_decision_sources_source_fk
    foreign key (historical_case_version_source_object_id, historical_case_version_id)
    references public.historical_case_version_source_objects(id, historical_case_version_id)
    on delete cascade
);

create index if not exists historical_case_version_decision_sources_version_idx
  on public.historical_case_version_decision_sources (historical_case_version_id);

create table if not exists public.historical_case_version_lesson_sources (
  id bigint generated by default as identity primary key,
  historical_case_version_id bigint not null references public.historical_case_versions(id) on delete cascade,
  lesson_id bigint not null,
  historical_case_version_source_object_id bigint not null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint historical_case_version_lesson_sources_unique
    unique (lesson_id, historical_case_version_source_object_id),
  constraint historical_case_version_lesson_sources_statement_fk
    foreign key (lesson_id, historical_case_version_id)
    references public.historical_case_version_lessons(id, historical_case_version_id)
    on delete cascade,
  constraint historical_case_version_lesson_sources_source_fk
    foreign key (historical_case_version_source_object_id, historical_case_version_id)
    references public.historical_case_version_source_objects(id, historical_case_version_id)
    on delete cascade
);

create index if not exists historical_case_version_lesson_sources_version_idx
  on public.historical_case_version_lesson_sources (historical_case_version_id);

create or replace function private.historical_case_version_contains_historical_value_only_content(
  p_historical_case_version_id bigint
)
returns boolean
language sql
stable
as $$
  select exists (
    select 1
    from public.historical_case_version_responsibilities hcvr
    where hcvr.historical_case_version_id = p_historical_case_version_id
      and hcvr.historical_value_only
    union all
    select 1
    from public.historical_case_version_decisions hcvd
    where hcvd.historical_case_version_id = p_historical_case_version_id
      and hcvd.historical_value_only
    union all
    select 1
    from public.historical_case_version_lessons hcvl
    where hcvl.historical_case_version_id = p_historical_case_version_id
      and hcvl.historical_value_only
  );
$$;

create or replace function private.enforce_historical_case_version_statement_editability()
returns trigger
language plpgsql
as $$
declare
  target_historical_case_version_id bigint := coalesce(new.historical_case_version_id, old.historical_case_version_id);
  target_governance_status text;
begin
  select hcv.governance_status
  into target_governance_status
  from public.historical_case_versions hcv
  where hcv.id = target_historical_case_version_id;

  if target_governance_status is not null and target_governance_status <> 'draft' then
    raise exception 'historical case governed statements and provenance links are immutable once the parent case version is no longer draft'
      using errcode = '23514';
  end if;

  return coalesce(new, old);
end;
$$;

create or replace function private.sync_historical_case_version_historical_value_summary()
returns trigger
language plpgsql
as $$
declare
  target_historical_case_version_id bigint := coalesce(new.historical_case_version_id, old.historical_case_version_id);
  computed_contains_historical_value_only_content boolean;
begin
  computed_contains_historical_value_only_content :=
    private.historical_case_version_contains_historical_value_only_content(target_historical_case_version_id);

  update public.historical_case_versions hcv
  set contains_historical_value_only_content = computed_contains_historical_value_only_content
  where hcv.id = target_historical_case_version_id
    and hcv.contains_historical_value_only_content is distinct from computed_contains_historical_value_only_content;

  return coalesce(new, old);
end;
$$;

create or replace function private.validate_historical_case_statement_source_link_dimension()
returns trigger
language plpgsql
as $$
declare
  required_dimension text := tg_argv[0];
  supported_claim_dimensions text[];
begin
  select hcvso.supported_claim_dimensions
  into supported_claim_dimensions
  from public.historical_case_version_source_objects hcvso
  where hcvso.id = new.historical_case_version_source_object_id;

  if supported_claim_dimensions is null or not (required_dimension = any(supported_claim_dimensions)) then
    raise exception 'historical case statement evidence links require a source association that supports the % claim dimension', required_dimension
      using errcode = '23514';
  end if;

  return new;
end;
$$;

create or replace function private.assert_historical_case_version_statement_provenance_complete(
  p_historical_case_version_id bigint
)
returns void
language plpgsql
as $$
begin
  if p_historical_case_version_id is null then
    return;
  end if;

  if exists (
    select 1
    from public.historical_case_version_responsibilities hcvr
    where hcvr.historical_case_version_id = p_historical_case_version_id
      and not exists (
        select 1
        from public.historical_case_version_responsibility_sources hcvrs
        where hcvrs.responsibility_id = hcvr.id
      )
  ) then
    raise exception 'historical case version cannot become active while responsibility statements lack supporting evidence associations'
      using errcode = '23514';
  end if;

  if exists (
    select 1
    from public.historical_case_version_decisions hcvd
    where hcvd.historical_case_version_id = p_historical_case_version_id
      and not exists (
        select 1
        from public.historical_case_version_decision_sources hcvds
        where hcvds.decision_id = hcvd.id
      )
  ) then
    raise exception 'historical case version cannot become active while decision statements lack supporting evidence associations'
      using errcode = '23514';
  end if;

  if exists (
    select 1
    from public.historical_case_version_lessons hcvl
    where hcvl.historical_case_version_id = p_historical_case_version_id
      and not exists (
        select 1
        from public.historical_case_version_lesson_sources hcvls
        where hcvls.lesson_id = hcvl.id
      )
  ) then
    raise exception 'historical case version cannot become active while lesson statements lack supporting evidence associations'
      using errcode = '23514';
  end if;
end;
$$;

create or replace function private.enforce_historical_case_version_lifecycle()
returns trigger
language plpgsql
as $$
begin
  if tg_op = 'UPDATE' and new.id is not null then
    new.contains_historical_value_only_content :=
      private.historical_case_version_contains_historical_value_only_content(new.id);
  end if;

  if tg_op = 'UPDATE' then
    if old.governance_status = 'draft' and new.governance_status not in ('draft', 'active', 'retired') then
      raise exception 'draft historical case versions can only remain draft, become active, or be retired'
        using errcode = '23514';
    end if;

    if old.governance_status = 'active' and new.governance_status not in ('active', 'superseded', 'retired') then
      raise exception 'active historical case versions can only remain active, become superseded, or be retired'
        using errcode = '23514';
    end if;

    if old.governance_status = 'superseded' and new.governance_status not in ('superseded', 'retired') then
      raise exception 'superseded historical case versions cannot become draft or active again'
        using errcode = '23514';
    end if;

    if old.governance_status = 'retired' and new.governance_status <> 'retired' then
      raise exception 'retired historical case versions are immutable lifecycle endpoints'
        using errcode = '23514';
    end if;

    if old.governance_status <> 'draft' and (
      old.historical_case_id is distinct from new.historical_case_id
      or old.version_number is distinct from new.version_number
      or old.precedent_availability is distinct from new.precedent_availability
      or old.precedent_type is distinct from new.precedent_type
      or old.evidence_strength is distinct from new.evidence_strength
      or old.historical_event_status is distinct from new.historical_event_status
      or old.temporal_precision is distinct from new.temporal_precision
      or old.event_date_start is distinct from new.event_date_start
      or old.event_date_end is distinct from new.event_date_end
      or old.temporal_note is distinct from new.temporal_note
      or old.curated_narrative is distinct from new.curated_narrative
      or old.confidentiality_level_id is distinct from new.confidentiality_level_id
      or old.personal_information_status is distinct from new.personal_information_status
      or old.personal_information_notes is distinct from new.personal_information_notes
      or old.contains_historical_value_only_content is distinct from new.contains_historical_value_only_content
      or old.supersedes_version_id is distinct from new.supersedes_version_id
    ) then
      raise exception 'non-draft historical case versions cannot be materially rewritten; create a superseding version instead'
        using errcode = '23514';
    end if;
  end if;

  if new.governance_status = 'draft' and new.activated_at is not null then
    raise exception 'draft historical case versions cannot record activated_at'
      using errcode = '23514';
  end if;

  if new.governance_status = 'active' and new.activated_at is null then
    new.activated_at := timezone('utc', now());
  end if;

  if new.governance_status = 'active' then
    perform private.assert_historical_case_version_statement_provenance_complete(new.id);
  end if;

  if new.governance_status = 'superseded' and new.activated_at is null then
    raise exception 'superseded historical case versions must retain an activated_at timestamp'
      using errcode = '23514';
  end if;

  return new;
end;
$$;

drop trigger if exists trg_historical_case_version_responsibilities_touch_updated_at on public.historical_case_version_responsibilities;
create trigger trg_historical_case_version_responsibilities_touch_updated_at
before update on public.historical_case_version_responsibilities
for each row
execute function private.touch_updated_at();

drop trigger if exists trg_historical_case_version_decisions_touch_updated_at on public.historical_case_version_decisions;
create trigger trg_historical_case_version_decisions_touch_updated_at
before update on public.historical_case_version_decisions
for each row
execute function private.touch_updated_at();

drop trigger if exists trg_historical_case_version_lessons_touch_updated_at on public.historical_case_version_lessons;
create trigger trg_historical_case_version_lessons_touch_updated_at
before update on public.historical_case_version_lessons
for each row
execute function private.touch_updated_at();

drop trigger if exists trg_hcv_responsibility_sources_touch_updated_at on public.historical_case_version_responsibility_sources;
create trigger trg_hcv_responsibility_sources_touch_updated_at
before update on public.historical_case_version_responsibility_sources
for each row
execute function private.touch_updated_at();

drop trigger if exists trg_historical_case_version_decision_sources_touch_updated_at on public.historical_case_version_decision_sources;
create trigger trg_historical_case_version_decision_sources_touch_updated_at
before update on public.historical_case_version_decision_sources
for each row
execute function private.touch_updated_at();

drop trigger if exists trg_historical_case_version_lesson_sources_touch_updated_at on public.historical_case_version_lesson_sources;
create trigger trg_historical_case_version_lesson_sources_touch_updated_at
before update on public.historical_case_version_lesson_sources
for each row
execute function private.touch_updated_at();

drop trigger if exists trg_enforce_historical_case_version_responsibility_editability on public.historical_case_version_responsibilities;
create trigger trg_enforce_historical_case_version_responsibility_editability
before insert or update or delete on public.historical_case_version_responsibilities
for each row
execute function private.enforce_historical_case_version_statement_editability();

drop trigger if exists trg_enforce_historical_case_version_decision_editability on public.historical_case_version_decisions;
create trigger trg_enforce_historical_case_version_decision_editability
before insert or update or delete on public.historical_case_version_decisions
for each row
execute function private.enforce_historical_case_version_statement_editability();

drop trigger if exists trg_enforce_historical_case_version_lesson_editability on public.historical_case_version_lessons;
create trigger trg_enforce_historical_case_version_lesson_editability
before insert or update or delete on public.historical_case_version_lessons
for each row
execute function private.enforce_historical_case_version_statement_editability();

drop trigger if exists trg_hcv_responsibility_source_editability on public.historical_case_version_responsibility_sources;
create trigger trg_hcv_responsibility_source_editability
before insert or update or delete on public.historical_case_version_responsibility_sources
for each row
execute function private.enforce_historical_case_version_statement_editability();

drop trigger if exists trg_enforce_historical_case_version_decision_source_editability on public.historical_case_version_decision_sources;
create trigger trg_enforce_historical_case_version_decision_source_editability
before insert or update or delete on public.historical_case_version_decision_sources
for each row
execute function private.enforce_historical_case_version_statement_editability();

drop trigger if exists trg_enforce_historical_case_version_lesson_source_editability on public.historical_case_version_lesson_sources;
create trigger trg_enforce_historical_case_version_lesson_source_editability
before insert or update or delete on public.historical_case_version_lesson_sources
for each row
execute function private.enforce_historical_case_version_statement_editability();

drop trigger if exists trg_sync_historical_case_version_summary_from_responsibilities on public.historical_case_version_responsibilities;
create trigger trg_sync_historical_case_version_summary_from_responsibilities
after insert or update or delete on public.historical_case_version_responsibilities
for each row
execute function private.sync_historical_case_version_historical_value_summary();

drop trigger if exists trg_sync_historical_case_version_summary_from_decisions on public.historical_case_version_decisions;
create trigger trg_sync_historical_case_version_summary_from_decisions
after insert or update or delete on public.historical_case_version_decisions
for each row
execute function private.sync_historical_case_version_historical_value_summary();

drop trigger if exists trg_sync_historical_case_version_summary_from_lessons on public.historical_case_version_lessons;
create trigger trg_sync_historical_case_version_summary_from_lessons
after insert or update or delete on public.historical_case_version_lessons
for each row
execute function private.sync_historical_case_version_historical_value_summary();

drop trigger if exists trg_hcv_responsibility_source_dimension on public.historical_case_version_responsibility_sources;
create trigger trg_hcv_responsibility_source_dimension
before insert or update on public.historical_case_version_responsibility_sources
for each row
execute function private.validate_historical_case_statement_source_link_dimension('responsibility');

drop trigger if exists trg_validate_historical_case_version_decision_source_dimension on public.historical_case_version_decision_sources;
create trigger trg_validate_historical_case_version_decision_source_dimension
before insert or update on public.historical_case_version_decision_sources
for each row
execute function private.validate_historical_case_statement_source_link_dimension('decision');

drop trigger if exists trg_validate_historical_case_version_lesson_source_dimension on public.historical_case_version_lesson_sources;
create trigger trg_validate_historical_case_version_lesson_source_dimension
before insert or update on public.historical_case_version_lesson_sources
for each row
execute function private.validate_historical_case_statement_source_link_dimension('lesson');

alter table public.historical_case_version_responsibilities enable row level security;
alter table public.historical_case_version_decisions enable row level security;
alter table public.historical_case_version_lessons enable row level security;
alter table public.historical_case_version_responsibility_sources enable row level security;
alter table public.historical_case_version_decision_sources enable row level security;
alter table public.historical_case_version_lesson_sources enable row level security;

revoke all on table public.historical_case_version_responsibilities from public, anon, authenticated, service_role;
revoke all on table public.historical_case_version_decisions from public, anon, authenticated, service_role;
revoke all on table public.historical_case_version_lessons from public, anon, authenticated, service_role;
revoke all on table public.historical_case_version_responsibility_sources from public, anon, authenticated, service_role;
revoke all on table public.historical_case_version_decision_sources from public, anon, authenticated, service_role;
revoke all on table public.historical_case_version_lesson_sources from public, anon, authenticated, service_role;
