create table if not exists public.historical_precedent_topics (
  id bigint generated by default as identity primary key,
  topic_code text not null unique,
  display_name text not null,
  description text not null,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint historical_precedent_topics_code_nonempty
    check (btrim(topic_code) <> ''),
  constraint historical_precedent_topics_display_name_nonempty
    check (btrim(display_name) <> ''),
  constraint historical_precedent_topics_description_nonempty
    check (btrim(description) <> ''),
  constraint historical_precedent_topics_sort_order_nonnegative
    check (sort_order >= 0)
);

create table if not exists public.historical_case_version_topics (
  id bigint generated by default as identity primary key,
  historical_case_version_id bigint not null references public.historical_case_versions(id) on delete cascade,
  topic_id bigint not null references public.historical_precedent_topics(id) on delete restrict,
  topic_relevance text not null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint historical_case_version_topics_relevance_check
    check (topic_relevance in ('primary', 'secondary')),
  constraint historical_case_version_topics_unique
    unique (historical_case_version_id, topic_id)
);

create table if not exists public.historical_case_version_rental_types (
  id bigint generated by default as identity primary key,
  historical_case_version_id bigint not null references public.historical_case_versions(id) on delete cascade,
  rental_type_id bigint not null references public.rental_types(id) on delete restrict,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint historical_case_version_rental_types_unique
    unique (historical_case_version_id, rental_type_id)
);

create table if not exists public.historical_case_version_spaces (
  id bigint generated by default as identity primary key,
  historical_case_version_id bigint not null references public.historical_case_versions(id) on delete cascade,
  venue_space_id bigint not null references public.venue_spaces(id) on delete restrict,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint historical_case_version_spaces_unique
    unique (historical_case_version_id, venue_space_id)
);

create or replace function private.enforce_historical_case_version_classification_editability()
returns trigger
language plpgsql
as $$
declare
  target_historical_case_version_id bigint := coalesce(new.historical_case_version_id, old.historical_case_version_id);
  target_governance_status text;
begin
  select hcv.governance_status
  into target_governance_status
  from public.historical_case_versions hcv
  where hcv.id = target_historical_case_version_id;

  if target_governance_status is not null and target_governance_status <> 'draft' then
    raise exception 'historical case classification associations are immutable once the parent case version is no longer draft'
      using errcode = '23514';
  end if;

  return coalesce(new, old);
end;
$$;

drop trigger if exists trg_historical_precedent_topics_touch_updated_at on public.historical_precedent_topics;
create trigger trg_historical_precedent_topics_touch_updated_at
before update on public.historical_precedent_topics
for each row
execute function private.touch_updated_at();

drop trigger if exists trg_historical_case_version_topics_touch_updated_at on public.historical_case_version_topics;
create trigger trg_historical_case_version_topics_touch_updated_at
before update on public.historical_case_version_topics
for each row
execute function private.touch_updated_at();

drop trigger if exists trg_historical_case_version_rental_types_touch_updated_at on public.historical_case_version_rental_types;
create trigger trg_historical_case_version_rental_types_touch_updated_at
before update on public.historical_case_version_rental_types
for each row
execute function private.touch_updated_at();

drop trigger if exists trg_historical_case_version_spaces_touch_updated_at on public.historical_case_version_spaces;
create trigger trg_historical_case_version_spaces_touch_updated_at
before update on public.historical_case_version_spaces
for each row
execute function private.touch_updated_at();

drop trigger if exists trg_enforce_historical_case_version_topic_editability on public.historical_case_version_topics;
create trigger trg_enforce_historical_case_version_topic_editability
before insert or update or delete on public.historical_case_version_topics
for each row
execute function private.enforce_historical_case_version_classification_editability();

drop trigger if exists trg_enforce_historical_case_version_rental_type_editability on public.historical_case_version_rental_types;
create trigger trg_enforce_historical_case_version_rental_type_editability
before insert or update or delete on public.historical_case_version_rental_types
for each row
execute function private.enforce_historical_case_version_classification_editability();

drop trigger if exists trg_enforce_historical_case_version_space_editability on public.historical_case_version_spaces;
create trigger trg_enforce_historical_case_version_space_editability
before insert or update or delete on public.historical_case_version_spaces
for each row
execute function private.enforce_historical_case_version_classification_editability();

insert into public.historical_precedent_topics (
  topic_code,
  display_name,
  description,
  sort_order
)
values
  (
    'venue_clearing',
    'Venue Clearing',
    'Historical precedent involving clearing, reconfiguring, or temporarily vacating canonical venue areas for a rental or activation.',
    10
  ),
  (
    'storage',
    'Storage',
    'Historical precedent involving on-site storage use, storage constraints, or storage-related operational planning.',
    20
  ),
  (
    'offsite_storage',
    'Offsite Storage',
    'Historical precedent involving off-site storage arrangements distinct from ordinary use of the venue storage room.',
    30
  ),
  (
    'responsibility_boundaries',
    'Responsibility Boundaries',
    'Historical precedent involving responsibility splits or boundary-setting across WNC, client, and external parties.',
    40
  ),
  (
    'client_operated_events',
    'Client-Operated Events',
    'Historical precedent involving events materially operated by the client rather than fully managed by WNC.',
    50
  ),
  (
    'production_coordination',
    'Production Coordination',
    'Historical precedent involving production coordination, vendor coordination, or broader event-support planning.',
    60
  ),
  (
    'technical_assessment',
    'Technical Assessment',
    'Historical precedent involving technical feasibility review, production assessment, or capability evaluation.',
    70
  ),
  (
    'electrical_load',
    'Electrical Load',
    'Historical precedent involving electrical-load concerns, power planning, or power-related operational constraints.',
    80
  ),
  (
    'catering_supplier_coordination',
    'Catering and Supplier Coordination',
    'Historical precedent involving catering fit, supplier suitability, or coordination with external food and service providers.',
    90
  ),
  (
    'alcohol_beverage_boundaries',
    'Alcohol and Beverage Boundaries',
    'Historical precedent involving alcohol, beverage-service boundaries, or related operational restrictions.',
    100
  ),
  (
    'production_access',
    'Production Access',
    'Historical precedent involving build-up, setup access, production access windows, or related entry and staging boundaries.',
    110
  ),
  (
    'overtime',
    'Overtime',
    'Historical precedent involving overtime exposure, overtime disputes, or timing overruns beyond agreed operating windows.',
    120
  ),
  (
    'materials_cleanup_damage',
    'Materials, Cleanup, and Damage',
    'Historical precedent involving unusual materials, residue, cleaning burden, restoration work, or damage concerns.',
    130
  ),
  (
    'branding_restrictions',
    'Branding Restrictions',
    'Historical precedent involving branding restrictions, collaboration pressure, or brand-use boundary setting.',
    140
  ),
  (
    'class_schedule_interaction',
    'Class Schedule Interaction',
    'Historical precedent involving interaction between rentals and the venue class schedule or standing programming cadence.',
    150
  ),
  (
    'permits_compliance',
    'Permits and Compliance',
    'Historical precedent involving permits, compliance review, regulatory uncertainty, or contamination-prone compliance handling.',
    160
  )
on conflict (topic_code) do update
set display_name = excluded.display_name,
    description = excluded.description,
    sort_order = excluded.sort_order,
    is_active = true;

alter table public.historical_precedent_topics enable row level security;
alter table public.historical_case_version_topics enable row level security;
alter table public.historical_case_version_rental_types enable row level security;
alter table public.historical_case_version_spaces enable row level security;

revoke all on table public.historical_precedent_topics from public, anon, authenticated, service_role;
revoke all on table public.historical_case_version_topics from public, anon, authenticated, service_role;
revoke all on table public.historical_case_version_rental_types from public, anon, authenticated, service_role;
revoke all on table public.historical_case_version_spaces from public, anon, authenticated, service_role;
