create table if not exists public.technical_equipment_inventory (
  id bigint generated by default as identity primary key,
  equipment_code text not null unique,
  source_item_code text not null unique,
  equipment_category text not null,
  equipment_name text not null,
  quantity_numeric integer,
  quantity_display text not null,
  primary_location text not null,
  availability_status text not null,
  normally_included boolean not null default true,
  exact_count_guaranteed boolean not null default false,
  source_id bigint not null references public.source_registry(id) on delete restrict,
  source_locator text not null,
  conditions_summary text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint technical_equipment_inventory_code_nonempty
    check (btrim(equipment_code) <> ''),
  constraint technical_equipment_inventory_source_item_code_nonempty
    check (btrim(source_item_code) <> ''),
  constraint technical_equipment_inventory_category_check
    check (
      equipment_category in (
        'wellness_equipment',
        'service_equipment',
        'furniture',
        'projection',
        'power',
        'lighting',
        'sound'
      )
    ),
  constraint technical_equipment_inventory_name_nonempty
    check (btrim(equipment_name) <> ''),
  constraint technical_equipment_inventory_quantity_positive
    check (quantity_numeric is null or quantity_numeric > 0),
  constraint technical_equipment_inventory_quantity_display_nonempty
    check (btrim(quantity_display) <> ''),
  constraint technical_equipment_inventory_primary_location_nonempty
    check (btrim(primary_location) <> ''),
  constraint technical_equipment_inventory_availability_status_check
    check (
      availability_status in (
        'standard',
        'available_on_request',
        'must_confirm'
      )
    ),
  constraint technical_equipment_inventory_source_locator_nonempty
    check (btrim(source_locator) <> ''),
  constraint technical_equipment_inventory_conditions_summary_nonempty
    check (
      conditions_summary is null
      or btrim(conditions_summary) <> ''
    )
);

create index if not exists technical_equipment_inventory_lookup_idx
  on public.technical_equipment_inventory (
    equipment_category,
    equipment_code
  );

create table if not exists public.technical_capability_rules (
  rule_id bigint primary key references public.rule_catalogue(id) on delete cascade,
  rule_type text not null,
  technical_area text not null,
  capability_code text,
  requirement_code text,
  equipment_inventory_id bigint references public.technical_equipment_inventory(id) on delete restrict,
  support_status text not null,
  included_in_base_rental boolean not null default false,
  internal_equipment_exists boolean not null default false,
  internal_support_sufficient boolean not null default false,
  client_may_self_organise boolean not null default false,
  wnc_can_coordinate boolean not null default false,
  coordination_fee_possible boolean not null default false,
  requires_confirmation boolean not null default false,
  manual_review_required boolean not null default false,
  conditions_summary text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint technical_capability_rules_rule_type_check
    check (
      rule_type in (
        'capability_availability',
        'requirement_support'
      )
    ),
  constraint technical_capability_rules_technical_area_check
    check (
      technical_area in (
        'connectivity',
        'projection',
        'sound',
        'audio',
        'lighting',
        'power',
        'filming',
        'livestream'
      )
    ),
  constraint technical_capability_rules_capability_code_check
    check (
      capability_code is null
      or capability_code in (
        'wifi',
        'basic_projector',
        'projection_screen',
        'installed_sonos_system',
        'additional_sound_system',
        'microphones',
        'dj_setup',
        'casambi_dimmable_venue_lighting',
        'production_lighting',
        'electrical_groups',
        'voltage_220v',
        'plug_points',
        'basic_extension_cable',
        'filming_setup',
        'livestream_system'
      )
    ),
  constraint technical_capability_rules_requirement_code_check
    check (
      requirement_code is null
      or requirement_code in (
        'standard_wifi',
        'ordinary_audio_playback',
        'amplified_event_sound',
        'microphone_use',
        'dj_audio_setup',
        'basic_projection',
        'projection_with_dedicated_screen',
        'standard_venue_lighting',
        'production_lighting',
        'standard_power_access',
        'high_load_power',
        'filming',
        'dedicated_livestreaming',
        'custom_technical_setup'
      )
    ),
  constraint technical_capability_rules_support_status_check
    check (
      support_status in (
        'standard',
        'available_on_request',
        'must_confirm',
        'external_supplier_required',
        'supported',
        'not_available',
        'requires_confirmation'
      )
    ),
  constraint technical_capability_rules_conditions_summary_nonempty
    check (
      conditions_summary is null
      or btrim(conditions_summary) <> ''
    ),
  constraint technical_capability_rules_semantics
    check (
      (
        rule_type = 'capability_availability'
        and capability_code is not null
        and requirement_code is null
        and support_status in (
          'standard',
          'available_on_request',
          'must_confirm',
          'external_supplier_required',
          'not_available'
        )
      )
      or (
        rule_type = 'requirement_support'
        and requirement_code is not null
        and capability_code is null
        and support_status in (
          'supported',
          'external_supplier_required',
          'requires_confirmation'
        )
      )
    ),
  constraint technical_capability_rules_support_flags
    check (
      (support_status <> 'must_confirm' or requires_confirmation = true)
      and (support_status <> 'requires_confirmation' or requires_confirmation = true)
      and (support_status <> 'not_available' or (internal_equipment_exists = false and internal_support_sufficient = false))
      and (support_status <> 'supported' or internal_support_sufficient = true)
      and (support_status <> 'standard' or internal_support_sufficient = true)
      and (support_status <> 'available_on_request' or internal_support_sufficient = true)
      and (support_status <> 'external_supplier_required' or internal_support_sufficient = false)
      and (coordination_fee_possible = false or wnc_can_coordinate = true)
      and (equipment_inventory_id is null or rule_type = 'capability_availability')
    )
);

create index if not exists technical_capability_rules_lookup_idx
  on public.technical_capability_rules (
    rule_type,
    technical_area,
    capability_code,
    requirement_code
  );

create or replace function private.assert_technical_capability_rule_integrity(p_rule_id bigint)
returns void
language plpgsql
as $$
declare
  current_rule record;
begin
  select
    rc.rule_code,
    rc.rule_domain,
    rc.rule_kind,
    rc.status,
    rc.effective_from,
    rc.effective_until,
    tcr.rule_type,
    tcr.technical_area,
    tcr.capability_code,
    tcr.requirement_code
  into current_rule
  from public.rule_catalogue rc
  join public.technical_capability_rules tcr
    on tcr.rule_id = rc.id
  where rc.id = p_rule_id;

  if not found then
    return;
  end if;

  if current_rule.rule_domain <> 'technical_capability' then
    raise exception 'technical_capability_rules row % must reference rule_domain technical_capability', p_rule_id
      using errcode = '23514';
  end if;

  if current_rule.rule_kind not in ('hard_rule', 'conditional_rule') then
    raise exception 'technical_capability_rules row % must reference a technical_capability hard_rule or conditional_rule', p_rule_id
      using errcode = '23514';
  end if;

  if current_rule.status = 'draft' then
    return;
  end if;

  if exists (
    select 1
    from public.technical_capability_rules other_tcr
    join public.rule_catalogue other_rc
      on other_rc.id = other_tcr.rule_id
    where other_tcr.rule_id <> p_rule_id
      and other_rc.status in ('active', 'superseded', 'retired')
      and other_tcr.rule_type = current_rule.rule_type
      and other_tcr.technical_area = current_rule.technical_area
      and other_tcr.capability_code is not distinct from current_rule.capability_code
      and other_tcr.requirement_code is not distinct from current_rule.requirement_code
      and private.date_windows_overlap(
        current_rule.effective_from,
        current_rule.effective_until,
        other_rc.effective_from,
        other_rc.effective_until
      )
  ) then
    raise exception 'overlapping technical capability rules detected for rule %', current_rule.rule_code
      using errcode = '23514';
  end if;
end;
$$;

create or replace function private.validate_technical_capability_rule_row()
returns trigger
language plpgsql
as $$
begin
  perform private.assert_technical_capability_rule_integrity(new.rule_id);
  return new;
end;
$$;

create or replace function private.validate_technical_capability_rule_catalogue()
returns trigger
language plpgsql
as $$
begin
  perform private.assert_technical_capability_rule_integrity(new.id);
  return new;
end;
$$;

drop trigger if exists trg_technical_equipment_inventory_touch_updated_at on public.technical_equipment_inventory;
create trigger trg_technical_equipment_inventory_touch_updated_at
before update on public.technical_equipment_inventory
for each row
execute function private.touch_updated_at();

drop trigger if exists trg_technical_capability_rules_touch_updated_at on public.technical_capability_rules;
create trigger trg_technical_capability_rules_touch_updated_at
before update on public.technical_capability_rules
for each row
execute function private.touch_updated_at();

drop trigger if exists trg_validate_technical_capability_rule_row on public.technical_capability_rules;
create trigger trg_validate_technical_capability_rule_row
after insert or update on public.technical_capability_rules
for each row
execute function private.validate_technical_capability_rule_row();

drop trigger if exists trg_validate_technical_capability_rule_catalogue on public.rule_catalogue;
create trigger trg_validate_technical_capability_rule_catalogue
after insert or update of rule_domain, rule_kind, status, effective_from, effective_until on public.rule_catalogue
for each row
execute function private.validate_technical_capability_rule_catalogue();

create or replace view public.current_technical_equipment_inventory as
select
  tei.id,
  tei.equipment_code,
  tei.source_item_code,
  tei.equipment_category,
  tei.equipment_name,
  tei.quantity_numeric,
  tei.quantity_display,
  tei.primary_location,
  tei.availability_status,
  tei.normally_included,
  tei.exact_count_guaranteed,
  tei.source_id,
  sr.source_code,
  sr.title as source_title,
  tei.source_locator,
  tei.conditions_summary,
  tei.created_at,
  tei.updated_at
from public.technical_equipment_inventory tei
join public.source_registry sr
  on sr.id = tei.source_id;

create or replace view public.current_technical_capability_rules as
select
  rc.id as rule_id,
  rc.rule_code,
  rc.rule_version,
  rc.status,
  rc.effective_from,
  rc.effective_until,
  rc.plain_language_explanation,
  tcr.rule_type,
  tcr.technical_area,
  tcr.capability_code,
  tcr.requirement_code,
  tcr.equipment_inventory_id,
  tei.equipment_code,
  tei.equipment_name,
  tcr.support_status,
  tcr.included_in_base_rental,
  tcr.internal_equipment_exists,
  tcr.internal_support_sufficient,
  tcr.client_may_self_organise,
  tcr.wnc_can_coordinate,
  tcr.coordination_fee_possible,
  tcr.requires_confirmation,
  tcr.manual_review_required,
  tcr.conditions_summary,
  coalesce(src.primary_source_codes, array[]::text[]) as primary_source_codes,
  coalesce(src.governance_source_codes, array[]::text[]) as governance_source_codes,
  coalesce(src.supporting_source_codes, array[]::text[]) as supporting_source_codes
from public.technical_capability_rules tcr
join public.rule_catalogue rc
  on rc.id = tcr.rule_id
left join public.technical_equipment_inventory tei
  on tei.id = tcr.equipment_inventory_id
left join lateral (
  select
    array_agg(distinct sr.source_code order by sr.source_code)
      filter (where rsl.relation_type = 'primary') as primary_source_codes,
    array_agg(distinct sr.source_code order by sr.source_code)
      filter (where rsl.relation_type = 'governance') as governance_source_codes,
    array_agg(distinct sr.source_code order by sr.source_code)
      filter (where rsl.relation_type = 'supporting') as supporting_source_codes
  from public.rule_source_links rsl
  join public.source_registry sr
    on sr.id = rsl.source_id
  where rsl.rule_id = rc.id
) src on true
where rc.status = 'active'
  and (rc.effective_from is null or rc.effective_from <= current_date)
  and (rc.effective_until is null or rc.effective_until >= current_date);

create or replace function api.get_technical_equipment_inventory(
  p_equipment_code text default null,
  p_equipment_category text default null
)
returns table (
  id bigint,
  equipment_code text,
  source_item_code text,
  equipment_category text,
  equipment_name text,
  quantity_numeric integer,
  quantity_display text,
  primary_location text,
  availability_status text,
  normally_included boolean,
  exact_count_guaranteed boolean,
  source_id bigint,
  source_code text,
  source_title text,
  source_locator text,
  conditions_summary text,
  created_at timestamptz,
  updated_at timestamptz
)
language sql
stable
as $$
  select
    ctei.id,
    ctei.equipment_code,
    ctei.source_item_code,
    ctei.equipment_category,
    ctei.equipment_name,
    ctei.quantity_numeric,
    ctei.quantity_display,
    ctei.primary_location,
    ctei.availability_status,
    ctei.normally_included,
    ctei.exact_count_guaranteed,
    ctei.source_id,
    ctei.source_code,
    ctei.source_title,
    ctei.source_locator,
    ctei.conditions_summary,
    ctei.created_at,
    ctei.updated_at
  from public.current_technical_equipment_inventory ctei
  where (
      p_equipment_code is null
      or ctei.equipment_code = nullif(btrim(p_equipment_code), '')
    )
    and (
      p_equipment_category is null
      or ctei.equipment_category = nullif(btrim(p_equipment_category), '')
    )
  order by ctei.equipment_category, ctei.equipment_code;
$$;

create or replace function api.evaluate_technical_equipment_quantity(
  p_equipment_code text,
  p_requested_quantity integer
)
returns table (
  equipment_id bigint,
  equipment_code text,
  equipment_name text,
  equipment_category text,
  quantity_numeric integer,
  quantity_display text,
  availability_status text,
  exact_count_guaranteed boolean,
  requested_quantity integer,
  quantity_evaluation_status text,
  conditions_summary text,
  source_code text,
  source_title text
)
language plpgsql
stable
as $$
declare
  v_equipment_code text := nullif(btrim(coalesce(p_equipment_code, '')), '');
begin
  if v_equipment_code is null then
    raise exception 'p_equipment_code is required.'
      using errcode = '22023';
  end if;

  if p_requested_quantity is null or p_requested_quantity <= 0 then
    raise exception 'p_requested_quantity must be a positive integer.'
      using errcode = '22023';
  end if;

  return query
  with matched_equipment as (
    select *
    from public.current_technical_equipment_inventory ctei
    where ctei.equipment_code = v_equipment_code
  )
  select
    me.id as equipment_id,
    me.equipment_code,
    me.equipment_name,
    me.equipment_category,
    me.quantity_numeric,
    me.quantity_display,
    me.availability_status,
    me.exact_count_guaranteed,
    p_requested_quantity as requested_quantity,
    case
      when me.quantity_numeric is not null and p_requested_quantity > me.quantity_numeric then 'insufficient_quantity'
      when me.quantity_numeric is null or me.exact_count_guaranteed = false then 'requires_confirmation'
      else 'quantity_available'
    end as quantity_evaluation_status,
    me.conditions_summary,
    me.source_code,
    me.source_title
  from matched_equipment me;

  if found then
    return;
  end if;

  return query
  select
    null::bigint as equipment_id,
    v_equipment_code as equipment_code,
    null::text as equipment_name,
    null::text as equipment_category,
    null::integer as quantity_numeric,
    null::text as quantity_display,
    null::text as availability_status,
    null::boolean as exact_count_guaranteed,
    p_requested_quantity as requested_quantity,
    'no_applicable_equipment'::text as quantity_evaluation_status,
    null::text as conditions_summary,
    null::text as source_code,
    null::text as source_title;
end;
$$;

create or replace function api.get_technical_capability(
  p_rule_type text default null,
  p_capability_code text default null,
  p_requirement_code text default null,
  p_technical_area text default null,
  p_as_of_date date default current_date
)
returns table (
  rule_id bigint,
  rule_code text,
  rule_version integer,
  status text,
  effective_from date,
  effective_until date,
  plain_language_explanation text,
  rule_type text,
  technical_area text,
  capability_code text,
  requirement_code text,
  equipment_inventory_id bigint,
  equipment_code text,
  equipment_name text,
  support_status text,
  included_in_base_rental boolean,
  internal_equipment_exists boolean,
  internal_support_sufficient boolean,
  client_may_self_organise boolean,
  wnc_can_coordinate boolean,
  coordination_fee_possible boolean,
  requires_confirmation boolean,
  manual_review_required boolean,
  conditions_summary text,
  applicability_status text,
  primary_source_codes text[],
  governance_source_codes text[],
  supporting_source_codes text[]
)
language plpgsql
stable
as $$
declare
  v_rule_type text := nullif(btrim(coalesce(p_rule_type, '')), '');
  v_capability_code text := nullif(btrim(coalesce(p_capability_code, '')), '');
  v_requirement_code text := nullif(btrim(coalesce(p_requirement_code, '')), '');
  v_technical_area text := nullif(btrim(coalesce(p_technical_area, '')), '');
  v_as_of_date date := coalesce(p_as_of_date, current_date);
  v_has_matches boolean := false;
begin
  if v_capability_code is not null and v_requirement_code is not null then
    raise exception 'Provide either p_capability_code or p_requirement_code, not both.'
      using errcode = '22023';
  end if;

  select exists (
    select 1
    from public.technical_capability_rules tcr
    join public.rule_catalogue rc
      on rc.id = tcr.rule_id
    where rc.status in ('active', 'superseded', 'retired')
      and (rc.effective_from is null or rc.effective_from <= v_as_of_date)
      and (rc.effective_until is null or rc.effective_until >= v_as_of_date)
      and (v_rule_type is null or tcr.rule_type = v_rule_type)
      and (v_technical_area is null or tcr.technical_area = v_technical_area)
      and (v_capability_code is null or tcr.capability_code = v_capability_code)
      and (v_requirement_code is null or tcr.requirement_code = v_requirement_code)
  )
  into v_has_matches;

  if v_has_matches then
    return query
    select
      rc.id as rule_id,
      rc.rule_code,
      rc.rule_version,
      rc.status,
      rc.effective_from,
      rc.effective_until,
      rc.plain_language_explanation,
      tcr.rule_type,
      tcr.technical_area,
      tcr.capability_code,
      tcr.requirement_code,
      tcr.equipment_inventory_id,
      tei.equipment_code,
      tei.equipment_name,
      tcr.support_status,
      tcr.included_in_base_rental,
      tcr.internal_equipment_exists,
      tcr.internal_support_sufficient,
      tcr.client_may_self_organise,
      tcr.wnc_can_coordinate,
      tcr.coordination_fee_possible,
      tcr.requires_confirmation,
      tcr.manual_review_required,
      tcr.conditions_summary,
      'applies'::text as applicability_status,
      coalesce(src.primary_source_codes, array[]::text[]) as primary_source_codes,
      coalesce(src.governance_source_codes, array[]::text[]) as governance_source_codes,
      coalesce(src.supporting_source_codes, array[]::text[]) as supporting_source_codes
    from public.technical_capability_rules tcr
    join public.rule_catalogue rc
      on rc.id = tcr.rule_id
    left join public.technical_equipment_inventory tei
      on tei.id = tcr.equipment_inventory_id
    left join lateral (
      select
        array_agg(distinct sr.source_code order by sr.source_code)
          filter (where rsl.relation_type = 'primary') as primary_source_codes,
        array_agg(distinct sr.source_code order by sr.source_code)
          filter (where rsl.relation_type = 'governance') as governance_source_codes,
        array_agg(distinct sr.source_code order by sr.source_code)
          filter (where rsl.relation_type = 'supporting') as supporting_source_codes
      from public.rule_source_links rsl
      join public.source_registry sr
        on sr.id = rsl.source_id
      where rsl.rule_id = rc.id
    ) src on true
    where rc.status in ('active', 'superseded', 'retired')
      and (rc.effective_from is null or rc.effective_from <= v_as_of_date)
      and (rc.effective_until is null or rc.effective_until >= v_as_of_date)
      and (v_rule_type is null or tcr.rule_type = v_rule_type)
      and (v_technical_area is null or tcr.technical_area = v_technical_area)
      and (v_capability_code is null or tcr.capability_code = v_capability_code)
      and (v_requirement_code is null or tcr.requirement_code = v_requirement_code)
    order by
      tcr.rule_type,
      tcr.technical_area,
      coalesce(tcr.capability_code, tcr.requirement_code),
      rc.rule_code;
    return;
  end if;

  return query
  select
    null::bigint as rule_id,
    null::text as rule_code,
    null::integer as rule_version,
    null::text as status,
    null::date as effective_from,
    null::date as effective_until,
    null::text as plain_language_explanation,
    v_rule_type as rule_type,
    v_technical_area as technical_area,
    v_capability_code as capability_code,
    v_requirement_code as requirement_code,
    null::bigint as equipment_inventory_id,
    null::text as equipment_code,
    null::text as equipment_name,
    null::text as support_status,
    null::boolean as included_in_base_rental,
    null::boolean as internal_equipment_exists,
    null::boolean as internal_support_sufficient,
    null::boolean as client_may_self_organise,
    null::boolean as wnc_can_coordinate,
    null::boolean as coordination_fee_possible,
    null::boolean as requires_confirmation,
    null::boolean as manual_review_required,
    null::text as conditions_summary,
    case
      when v_rule_type = 'capability_availability' and v_capability_code is null then 'insufficient_information'
      when v_rule_type = 'requirement_support' and v_requirement_code is null then 'insufficient_information'
      when v_rule_type is null and v_capability_code is null and v_requirement_code is null then 'insufficient_information'
      else 'no_applicable_rule'
    end as applicability_status,
    array[]::text[] as primary_source_codes,
    array[]::text[] as governance_source_codes,
    array[]::text[] as supporting_source_codes;
end;
$$;

create or replace function api.evaluate_technical_requirement(
  p_requirement_code text,
  p_as_of_date date default current_date
)
returns table (
  rule_id bigint,
  rule_code text,
  rule_version integer,
  status text,
  effective_from date,
  effective_until date,
  plain_language_explanation text,
  rule_type text,
  technical_area text,
  capability_code text,
  requirement_code text,
  equipment_inventory_id bigint,
  equipment_code text,
  equipment_name text,
  support_status text,
  included_in_base_rental boolean,
  internal_equipment_exists boolean,
  internal_support_sufficient boolean,
  client_may_self_organise boolean,
  wnc_can_coordinate boolean,
  coordination_fee_possible boolean,
  requires_confirmation boolean,
  manual_review_required boolean,
  conditions_summary text,
  applicability_status text,
  primary_source_codes text[],
  governance_source_codes text[],
  supporting_source_codes text[]
)
language sql
stable
as $$
  select *
  from api.get_technical_capability(
    'requirement_support',
    null,
    p_requirement_code,
    null,
    p_as_of_date
  );
$$;

grant select on public.current_technical_equipment_inventory to anon, authenticated, service_role;
grant select on public.current_technical_capability_rules to anon, authenticated, service_role;
grant execute on function api.get_technical_equipment_inventory(text, text) to anon, authenticated, service_role;
grant execute on function api.evaluate_technical_equipment_quantity(text, integer) to anon, authenticated, service_role;
grant execute on function api.get_technical_capability(text, text, text, text, date) to anon, authenticated, service_role;
grant execute on function api.evaluate_technical_requirement(text, date) to anon, authenticated, service_role;
