create or replace function private.normalize_historical_case_alias_text(p_alias_text text)
returns text
language sql
immutable
as $$
  select lower(regexp_replace(btrim(p_alias_text), '\s+', ' ', 'g'));
$$;

create table if not exists public.historical_cases (
  id bigint generated by default as identity primary key,
  case_code text not null unique,
  canonical_title text not null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint historical_cases_case_code_nonempty
    check (btrim(case_code) <> ''),
  constraint historical_cases_case_code_format_check
    check (case_code ~ '^HC-[0-9]{3,}$'),
  constraint historical_cases_canonical_title_nonempty
    check (btrim(canonical_title) <> '')
);

create table if not exists public.historical_case_aliases (
  id bigint generated by default as identity primary key,
  historical_case_id bigint not null references public.historical_cases(id) on delete cascade,
  alias_text text not null,
  alias_type text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint historical_case_aliases_alias_text_nonempty
    check (btrim(alias_text) <> ''),
  constraint historical_case_aliases_alias_type_check
    check (alias_type is null or alias_type in ('client', 'brand', 'event', 'person', 'shorthand', 'other')),
  constraint historical_case_aliases_alias_type_nonempty
    check (alias_type is null or btrim(alias_type) <> '')
);

create unique index if not exists historical_case_aliases_case_alias_unique_idx
  on public.historical_case_aliases (
    historical_case_id,
    private.normalize_historical_case_alias_text(alias_text)
  );

create table if not exists public.historical_case_versions (
  id bigint generated by default as identity primary key,
  historical_case_id bigint not null references public.historical_cases(id) on delete restrict,
  version_number integer not null,
  governance_status text not null,
  precedent_availability text not null,
  precedent_type text not null,
  evidence_strength text not null,
  historical_event_status text not null,
  temporal_precision text not null,
  event_date_start date,
  event_date_end date,
  temporal_note text,
  curated_narrative text not null,
  confidentiality_level_id bigint not null references public.knowledge_confidentiality_levels(id) on delete restrict,
  personal_information_status text not null default 'unknown',
  personal_information_notes text,
  contains_historical_value_only_content boolean not null,
  supersedes_version_id bigint references public.historical_case_versions(id) on delete restrict,
  activated_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint historical_case_versions_version_positive
    check (version_number > 0),
  constraint historical_case_versions_governance_status_check
    check (governance_status in ('draft', 'active', 'superseded', 'retired')),
  constraint historical_case_versions_precedent_availability_check
    check (precedent_availability in ('active', 'limited', 'held', 'archived')),
  constraint historical_case_versions_precedent_type_check
    check (precedent_type in ('full_case', 'limited_precedent', 'cautionary_precedent')),
  constraint historical_case_versions_evidence_strength_check
    check (evidence_strength in ('strong', 'moderate', 'limited')),
  constraint historical_case_versions_historical_event_status_check
    check (historical_event_status in ('completed', 'cancelled', 'postponed', 'planning_only', 'partial_or_unclear')),
  constraint historical_case_versions_temporal_precision_check
    check (temporal_precision in ('exact', 'approximate', 'month', 'year', 'unknown')),
  constraint historical_case_versions_event_date_range_check
    check (event_date_end is null or event_date_start is null or event_date_end >= event_date_start),
  constraint historical_case_versions_temporal_note_nonempty
    check (temporal_note is null or btrim(temporal_note) <> ''),
  constraint historical_case_versions_curated_narrative_nonempty
    check (btrim(curated_narrative) <> ''),
  constraint historical_case_versions_personal_information_status_check
    check (personal_information_status in ('yes', 'no', 'unknown')),
  constraint historical_case_versions_personal_information_notes_nonempty
    check (personal_information_notes is null or btrim(personal_information_notes) <> ''),
  constraint historical_case_versions_unique_version
    unique (historical_case_id, version_number),
  constraint historical_case_versions_temporal_precision_consistency_check
    check (
      (
        temporal_precision = 'unknown'
        and event_date_start is null
        and event_date_end is null
      )
      or (
        temporal_precision = 'exact'
        and event_date_start is not null
        and event_date_end = event_date_start
      )
      or (
        temporal_precision = 'approximate'
        and event_date_start is not null
        and event_date_end is not null
      )
      or (
        temporal_precision = 'month'
        and event_date_start is not null
        and event_date_end is not null
        and event_date_start = date_trunc('month', event_date_start)::date
        and event_date_end = (date_trunc('month', event_date_start) + interval '1 month - 1 day')::date
      )
      or (
        temporal_precision = 'year'
        and event_date_start is not null
        and event_date_end is not null
        and event_date_start = make_date(extract(year from event_date_start)::integer, 1, 1)
        and event_date_end = make_date(extract(year from event_date_start)::integer, 12, 31)
      )
    )
);

create unique index if not exists historical_case_versions_one_active_version_per_case_idx
  on public.historical_case_versions (historical_case_id)
  where governance_status = 'active';

create or replace function private.validate_historical_case_version_supersession()
returns trigger
language plpgsql
as $$
declare
  superseded_case_id bigint;
  superseded_version_number integer;
begin
  if new.supersedes_version_id is null then
    return new;
  end if;

  if new.id is not null and new.supersedes_version_id = new.id then
    raise exception 'historical case version cannot supersede itself'
      using errcode = '23514';
  end if;

  select hcv.historical_case_id, hcv.version_number
  into superseded_case_id, superseded_version_number
  from public.historical_case_versions hcv
  where hcv.id = new.supersedes_version_id;

  if superseded_case_id is not null and superseded_case_id <> new.historical_case_id then
    raise exception 'historical case version can only supersede a prior version from the same historical case'
      using errcode = '23514';
  end if;

  if superseded_version_number is not null and new.version_number <= superseded_version_number then
    raise exception 'historical case version number must increase when superseding a prior version'
      using errcode = '23514';
  end if;

  return new;
end;
$$;

create or replace function private.enforce_historical_case_version_lifecycle()
returns trigger
language plpgsql
as $$
begin
  if tg_op = 'UPDATE' then
    if old.governance_status = 'draft' and new.governance_status not in ('draft', 'active', 'retired') then
      raise exception 'draft historical case versions can only remain draft, become active, or be retired'
        using errcode = '23514';
    end if;

    if old.governance_status = 'active' and new.governance_status not in ('active', 'superseded', 'retired') then
      raise exception 'active historical case versions can only remain active, become superseded, or be retired'
        using errcode = '23514';
    end if;

    if old.governance_status = 'superseded' and new.governance_status not in ('superseded', 'retired') then
      raise exception 'superseded historical case versions cannot become draft or active again'
        using errcode = '23514';
    end if;

    if old.governance_status = 'retired' and new.governance_status <> 'retired' then
      raise exception 'retired historical case versions are immutable lifecycle endpoints'
        using errcode = '23514';
    end if;

    if old.governance_status <> 'draft' and (
      old.historical_case_id is distinct from new.historical_case_id
      or old.version_number is distinct from new.version_number
      or old.precedent_availability is distinct from new.precedent_availability
      or old.precedent_type is distinct from new.precedent_type
      or old.evidence_strength is distinct from new.evidence_strength
      or old.historical_event_status is distinct from new.historical_event_status
      or old.temporal_precision is distinct from new.temporal_precision
      or old.event_date_start is distinct from new.event_date_start
      or old.event_date_end is distinct from new.event_date_end
      or old.temporal_note is distinct from new.temporal_note
      or old.curated_narrative is distinct from new.curated_narrative
      or old.confidentiality_level_id is distinct from new.confidentiality_level_id
      or old.personal_information_status is distinct from new.personal_information_status
      or old.personal_information_notes is distinct from new.personal_information_notes
      or old.contains_historical_value_only_content is distinct from new.contains_historical_value_only_content
      or old.supersedes_version_id is distinct from new.supersedes_version_id
    ) then
      raise exception 'non-draft historical case versions cannot be materially rewritten; create a superseding version instead'
        using errcode = '23514';
    end if;
  end if;

  if new.governance_status = 'draft' and new.activated_at is not null then
    raise exception 'draft historical case versions cannot record activated_at'
      using errcode = '23514';
  end if;

  if new.governance_status = 'active' and new.activated_at is null then
    new.activated_at := timezone('utc', now());
  end if;

  if new.governance_status = 'superseded' and new.activated_at is null then
    raise exception 'superseded historical case versions must retain an activated_at timestamp'
      using errcode = '23514';
  end if;

  return new;
end;
$$;

drop trigger if exists trg_historical_cases_touch_updated_at on public.historical_cases;
create trigger trg_historical_cases_touch_updated_at
before update on public.historical_cases
for each row
execute function private.touch_updated_at();

drop trigger if exists trg_historical_case_aliases_touch_updated_at on public.historical_case_aliases;
create trigger trg_historical_case_aliases_touch_updated_at
before update on public.historical_case_aliases
for each row
execute function private.touch_updated_at();

drop trigger if exists trg_historical_case_versions_touch_updated_at on public.historical_case_versions;
create trigger trg_historical_case_versions_touch_updated_at
before update on public.historical_case_versions
for each row
execute function private.touch_updated_at();

drop trigger if exists trg_validate_historical_case_version_supersession on public.historical_case_versions;
create trigger trg_validate_historical_case_version_supersession
before insert or update on public.historical_case_versions
for each row
execute function private.validate_historical_case_version_supersession();

drop trigger if exists trg_enforce_historical_case_version_lifecycle on public.historical_case_versions;
create trigger trg_enforce_historical_case_version_lifecycle
before insert or update on public.historical_case_versions
for each row
execute function private.enforce_historical_case_version_lifecycle();

alter table public.historical_cases enable row level security;
alter table public.historical_case_aliases enable row level security;
alter table public.historical_case_versions enable row level security;

revoke all on table
  public.historical_cases,
  public.historical_case_aliases,
  public.historical_case_versions
from anon, authenticated, service_role;
