create schema if not exists api;
create schema if not exists private;

create or replace function private.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

create or replace function private.normalize_rental_duration_hours(p_duration_minutes integer)
returns integer
language sql
immutable
as $$
  select case
    when p_duration_minutes is null or p_duration_minutes <= 0 then null
    else ceil(p_duration_minutes::numeric / 60.0)::integer
  end;
$$;

create table if not exists public.source_registry (
  id bigint generated by default as identity primary key,
  source_code text not null unique,
  title text not null,
  source_type text not null,
  authority_level text not null,
  lifecycle_status text not null,
  original_filename text not null,
  relative_source_path text not null unique,
  effective_date date,
  notes text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint source_registry_authority_level_check
    check (authority_level in ('authoritative', 'guidance', 'reference_only', 'unverified')),
  constraint source_registry_source_code_nonempty
    check (btrim(source_code) <> ''),
  constraint source_registry_title_nonempty
    check (btrim(title) <> ''),
  constraint source_registry_source_type_nonempty
    check (btrim(source_type) <> ''),
  constraint source_registry_lifecycle_status_nonempty
    check (btrim(lifecycle_status) <> ''),
  constraint source_registry_original_filename_nonempty
    check (btrim(original_filename) <> ''),
  constraint source_registry_relative_source_path_nonempty
    check (btrim(relative_source_path) <> '')
);

create table if not exists public.rental_types (
  id bigint generated by default as identity primary key,
  rental_type_code text not null unique,
  display_name text not null,
  description text not null,
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint rental_types_code_nonempty check (btrim(rental_type_code) <> ''),
  constraint rental_types_display_name_nonempty check (btrim(display_name) <> ''),
  constraint rental_types_description_nonempty check (btrim(description) <> '')
);

create table if not exists public.venue_spaces (
  id bigint generated by default as identity primary key,
  space_code text not null unique,
  display_name text not null,
  description text not null,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint venue_spaces_code_nonempty check (btrim(space_code) <> ''),
  constraint venue_spaces_display_name_nonempty check (btrim(display_name) <> ''),
  constraint venue_spaces_description_nonempty check (btrim(description) <> ''),
  constraint venue_spaces_sort_order_nonnegative check (sort_order >= 0)
);

create table if not exists public.rule_catalogue (
  id bigint generated by default as identity primary key,
  rule_code text not null,
  rule_domain text not null,
  rule_kind text not null,
  rule_version integer not null,
  status text not null,
  effective_from date,
  effective_until date,
  plain_language_explanation text not null,
  owner_role text,
  supersedes_rule_id bigint references public.rule_catalogue(id) on delete restrict,
  last_reviewed_at date,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint rule_catalogue_rule_code_nonempty check (btrim(rule_code) <> ''),
  constraint rule_catalogue_rule_domain_nonempty check (btrim(rule_domain) <> ''),
  constraint rule_catalogue_rule_kind_check check (rule_kind in ('hard_rule', 'conditional_rule')),
  constraint rule_catalogue_rule_version_positive check (rule_version > 0),
  constraint rule_catalogue_status_check check (status in ('draft', 'active', 'superseded', 'retired')),
  constraint rule_catalogue_date_range_check
    check (effective_until is null or effective_from is null or effective_until >= effective_from),
  constraint rule_catalogue_plain_language_nonempty check (btrim(plain_language_explanation) <> ''),
  constraint rule_catalogue_version_unique unique (rule_code, rule_version)
);

create unique index if not exists rule_catalogue_one_active_version_per_code_idx
  on public.rule_catalogue (rule_code)
  where status = 'active';

create table if not exists public.rule_source_links (
  id bigint generated by default as identity primary key,
  rule_id bigint not null references public.rule_catalogue(id) on delete cascade,
  source_id bigint not null references public.source_registry(id) on delete restrict,
  relation_type text not null,
  citation_locator text,
  notes text,
  created_at timestamptz not null default timezone('utc', now()),
  constraint rule_source_links_relation_type_check
    check (relation_type in ('primary', 'supporting', 'governance', 'conflict')),
  constraint rule_source_links_unique unique (rule_id, source_id, relation_type)
);

create or replace function private.validate_rule_supersession()
returns trigger
language plpgsql
as $$
declare
  superseded_code text;
begin
  if new.supersedes_rule_id is null then
    return new;
  end if;

  if new.id is not null and new.supersedes_rule_id = new.id then
    raise exception 'rule cannot supersede itself'
      using errcode = '23514';
  end if;

  select rule_code
  into superseded_code
  from public.rule_catalogue
  where id = new.supersedes_rule_id;

  if superseded_code is not null and superseded_code <> new.rule_code then
    raise exception 'rule can only supersede a prior version with the same rule_code'
      using errcode = '23514';
  end if;

  return new;
end;
$$;

create or replace function private.enforce_rule_provenance_for_rule()
returns trigger
language plpgsql
as $$
begin
  if new.status in ('active', 'superseded', 'retired')
     and not exists (
       select 1
       from public.rule_source_links rsl
       where rsl.rule_id = new.id
         and rsl.relation_type in ('primary', 'governance')
     ) then
    raise exception 'rule % must have at least one primary or governance source link before commit', new.rule_code
      using errcode = '23514';
  end if;

  return null;
end;
$$;

create or replace function private.enforce_rule_provenance_for_link()
returns trigger
language plpgsql
as $$
declare
  target_rule_id bigint;
  target_status text;
  target_rule_code text;
begin
  target_rule_id := coalesce(new.rule_id, old.rule_id);

  select status, rule_code
  into target_status, target_rule_code
  from public.rule_catalogue
  where id = target_rule_id;

  if not found then
    return null;
  end if;

  if target_status in ('active', 'superseded', 'retired')
     and not exists (
       select 1
       from public.rule_source_links rsl
       where rsl.rule_id = target_rule_id
         and rsl.relation_type in ('primary', 'governance')
     ) then
    raise exception 'rule % must have at least one primary or governance source link before commit', target_rule_code
      using errcode = '23514';
  end if;

  return null;
end;
$$;

drop trigger if exists trg_source_registry_touch_updated_at on public.source_registry;
create trigger trg_source_registry_touch_updated_at
before update on public.source_registry
for each row
execute function private.touch_updated_at();

drop trigger if exists trg_rental_types_touch_updated_at on public.rental_types;
create trigger trg_rental_types_touch_updated_at
before update on public.rental_types
for each row
execute function private.touch_updated_at();

drop trigger if exists trg_venue_spaces_touch_updated_at on public.venue_spaces;
create trigger trg_venue_spaces_touch_updated_at
before update on public.venue_spaces
for each row
execute function private.touch_updated_at();

drop trigger if exists trg_rule_catalogue_touch_updated_at on public.rule_catalogue;
create trigger trg_rule_catalogue_touch_updated_at
before update on public.rule_catalogue
for each row
execute function private.touch_updated_at();

drop trigger if exists trg_validate_rule_supersession on public.rule_catalogue;
create trigger trg_validate_rule_supersession
before insert or update on public.rule_catalogue
for each row
execute function private.validate_rule_supersession();

drop trigger if exists rule_catalogue_requires_provenance on public.rule_catalogue;
create constraint trigger rule_catalogue_requires_provenance
after insert or update of status on public.rule_catalogue
deferrable initially deferred
for each row
execute function private.enforce_rule_provenance_for_rule();

drop trigger if exists rule_source_links_requires_provenance on public.rule_source_links;
create constraint trigger rule_source_links_requires_provenance
after insert or update or delete on public.rule_source_links
deferrable initially deferred
for each row
execute function private.enforce_rule_provenance_for_link();
