create table if not exists public.rental_case_facts (
  id bigint generated by default as identity primary key,
  rental_case_fact_uuid uuid not null default extensions.gen_random_uuid(),
  rental_case_id bigint not null references public.rental_cases(id) on delete restrict,
  field_code text not null,
  domain_code text not null,
  value_payload jsonb not null,
  source_reference text not null,
  established_case_revision integer not null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint rental_case_facts_uuid_unique unique (rental_case_fact_uuid),
  constraint rental_case_facts_case_id_unique unique (id, rental_case_id),
  constraint rental_case_facts_case_field_unique unique (rental_case_id, field_code),
  constraint rental_case_facts_field_code_nonempty check (btrim(field_code) <> ''),
  constraint rental_case_facts_domain_code_nonempty check (btrim(domain_code) <> ''),
  constraint rental_case_facts_value_payload_present check (jsonb_typeof(value_payload) is not null),
  constraint rental_case_facts_source_reference_nonempty check (btrim(source_reference) <> ''),
  constraint rental_case_facts_established_case_revision_nonnegative check (established_case_revision >= 0)
);

create index if not exists rental_case_facts_case_domain_idx
  on public.rental_case_facts (rental_case_id, domain_code, field_code);

create table if not exists public.inbound_source_records (
  id bigint generated by default as identity primary key,
  inbound_source_record_uuid uuid not null default extensions.gen_random_uuid(),
  source_system_code text not null,
  source_record_type text not null,
  dedupe_key text not null,
  source_hash text not null,
  external_source_id text,
  conversation_reference text,
  sender_actor_type text,
  sender_actor_reference text,
  case_reference_hint text,
  resolved_rental_case_id bigint references public.rental_cases(id) on delete restrict,
  association_status text not null,
  association_basis text,
  occurred_at timestamptz not null,
  received_at timestamptz,
  source_location_reference text,
  confidentiality_posture text,
  pi_posture text,
  evidence_excerpt text,
  created_at timestamptz not null default timezone('utc', now()),
  constraint inbound_source_records_uuid_unique unique (inbound_source_record_uuid),
  constraint inbound_source_records_system_dedupe_unique unique (source_system_code, dedupe_key),
  constraint inbound_source_records_source_system_check
    check (
      source_system_code in (
        'email',
        'manual_input',
        'intake_form',
        'external_platform',
        'call_summary',
        'site_visit_summary',
        'supplier_communication',
        'integration_event'
      )
    ),
  constraint inbound_source_records_source_record_type_check
    check (
      source_record_type in (
        'message',
        'form_submission',
        'operator_note',
        'call_summary',
        'site_visit_summary',
        'platform_event',
        'supplier_message',
        'integration_event'
      )
    ),
  constraint inbound_source_records_dedupe_key_nonempty check (btrim(dedupe_key) <> ''),
  constraint inbound_source_records_source_hash_nonempty check (btrim(source_hash) <> ''),
  constraint inbound_source_records_external_source_id_nonempty
    check (external_source_id is null or btrim(external_source_id) <> ''),
  constraint inbound_source_records_conversation_reference_nonempty
    check (conversation_reference is null or btrim(conversation_reference) <> ''),
  constraint inbound_source_records_sender_actor_type_check
    check (
      sender_actor_type is null
      or sender_actor_type in ('client', 'wnc', 'external_supplier', 'operator', 'system', 'unknown')
    ),
  constraint inbound_source_records_sender_actor_reference_nonempty
    check (sender_actor_reference is null or btrim(sender_actor_reference) <> ''),
  constraint inbound_source_records_case_reference_hint_nonempty
    check (case_reference_hint is null or btrim(case_reference_hint) <> ''),
  constraint inbound_source_records_association_status_check
    check (association_status in ('resolved', 'case_association_required', 'rejected')),
  constraint inbound_source_records_association_basis_nonempty
    check (association_basis is null or btrim(association_basis) <> ''),
  constraint inbound_source_records_received_after_occurred_check
    check (received_at is null or received_at >= occurred_at),
  constraint inbound_source_records_source_location_reference_nonempty
    check (source_location_reference is null or btrim(source_location_reference) <> ''),
  constraint inbound_source_records_confidentiality_posture_nonempty
    check (confidentiality_posture is null or btrim(confidentiality_posture) <> ''),
  constraint inbound_source_records_pi_posture_nonempty
    check (pi_posture is null or btrim(pi_posture) <> ''),
  constraint inbound_source_records_evidence_excerpt_length_check
    check (evidence_excerpt is null or char_length(evidence_excerpt) <= 500),
  constraint inbound_source_records_resolved_requires_case_check
    check (
      (association_status = 'resolved' and resolved_rental_case_id is not null)
      or (association_status <> 'resolved' and resolved_rental_case_id is null)
    )
);

create index if not exists inbound_source_records_case_occurred_at_idx
  on public.inbound_source_records (resolved_rental_case_id, occurred_at desc)
  where resolved_rental_case_id is not null;

create table if not exists public.inbound_observations (
  id bigint generated by default as identity primary key,
  inbound_observation_uuid uuid not null default extensions.gen_random_uuid(),
  inbound_source_record_id bigint not null references public.inbound_source_records(id) on delete restrict,
  rental_case_id bigint references public.rental_cases(id) on delete restrict,
  reported_field_code text not null,
  reported_domain_code text,
  target_field_code text,
  target_domain_code text,
  observation_type text not null,
  claim_kind text not null,
  candidate_value_payload jsonb not null,
  source_evidence_reference text not null,
  status text not null,
  observation_identity_key text not null,
  asserted_by_party_type text,
  asserted_by_reference text,
  source_excerpt text,
  observed_against_case_revision integer,
  extraction_confidence numeric(6, 5),
  ambiguity_flags text[] not null default '{}'::text[],
  supersedes_inbound_observation_id bigint references public.inbound_observations(id) on delete restrict,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint inbound_observations_uuid_unique unique (inbound_observation_uuid),
  constraint inbound_observations_source_identity_unique unique (inbound_source_record_id, observation_identity_key),
  constraint inbound_observations_reported_field_code_nonempty check (btrim(reported_field_code) <> ''),
  constraint inbound_observations_reported_domain_code_nonempty
    check (reported_domain_code is null or btrim(reported_domain_code) <> ''),
  constraint inbound_observations_target_field_code_nonempty
    check (target_field_code is null or btrim(target_field_code) <> ''),
  constraint inbound_observations_target_domain_code_nonempty
    check (target_domain_code is null or btrim(target_domain_code) <> ''),
  constraint inbound_observations_target_pair_check
    check (
      (target_field_code is null and target_domain_code is null)
      or (target_field_code is not null and target_domain_code is not null)
    ),
  constraint inbound_observations_observation_type_check
    check (
      observation_type in (
        'fact_candidate',
        'request_candidate',
        'change_candidate',
        'confirmation_candidate',
        'case_decision_candidate',
        'requirement_evidence_candidate',
        'unknown_or_unmapped'
      )
    ),
  constraint inbound_observations_claim_kind_check
    check (
      claim_kind in (
        'new_information',
        'change_request',
        'exception_request',
        'confirmation',
        'requirement_evidence',
        'question_answer',
        'unknown'
      )
    ),
  constraint inbound_observations_source_evidence_reference_nonempty check (btrim(source_evidence_reference) <> ''),
  constraint inbound_observations_status_check
    check (status in ('candidate', 'validated', 'rejected', 'consumed', 'superseded', 'unmapped', 'quarantined')),
  constraint inbound_observations_identity_key_nonempty check (btrim(observation_identity_key) <> ''),
  constraint inbound_observations_asserted_by_party_type_check
    check (
      asserted_by_party_type is null
      or asserted_by_party_type in ('client', 'wnc', 'external_supplier', 'operator', 'system', 'unknown')
    ),
  constraint inbound_observations_asserted_by_reference_nonempty
    check (asserted_by_reference is null or btrim(asserted_by_reference) <> ''),
  constraint inbound_observations_source_excerpt_length_check
    check (source_excerpt is null or char_length(source_excerpt) <= 500),
  constraint inbound_observations_observed_against_case_revision_nonnegative
    check (observed_against_case_revision is null or observed_against_case_revision >= 0),
  constraint inbound_observations_extraction_confidence_range_check
    check (
      extraction_confidence is null
      or (extraction_confidence >= 0 and extraction_confidence <= 1)
    ),
  constraint inbound_observations_ambiguity_flags_check
    check (private.workflow_text_array_values_nonempty(ambiguity_flags)),
  constraint inbound_observations_supersedes_self_check
    check (supersedes_inbound_observation_id is null or supersedes_inbound_observation_id <> id)
);

create index if not exists inbound_observations_case_status_idx
  on public.inbound_observations (rental_case_id, status, created_at desc)
  where rental_case_id is not null;

create table if not exists public.inbound_observation_effects (
  id bigint generated by default as identity primary key,
  inbound_observation_effect_uuid uuid not null default extensions.gen_random_uuid(),
  inbound_observation_id bigint not null unique references public.inbound_observations(id) on delete restrict,
  rental_case_id bigint references public.rental_cases(id) on delete restrict,
  disposition_code text not null,
  revalidation_required boolean not null default true,
  stale_observation boolean not null default false,
  reason_codes text[] not null default '{}'::text[],
  linked_open_question_id bigint,
  linked_requirement_id bigint,
  linked_proposed_change_id bigint,
  linked_case_decision_id bigint,
  linked_reschedule_request_id bigint,
  workflow_event_id bigint,
  created_at timestamptz not null default timezone('utc', now()),
  constraint inbound_observation_effects_uuid_unique unique (inbound_observation_effect_uuid),
  constraint inbound_observation_effects_disposition_code_check
    check (
      disposition_code in (
        'no_workflow_effect',
        'open_question_answer_candidate',
        'create_proposed_change',
        'create_case_decision_candidate',
        'create_reschedule_request',
        'record_confirmation_candidate',
        'record_requirement_evidence_candidate',
        'manual_mapping_required',
        'reject_quarantine',
        'case_association_required'
      )
    ),
  constraint inbound_observation_effects_reason_codes_check
    check (private.workflow_text_array_values_nonempty(reason_codes)),
  constraint inbound_observation_effects_single_link_target_check
    check (
      (
        case when linked_open_question_id is null then 0 else 1 end
        + case when linked_requirement_id is null then 0 else 1 end
        + case when linked_proposed_change_id is null then 0 else 1 end
        + case when linked_case_decision_id is null then 0 else 1 end
        + case when linked_reschedule_request_id is null then 0 else 1 end
      ) <= 1
    ),
  constraint inbound_observation_effects_disposition_target_requirement_check
    check (
      (disposition_code <> 'open_question_answer_candidate' or linked_open_question_id is not null)
      and (disposition_code <> 'create_proposed_change' or linked_proposed_change_id is not null)
      and (disposition_code <> 'create_case_decision_candidate' or linked_case_decision_id is not null)
      and (disposition_code <> 'create_reschedule_request' or linked_reschedule_request_id is not null)
      and (disposition_code <> 'record_requirement_evidence_candidate' or linked_requirement_id is not null)
    ),
  constraint inbound_observation_effects_open_question_fkey
    foreign key (linked_open_question_id, rental_case_id)
    references public.rental_case_open_questions(id, rental_case_id)
    on delete restrict,
  constraint inbound_observation_effects_requirement_fkey
    foreign key (linked_requirement_id, rental_case_id)
    references public.rental_case_requirements(id, rental_case_id)
    on delete restrict,
  constraint inbound_observation_effects_proposed_change_fkey
    foreign key (linked_proposed_change_id, rental_case_id)
    references public.rental_case_proposed_changes(id, rental_case_id)
    on delete restrict,
  constraint inbound_observation_effects_case_decision_fkey
    foreign key (linked_case_decision_id, rental_case_id)
    references public.rental_case_decisions(id, rental_case_id)
    on delete restrict,
  constraint inbound_observation_effects_reschedule_request_fkey
    foreign key (linked_reschedule_request_id, rental_case_id)
    references public.rental_case_reschedule_requests(id, rental_case_id)
    on delete restrict,
  constraint inbound_observation_effects_workflow_event_fkey
    foreign key (workflow_event_id, rental_case_id)
    references public.workflow_events(id, rental_case_id)
    on delete restrict
);

create index if not exists inbound_observation_effects_case_created_at_idx
  on public.inbound_observation_effects (rental_case_id, created_at desc)
  where rental_case_id is not null;

drop trigger if exists trg_rental_case_facts_touch_updated_at on public.rental_case_facts;
create trigger trg_rental_case_facts_touch_updated_at
before update on public.rental_case_facts
for each row
execute function private.touch_updated_at();

drop trigger if exists trg_inbound_observations_touch_updated_at on public.inbound_observations;
create trigger trg_inbound_observations_touch_updated_at
before update on public.inbound_observations
for each row
execute function private.touch_updated_at();

drop trigger if exists trg_inbound_source_records_append_only_update on public.inbound_source_records;
create trigger trg_inbound_source_records_append_only_update
before update on public.inbound_source_records
for each row
execute function private.workflow_append_only_guard();

drop trigger if exists trg_inbound_source_records_append_only_delete on public.inbound_source_records;
create trigger trg_inbound_source_records_append_only_delete
before delete on public.inbound_source_records
for each row
execute function private.workflow_append_only_guard();

drop trigger if exists trg_inbound_observation_effects_append_only_update on public.inbound_observation_effects;
create trigger trg_inbound_observation_effects_append_only_update
before update on public.inbound_observation_effects
for each row
execute function private.workflow_append_only_guard();

drop trigger if exists trg_inbound_observation_effects_append_only_delete on public.inbound_observation_effects;
create trigger trg_inbound_observation_effects_append_only_delete
before delete on public.inbound_observation_effects
for each row
execute function private.workflow_append_only_guard();

alter table public.rental_case_facts enable row level security;
alter table public.inbound_source_records enable row level security;
alter table public.inbound_observations enable row level security;
alter table public.inbound_observation_effects enable row level security;

revoke all on table
  public.rental_case_facts,
  public.inbound_source_records,
  public.inbound_observations,
  public.inbound_observation_effects
from anon, authenticated, service_role;
