create table if not exists public.historical_case_rule_relationship_types (
  id bigint generated by default as identity primary key,
  relationship_code text not null unique,
  display_name text not null,
  description text not null,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint hcrrt_code_nonempty
    check (btrim(relationship_code) <> ''),
  constraint hcrrt_display_name_nonempty
    check (btrim(display_name) <> ''),
  constraint hcrrt_description_nonempty
    check (btrim(description) <> ''),
  constraint hcrrt_sort_order_nonnegative
    check (sort_order >= 0)
);

create table if not exists public.historical_case_version_logical_rules (
  id bigint generated by default as identity primary key,
  historical_case_version_id bigint not null references public.historical_case_versions(id) on delete cascade,
  rule_code text not null references public.logical_rules(rule_code) on delete restrict,
  relationship_type_id bigint not null references public.historical_case_rule_relationship_types(id) on delete restrict,
  relationship_note text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint hcvlr_relationship_note_nonempty
    check (relationship_note is null or btrim(relationship_note) <> ''),
  constraint hcvlr_unique
    unique (historical_case_version_id, rule_code, relationship_type_id)
);

create index if not exists hcvlr_version_idx
  on public.historical_case_version_logical_rules (historical_case_version_id);

create index if not exists hcvlr_rule_code_idx
  on public.historical_case_version_logical_rules (rule_code);

create table if not exists public.historical_case_version_rule_versions (
  id bigint generated by default as identity primary key,
  historical_case_version_id bigint not null references public.historical_case_versions(id) on delete cascade,
  rule_version_id bigint not null references public.rule_catalogue(id) on delete restrict,
  relationship_type_id bigint not null references public.historical_case_rule_relationship_types(id) on delete restrict,
  relationship_note text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint hcvrv_relationship_note_nonempty
    check (relationship_note is null or btrim(relationship_note) <> ''),
  constraint hcvrv_unique
    unique (historical_case_version_id, rule_version_id, relationship_type_id)
);

create index if not exists hcvrv_version_idx
  on public.historical_case_version_rule_versions (historical_case_version_id);

create index if not exists hcvrv_rule_version_idx
  on public.historical_case_version_rule_versions (rule_version_id);

create table if not exists public.historical_case_knowledge_relationship_types (
  id bigint generated by default as identity primary key,
  relationship_code text not null unique,
  display_name text not null,
  description text not null,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint hckrt_code_nonempty
    check (btrim(relationship_code) <> ''),
  constraint hckrt_display_name_nonempty
    check (btrim(display_name) <> ''),
  constraint hckrt_description_nonempty
    check (btrim(description) <> ''),
  constraint hckrt_sort_order_nonnegative
    check (sort_order >= 0)
);

create table if not exists public.historical_case_version_knowledge_documents (
  id bigint generated by default as identity primary key,
  historical_case_version_id bigint not null references public.historical_case_versions(id) on delete cascade,
  knowledge_document_id bigint not null references public.knowledge_documents(id) on delete restrict,
  relationship_type_id bigint not null references public.historical_case_knowledge_relationship_types(id) on delete restrict,
  relationship_note text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint hcvkd_relationship_note_nonempty
    check (relationship_note is null or btrim(relationship_note) <> ''),
  constraint hcvkd_unique
    unique (historical_case_version_id, knowledge_document_id, relationship_type_id)
);

create index if not exists hcvkd_version_idx
  on public.historical_case_version_knowledge_documents (historical_case_version_id);

create index if not exists hcvkd_document_idx
  on public.historical_case_version_knowledge_documents (knowledge_document_id);

create table if not exists public.historical_case_version_knowledge_document_versions (
  id bigint generated by default as identity primary key,
  historical_case_version_id bigint not null references public.historical_case_versions(id) on delete cascade,
  knowledge_document_version_id bigint not null references public.knowledge_document_versions(id) on delete restrict,
  relationship_type_id bigint not null references public.historical_case_knowledge_relationship_types(id) on delete restrict,
  relationship_note text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint hcvkdv_relationship_note_nonempty
    check (relationship_note is null or btrim(relationship_note) <> ''),
  constraint hcvkdv_unique
    unique (historical_case_version_id, knowledge_document_version_id, relationship_type_id)
);

create index if not exists hcvkdv_version_idx
  on public.historical_case_version_knowledge_document_versions (historical_case_version_id);

create index if not exists hcvkdv_doc_version_idx
  on public.historical_case_version_knowledge_document_versions (knowledge_document_version_id);

create or replace function private.enforce_hcv_authority_connectivity_editability()
returns trigger
language plpgsql
as $$
declare
  target_historical_case_version_id bigint := coalesce(new.historical_case_version_id, old.historical_case_version_id);
  target_governance_status text;
begin
  select hcv.governance_status
  into target_governance_status
  from public.historical_case_versions hcv
  where hcv.id = target_historical_case_version_id;

  if target_governance_status is not null and target_governance_status <> 'draft' then
    raise exception 'historical case current-authority connectivity is immutable once the parent case version is no longer draft'
      using errcode = '23514';
  end if;

  return coalesce(new, old);
end;
$$;

create or replace function private.assert_hcv_rule_version_parent_scope_complete(
  p_historical_case_version_id bigint
)
returns void
language plpgsql
as $$
declare
  missing_rule_code text;
  missing_rule_version_id bigint;
begin
  if p_historical_case_version_id is null then
    return;
  end if;

  select rc.rule_code, hcvrv.rule_version_id
  into missing_rule_code, missing_rule_version_id
  from public.historical_case_version_rule_versions hcvrv
  join public.rule_catalogue rc
    on rc.id = hcvrv.rule_version_id
  where hcvrv.historical_case_version_id = p_historical_case_version_id
    and not exists (
      select 1
      from public.historical_case_version_logical_rules hcvlr
      where hcvlr.historical_case_version_id = hcvrv.historical_case_version_id
        and hcvlr.rule_code = rc.rule_code
    )
  limit 1;

  if missing_rule_version_id is not null then
    raise exception 'historical case version % cannot link to exact rule version % because no stable logical-rule relationship exists for rule_code %',
      p_historical_case_version_id,
      missing_rule_version_id,
      missing_rule_code
      using errcode = '23514';
  end if;
end;
$$;

create or replace function private.assert_hcv_doc_version_parent_scope_complete(
  p_historical_case_version_id bigint
)
returns void
language plpgsql
as $$
declare
  missing_document_id bigint;
  missing_document_version_id bigint;
begin
  if p_historical_case_version_id is null then
    return;
  end if;

  select kdv.document_id, hcvkdv.knowledge_document_version_id
  into missing_document_id, missing_document_version_id
  from public.historical_case_version_knowledge_document_versions hcvkdv
  join public.knowledge_document_versions kdv
    on kdv.id = hcvkdv.knowledge_document_version_id
  where hcvkdv.historical_case_version_id = p_historical_case_version_id
    and not exists (
      select 1
      from public.historical_case_version_knowledge_documents hcvkd
      where hcvkd.historical_case_version_id = hcvkdv.historical_case_version_id
        and hcvkd.knowledge_document_id = kdv.document_id
    )
  limit 1;

  if missing_document_version_id is not null then
    raise exception 'historical case version % cannot link to exact knowledge document version % because no stable knowledge document relationship exists for document_id %',
      p_historical_case_version_id,
      missing_document_version_id,
      missing_document_id
      using errcode = '23514';
  end if;
end;
$$;

create or replace function private.enforce_hcv_rule_version_parent_scope()
returns trigger
language plpgsql
as $$
declare
  target_historical_case_version_id bigint := coalesce(new.historical_case_version_id, old.historical_case_version_id);
begin
  perform private.assert_hcv_rule_version_parent_scope_complete(target_historical_case_version_id);
  return null;
end;
$$;

create or replace function private.enforce_hcv_doc_version_parent_scope()
returns trigger
language plpgsql
as $$
declare
  target_historical_case_version_id bigint := coalesce(new.historical_case_version_id, old.historical_case_version_id);
begin
  perform private.assert_hcv_doc_version_parent_scope_complete(target_historical_case_version_id);
  return null;
end;
$$;

create or replace function private.assert_hcv_current_authority_connectivity_valid(
  p_historical_case_version_id bigint,
  p_precedent_availability text,
  p_contains_historical_value_only_content boolean
)
returns void
language plpgsql
as $$
declare
  has_phase_4_relationship boolean;
  has_phase_5_relationship boolean;
  requires_phase_4 boolean;
  requires_phase_5 boolean;
  requires_phase_4_and_5 boolean;
  has_potential_conflict boolean;
  has_current_status_unknown boolean;
begin
  if p_historical_case_version_id is null then
    return;
  end if;

  select exists (
    select 1
    from public.historical_case_version_logical_rules hcvlr
    where hcvlr.historical_case_version_id = p_historical_case_version_id
    union all
    select 1
    from public.historical_case_version_rule_versions hcvrv
    where hcvrv.historical_case_version_id = p_historical_case_version_id
  )
  into has_phase_4_relationship;

  select exists (
    select 1
    from public.historical_case_version_knowledge_documents hcvkd
    where hcvkd.historical_case_version_id = p_historical_case_version_id
    union all
    select 1
    from public.historical_case_version_knowledge_document_versions hcvkdv
    where hcvkdv.historical_case_version_id = p_historical_case_version_id
  )
  into has_phase_5_relationship;

  select exists (
    select 1
    from public.historical_case_version_responsibilities hcvr
    where hcvr.historical_case_version_id = p_historical_case_version_id
      and hcvr.current_authority_disposition = 'check_phase_4'
    union all
    select 1
    from public.historical_case_version_decisions hcvd
    where hcvd.historical_case_version_id = p_historical_case_version_id
      and hcvd.current_authority_disposition = 'check_phase_4'
    union all
    select 1
    from public.historical_case_version_lessons hcvl
    where hcvl.historical_case_version_id = p_historical_case_version_id
      and hcvl.current_authority_disposition = 'check_phase_4'
  )
  into requires_phase_4;

  select exists (
    select 1
    from public.historical_case_version_responsibilities hcvr
    where hcvr.historical_case_version_id = p_historical_case_version_id
      and hcvr.current_authority_disposition = 'check_phase_5'
    union all
    select 1
    from public.historical_case_version_decisions hcvd
    where hcvd.historical_case_version_id = p_historical_case_version_id
      and hcvd.current_authority_disposition = 'check_phase_5'
    union all
    select 1
    from public.historical_case_version_lessons hcvl
    where hcvl.historical_case_version_id = p_historical_case_version_id
      and hcvl.current_authority_disposition = 'check_phase_5'
  )
  into requires_phase_5;

  select exists (
    select 1
    from public.historical_case_version_responsibilities hcvr
    where hcvr.historical_case_version_id = p_historical_case_version_id
      and hcvr.current_authority_disposition = 'check_phase_4_and_5'
    union all
    select 1
    from public.historical_case_version_decisions hcvd
    where hcvd.historical_case_version_id = p_historical_case_version_id
      and hcvd.current_authority_disposition = 'check_phase_4_and_5'
    union all
    select 1
    from public.historical_case_version_lessons hcvl
    where hcvl.historical_case_version_id = p_historical_case_version_id
      and hcvl.current_authority_disposition = 'check_phase_4_and_5'
  )
  into requires_phase_4_and_5;

  select exists (
    select 1
    from public.historical_case_version_responsibilities hcvr
    where hcvr.historical_case_version_id = p_historical_case_version_id
      and hcvr.current_authority_disposition = 'potential_conflict_with_current_knowledge'
    union all
    select 1
    from public.historical_case_version_decisions hcvd
    where hcvd.historical_case_version_id = p_historical_case_version_id
      and hcvd.current_authority_disposition = 'potential_conflict_with_current_knowledge'
    union all
    select 1
    from public.historical_case_version_lessons hcvl
    where hcvl.historical_case_version_id = p_historical_case_version_id
      and hcvl.current_authority_disposition = 'potential_conflict_with_current_knowledge'
  )
  into has_potential_conflict;

  select exists (
    select 1
    from public.historical_case_version_responsibilities hcvr
    where hcvr.historical_case_version_id = p_historical_case_version_id
      and hcvr.current_authority_disposition = 'current_status_unknown'
    union all
    select 1
    from public.historical_case_version_decisions hcvd
    where hcvd.historical_case_version_id = p_historical_case_version_id
      and hcvd.current_authority_disposition = 'current_status_unknown'
    union all
    select 1
    from public.historical_case_version_lessons hcvl
    where hcvl.historical_case_version_id = p_historical_case_version_id
      and hcvl.current_authority_disposition = 'current_status_unknown'
  )
  into has_current_status_unknown;

  if (requires_phase_4 or requires_phase_4_and_5) and not has_phase_4_relationship then
    raise exception 'historical case version % cannot become active because at least one governed statement requires Phase 4 current-authority connectivity',
      p_historical_case_version_id
      using errcode = '23514';
  end if;

  if (requires_phase_5 or requires_phase_4_and_5) and not has_phase_5_relationship then
    raise exception 'historical case version % cannot become active because at least one governed statement requires Phase 5 current-authority connectivity',
      p_historical_case_version_id
      using errcode = '23514';
  end if;

  if has_potential_conflict and not (has_phase_4_relationship or has_phase_5_relationship) then
    raise exception 'historical case version % cannot become active because potential_conflict_with_current_knowledge requires at least one current-authority relationship',
      p_historical_case_version_id
      using errcode = '23514';
  end if;

  if has_potential_conflict and not p_contains_historical_value_only_content then
    raise exception 'historical case version % cannot become active because potential_conflict_with_current_knowledge requires historical-value-only content to remain explicitly marked',
      p_historical_case_version_id
      using errcode = '23514';
  end if;

  if has_current_status_unknown and p_precedent_availability <> 'limited' then
    raise exception 'historical case version % cannot become active with current_status_unknown unless precedent_availability is limited',
      p_historical_case_version_id
      using errcode = '23514';
  end if;
end;
$$;

create or replace function private.enforce_historical_case_version_lifecycle()
returns trigger
language plpgsql
as $$
begin
  if tg_op = 'UPDATE' and new.id is not null then
    new.contains_historical_value_only_content :=
      private.historical_case_version_contains_historical_value_only_content(new.id);
  end if;

  if tg_op = 'UPDATE' then
    if old.governance_status = 'draft' and new.governance_status not in ('draft', 'active', 'retired') then
      raise exception 'draft historical case versions can only remain draft, become active, or be retired'
        using errcode = '23514';
    end if;

    if old.governance_status = 'active' and new.governance_status not in ('active', 'superseded', 'retired') then
      raise exception 'active historical case versions can only remain active, become superseded, or be retired'
        using errcode = '23514';
    end if;

    if old.governance_status = 'superseded' and new.governance_status not in ('superseded', 'retired') then
      raise exception 'superseded historical case versions cannot become draft or active again'
        using errcode = '23514';
    end if;

    if old.governance_status = 'retired' and new.governance_status <> 'retired' then
      raise exception 'retired historical case versions are immutable lifecycle endpoints'
        using errcode = '23514';
    end if;

    if old.governance_status <> 'draft' and (
      old.historical_case_id is distinct from new.historical_case_id
      or old.version_number is distinct from new.version_number
      or old.precedent_availability is distinct from new.precedent_availability
      or old.precedent_type is distinct from new.precedent_type
      or old.evidence_strength is distinct from new.evidence_strength
      or old.historical_event_status is distinct from new.historical_event_status
      or old.temporal_precision is distinct from new.temporal_precision
      or old.event_date_start is distinct from new.event_date_start
      or old.event_date_end is distinct from new.event_date_end
      or old.temporal_note is distinct from new.temporal_note
      or old.curated_narrative is distinct from new.curated_narrative
      or old.confidentiality_level_id is distinct from new.confidentiality_level_id
      or old.personal_information_status is distinct from new.personal_information_status
      or old.personal_information_notes is distinct from new.personal_information_notes
      or old.contains_historical_value_only_content is distinct from new.contains_historical_value_only_content
      or old.supersedes_version_id is distinct from new.supersedes_version_id
    ) then
      raise exception 'non-draft historical case versions cannot be materially rewritten; create a superseding version instead'
        using errcode = '23514';
    end if;
  end if;

  if new.governance_status = 'draft' and new.activated_at is not null then
    raise exception 'draft historical case versions cannot record activated_at'
      using errcode = '23514';
  end if;

  if new.governance_status = 'active' and new.activated_at is null then
    new.activated_at := timezone('utc', now());
  end if;

  if new.governance_status = 'active' then
    perform private.assert_historical_case_version_statement_provenance_complete(new.id);
    perform private.assert_hcv_current_authority_connectivity_valid(
      new.id,
      new.precedent_availability,
      new.contains_historical_value_only_content
    );
  end if;

  if new.governance_status = 'superseded' and new.activated_at is null then
    raise exception 'superseded historical case versions must retain an activated_at timestamp'
      using errcode = '23514';
  end if;

  return new;
end;
$$;

drop trigger if exists trg_historical_case_rule_relationship_types_touch_updated_at on public.historical_case_rule_relationship_types;
create trigger trg_historical_case_rule_relationship_types_touch_updated_at
before update on public.historical_case_rule_relationship_types
for each row
execute function private.touch_updated_at();

drop trigger if exists trg_hckrt_touch_updated_at on public.historical_case_knowledge_relationship_types;
create trigger trg_hckrt_touch_updated_at
before update on public.historical_case_knowledge_relationship_types
for each row
execute function private.touch_updated_at();

drop trigger if exists trg_historical_case_version_logical_rules_touch_updated_at on public.historical_case_version_logical_rules;
create trigger trg_historical_case_version_logical_rules_touch_updated_at
before update on public.historical_case_version_logical_rules
for each row
execute function private.touch_updated_at();

drop trigger if exists trg_historical_case_version_rule_versions_touch_updated_at on public.historical_case_version_rule_versions;
create trigger trg_historical_case_version_rule_versions_touch_updated_at
before update on public.historical_case_version_rule_versions
for each row
execute function private.touch_updated_at();

drop trigger if exists trg_hcvkd_touch_updated_at on public.historical_case_version_knowledge_documents;
create trigger trg_hcvkd_touch_updated_at
before update on public.historical_case_version_knowledge_documents
for each row
execute function private.touch_updated_at();

drop trigger if exists trg_hcvkdv_touch_updated_at on public.historical_case_version_knowledge_document_versions;
create trigger trg_hcvkdv_touch_updated_at
before update on public.historical_case_version_knowledge_document_versions
for each row
execute function private.touch_updated_at();

drop trigger if exists trg_hcv_logical_rules_editability on public.historical_case_version_logical_rules;
create trigger trg_hcv_logical_rules_editability
before insert or update or delete on public.historical_case_version_logical_rules
for each row
execute function private.enforce_hcv_authority_connectivity_editability();

drop trigger if exists trg_hcv_rule_versions_editability on public.historical_case_version_rule_versions;
create trigger trg_hcv_rule_versions_editability
before insert or update or delete on public.historical_case_version_rule_versions
for each row
execute function private.enforce_hcv_authority_connectivity_editability();

drop trigger if exists trg_hcv_knowledge_documents_editability on public.historical_case_version_knowledge_documents;
create trigger trg_hcv_knowledge_documents_editability
before insert or update or delete on public.historical_case_version_knowledge_documents
for each row
execute function private.enforce_hcv_authority_connectivity_editability();

drop trigger if exists trg_hcv_knowledge_document_versions_editability on public.historical_case_version_knowledge_document_versions;
create trigger trg_hcv_knowledge_document_versions_editability
before insert or update or delete on public.historical_case_version_knowledge_document_versions
for each row
execute function private.enforce_hcv_authority_connectivity_editability();

drop trigger if exists trg_hcv_rule_versions_parent_scope_logical_rules on public.historical_case_version_logical_rules;
create constraint trigger trg_hcv_rule_versions_parent_scope_logical_rules
after insert or update or delete on public.historical_case_version_logical_rules
deferrable initially deferred
for each row
execute function private.enforce_hcv_rule_version_parent_scope();

drop trigger if exists trg_hcv_rule_versions_parent_scope_exact on public.historical_case_version_rule_versions;
create constraint trigger trg_hcv_rule_versions_parent_scope_exact
after insert or update or delete on public.historical_case_version_rule_versions
deferrable initially deferred
for each row
execute function private.enforce_hcv_rule_version_parent_scope();

drop trigger if exists trg_hcv_doc_versions_parent_scope_docs on public.historical_case_version_knowledge_documents;
create constraint trigger trg_hcv_doc_versions_parent_scope_docs
after insert or update or delete on public.historical_case_version_knowledge_documents
deferrable initially deferred
for each row
execute function private.enforce_hcv_doc_version_parent_scope();

drop trigger if exists trg_hcv_doc_versions_parent_scope_exact on public.historical_case_version_knowledge_document_versions;
create constraint trigger trg_hcv_doc_versions_parent_scope_exact
after insert or update or delete on public.historical_case_version_knowledge_document_versions
deferrable initially deferred
for each row
execute function private.enforce_hcv_doc_version_parent_scope();

insert into public.historical_case_rule_relationship_types (
  relationship_code,
  display_name,
  description,
  sort_order
)
values
  (
    'relevant_to',
    'Relevant To',
    'The historical case version is materially relevant to the referenced current deterministic rule concept without defining or governing it.',
    10
  ),
  (
    'illustrates',
    'Illustrates',
    'The historical case version illustrates how the referenced current deterministic rule concept may arise in practice without becoming authoritative truth.',
    20
  ),
  (
    'historical_precedent_for',
    'Historical Precedent For',
    'The historical case version serves as non-authoritative historical precedent for the referenced current deterministic rule concept.',
    30
  ),
  (
    'encountered_issue_related_to',
    'Encountered Issue Related To',
    'The historical case version encountered an issue materially related to the referenced current deterministic rule concept.',
    40
  )
on conflict (relationship_code) do update
set display_name = excluded.display_name,
    description = excluded.description,
    sort_order = excluded.sort_order,
    is_active = true;

insert into public.historical_case_knowledge_relationship_types (
  relationship_code,
  display_name,
  description,
  sort_order
)
values
  (
    'current_guidance_to_consult',
    'Current Guidance To Consult',
    'The referenced governed knowledge document should be consulted when interpreting the historical case version today.',
    10
  ),
  (
    'current_context_relevant_to_case',
    'Current Context Relevant To Case',
    'The referenced governed knowledge document provides current context materially relevant to interpreting the historical case version.',
    20
  ),
  (
    'current_authority_supersedes_historical_practice',
    'Current Authority Supersedes Historical Practice',
    'The referenced governed knowledge document reflects current authority that supersedes the historical practice preserved in the case version.',
    30
  ),
  (
    'current_document_for_interpretation',
    'Current Document For Interpretation',
    'The referenced governed knowledge document provides the current document surface that later consumers should use for interpretation.',
    40
  )
on conflict (relationship_code) do update
set display_name = excluded.display_name,
    description = excluded.description,
    sort_order = excluded.sort_order,
    is_active = true;

alter table public.historical_case_rule_relationship_types enable row level security;
alter table public.historical_case_version_logical_rules enable row level security;
alter table public.historical_case_version_rule_versions enable row level security;
alter table public.historical_case_knowledge_relationship_types enable row level security;
alter table public.historical_case_version_knowledge_documents enable row level security;
alter table public.historical_case_version_knowledge_document_versions enable row level security;

revoke all on table public.historical_case_rule_relationship_types from public, anon, authenticated, service_role;
revoke all on table public.historical_case_version_logical_rules from public, anon, authenticated, service_role;
revoke all on table public.historical_case_version_rule_versions from public, anon, authenticated, service_role;
revoke all on table public.historical_case_knowledge_relationship_types from public, anon, authenticated, service_role;
revoke all on table public.historical_case_version_knowledge_documents from public, anon, authenticated, service_role;
revoke all on table public.historical_case_version_knowledge_document_versions from public, anon, authenticated, service_role;
