create table if not exists private.knowledge_chunk_logical_rules (
  id bigint generated by default as identity primary key,
  chunk_id bigint not null references private.knowledge_chunks(id) on delete cascade,
  rule_code text not null references public.logical_rules(rule_code) on delete restrict,
  relationship_type_id bigint not null references public.knowledge_rule_relationship_types(id) on delete restrict,
  notes text,
  created_at timestamptz not null default timezone('utc', now()),
  constraint knowledge_chunk_logical_rules_notes_nonempty
    check (notes is null or btrim(notes) <> ''),
  constraint knowledge_chunk_logical_rules_unique
    unique (chunk_id, rule_code, relationship_type_id)
);

create index if not exists knowledge_chunk_logical_rules_chunk_idx
  on private.knowledge_chunk_logical_rules (chunk_id);

create index if not exists knowledge_chunk_logical_rules_rule_idx
  on private.knowledge_chunk_logical_rules (rule_code);

create table if not exists private.knowledge_chunk_rule_versions (
  id bigint generated by default as identity primary key,
  chunk_id bigint not null references private.knowledge_chunks(id) on delete cascade,
  rule_version_id bigint not null references public.rule_catalogue(id) on delete restrict,
  relationship_type_id bigint not null references public.knowledge_rule_relationship_types(id) on delete restrict,
  notes text,
  created_at timestamptz not null default timezone('utc', now()),
  constraint knowledge_chunk_rule_versions_notes_nonempty
    check (notes is null or btrim(notes) <> ''),
  constraint knowledge_chunk_rule_versions_unique
    unique (chunk_id, rule_version_id, relationship_type_id)
);

create index if not exists knowledge_chunk_rule_versions_chunk_idx
  on private.knowledge_chunk_rule_versions (chunk_id);

create index if not exists knowledge_chunk_rule_versions_rule_version_idx
  on private.knowledge_chunk_rule_versions (rule_version_id);

create or replace function private.validate_knowledge_chunk_logical_rule_parent_scope()
returns trigger
language plpgsql
as $$
declare
  parent_document_version_id bigint;
  has_parent_rule boolean;
begin
  select kcs.document_version_id
  into parent_document_version_id
  from private.knowledge_chunks kc
  join private.knowledge_chunk_sets kcs
    on kcs.id = kc.chunk_set_id
  where kc.id = new.chunk_id;

  if parent_document_version_id is null then
    return new;
  end if;

  select exists (
    select 1
    from public.knowledge_document_version_logical_rules kdvlr
    where kdvlr.document_version_id = parent_document_version_id
      and kdvlr.rule_code = new.rule_code
  )
  into has_parent_rule;

  if not has_parent_rule then
    raise exception 'chunk % cannot link to logical rule % because parent document version % has no document-level relationship to that rule',
      new.chunk_id,
      new.rule_code,
      parent_document_version_id
      using errcode = '23514';
  end if;

  return new;
end;
$$;

create or replace function private.validate_knowledge_chunk_rule_version_parent_scope()
returns trigger
language plpgsql
as $$
declare
  parent_document_version_id bigint;
  has_parent_rule_version boolean;
begin
  select kcs.document_version_id
  into parent_document_version_id
  from private.knowledge_chunks kc
  join private.knowledge_chunk_sets kcs
    on kcs.id = kc.chunk_set_id
  where kc.id = new.chunk_id;

  if parent_document_version_id is null then
    return new;
  end if;

  select exists (
    select 1
    from public.knowledge_document_version_rule_versions kdvrv
    where kdvrv.document_version_id = parent_document_version_id
      and kdvrv.rule_version_id = new.rule_version_id
  )
  into has_parent_rule_version;

  if not has_parent_rule_version then
    raise exception 'chunk % cannot link to exact rule version % because parent document version % has no exact document-level relationship to that rule version',
      new.chunk_id,
      new.rule_version_id,
      parent_document_version_id
      using errcode = '23514';
  end if;

  return new;
end;
$$;

drop trigger if exists trg_kclr_validate_target_kind on private.knowledge_chunk_logical_rules;
create trigger trg_kclr_validate_target_kind
before insert or update of relationship_type_id on private.knowledge_chunk_logical_rules
for each row
execute function private.validate_knowledge_rule_relationship_target_kind('logical_rule');

drop trigger if exists trg_kcrv_validate_target_kind on private.knowledge_chunk_rule_versions;
create trigger trg_kcrv_validate_target_kind
before insert or update of relationship_type_id on private.knowledge_chunk_rule_versions
for each row
execute function private.validate_knowledge_rule_relationship_target_kind('rule_version');

drop trigger if exists trg_kclr_validate_parent_scope on private.knowledge_chunk_logical_rules;
create trigger trg_kclr_validate_parent_scope
before insert or update of chunk_id, rule_code on private.knowledge_chunk_logical_rules
for each row
execute function private.validate_knowledge_chunk_logical_rule_parent_scope();

drop trigger if exists trg_kcrv_validate_parent_scope on private.knowledge_chunk_rule_versions;
create trigger trg_kcrv_validate_parent_scope
before insert or update of chunk_id, rule_version_id on private.knowledge_chunk_rule_versions
for each row
execute function private.validate_knowledge_chunk_rule_version_parent_scope();

alter table private.knowledge_chunk_logical_rules enable row level security;
alter table private.knowledge_chunk_rule_versions enable row level security;

revoke all on table private.knowledge_chunk_logical_rules from public, anon, authenticated, service_role;
revoke all on table private.knowledge_chunk_rule_versions from public, anon, authenticated, service_role;
