create extension if not exists vector with schema extensions;

create table if not exists private.knowledge_embedding_models (
  id bigint generated by default as identity primary key,
  provider_code text not null,
  model_code text not null,
  model_version text,
  embedding_dimensions integer not null,
  config_fingerprint text not null,
  configuration_json jsonb not null default '{}'::jsonb,
  is_retrieval_approved boolean not null default false,
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint knowledge_embedding_models_provider_code_nonempty
    check (btrim(provider_code) <> ''),
  constraint knowledge_embedding_models_model_code_nonempty
    check (btrim(model_code) <> ''),
  constraint knowledge_embedding_models_model_version_nonempty
    check (model_version is null or btrim(model_version) <> ''),
  constraint knowledge_embedding_models_embedding_dimensions_positive
    check (embedding_dimensions > 0),
  constraint knowledge_embedding_models_config_fingerprint_nonempty
    check (btrim(config_fingerprint) <> ''),
  constraint knowledge_embedding_models_configuration_json_object
    check (jsonb_typeof(configuration_json) = 'object')
);

create unique index if not exists knowledge_embedding_models_registry_identity_idx
  on private.knowledge_embedding_models (
    provider_code,
    model_code,
    coalesce(model_version, ''),
    config_fingerprint
  );

create unique index if not exists knowledge_embedding_models_one_active_retrieval_model_idx
  on private.knowledge_embedding_models ((1))
  where is_retrieval_approved
    and is_active;

create table if not exists private.knowledge_embeddings (
  id bigint generated by default as identity primary key,
  chunk_id bigint not null references private.knowledge_chunks(id) on delete cascade,
  embedding_model_id bigint not null references private.knowledge_embedding_models(id) on delete restrict,
  input_content_hash text not null,
  generated_at timestamptz not null,
  embedding extensions.vector not null,
  created_at timestamptz not null default timezone('utc', now()),
  constraint knowledge_embeddings_input_content_hash_nonempty
    check (btrim(input_content_hash) <> ''),
  constraint knowledge_embeddings_unique_chunk_model_input
    unique (chunk_id, embedding_model_id, input_content_hash)
);

create index if not exists knowledge_embeddings_model_chunk_lookup_idx
  on private.knowledge_embeddings (embedding_model_id, chunk_id, input_content_hash);

create or replace function private.build_knowledge_chunk_embedding_input(
  p_document_title text,
  p_heading_path text,
  p_section_heading text,
  p_question_label text,
  p_body_text text
)
returns text
language sql
immutable
as $$
select concat_ws(
  E'\n\n',
  concat('Document: ', coalesce(p_document_title, '')),
  case
    when coalesce(nullif(btrim(p_heading_path), ''), nullif(btrim(p_section_heading), '')) is not null then
      concat('Section: ', coalesce(nullif(btrim(p_heading_path), ''), nullif(btrim(p_section_heading), '')))
    else null
  end,
  case
    when nullif(btrim(p_question_label), '') is not null then
      concat('Question: ', nullif(btrim(p_question_label), ''))
    else null
  end,
  coalesce(p_body_text, '')
);
$$;

create or replace function private.build_knowledge_chunk_embedding_input_hash(
  p_document_title text,
  p_heading_path text,
  p_section_heading text,
  p_question_label text,
  p_body_text text
)
returns text
language sql
immutable
as $$
select md5(
  private.build_knowledge_chunk_embedding_input(
    p_document_title,
    p_heading_path,
    p_section_heading,
    p_question_label,
    p_body_text
  )
);
$$;

create or replace view private.current_knowledge_chunk_embedding_inputs as
select
  ckc.chunk_id,
  ckc.chunk_set_id,
  ckc.document_version_id,
  ckc.document_version_number,
  ckc.document_code,
  ckc.document_title,
  ckc.primary_category_code,
  ckc.chunk_ordinal,
  ckc.section_heading,
  ckc.heading_path,
  ckc.question_label,
  ckc.document_title_snapshot,
  ckc.body_text,
  ckc.content_hash,
  ckc.token_count,
  ckc.primary_chunk_source_id,
  ckc.primary_document_version_source_object_id,
  ckc.primary_source_locator,
  ckc.chunk_source_count,
  ckc.rental_type_codes,
  private.build_knowledge_chunk_embedding_input(
    ckc.document_title_snapshot,
    ckc.heading_path,
    ckc.section_heading,
    ckc.question_label,
    ckc.body_text
  ) as embedding_input_text,
  private.build_knowledge_chunk_embedding_input_hash(
    ckc.document_title_snapshot,
    ckc.heading_path,
    ckc.section_heading,
    ckc.question_label,
    ckc.body_text
  ) as embedding_input_hash
from private.current_knowledge_chunks ckc;

create or replace function private.validate_knowledge_embedding()
returns trigger
language plpgsql
as $$
declare
  expected_dimensions integer;
  actual_dimensions integer;
begin
  select kem.embedding_dimensions
  into expected_dimensions
  from private.knowledge_embedding_models kem
  where kem.id = new.embedding_model_id;

  if expected_dimensions is null then
    return new;
  end if;

  actual_dimensions := extensions.vector_dims(new.embedding);

  if actual_dimensions <> expected_dimensions then
    raise exception 'embedding dimensions % do not match model % dimensions %',
      actual_dimensions,
      new.embedding_model_id,
      expected_dimensions
      using errcode = '23514';
  end if;

  return new;
end;
$$;

create or replace function private.search_knowledge_chunks_semantic(
  p_query_embedding extensions.vector,
  p_result_limit integer default 10,
  p_embedding_model_id bigint default null,
  p_document_code text default null,
  p_category_code text default null,
  p_rental_type_code text default null
)
returns table (
  chunk_id bigint,
  document_code text,
  document_title text,
  document_version_id bigint,
  document_version_number integer,
  chunk_set_id bigint,
  chunk_ordinal integer,
  section_heading text,
  heading_path text,
  question_label text,
  body_text text,
  similarity_score double precision,
  cosine_distance double precision,
  content_hash text,
  input_content_hash text,
  embedding_model_id bigint,
  provider_code text,
  model_code text,
  model_version text,
  primary_chunk_source_id bigint,
  primary_document_version_source_object_id bigint,
  primary_source_locator text,
  primary_category_code text,
  rental_type_codes text[]
)
language plpgsql
stable
security invoker
set search_path = pg_catalog, private, public, extensions
as $$
declare
  resolved_embedding_model_id bigint;
  resolved_embedding_dimensions integer;
  approved_model_count integer;
  actual_query_dimensions integer;
  bounded_limit integer;
begin
  if p_query_embedding is null then
    raise exception 'query embedding is required'
      using errcode = '22004';
  end if;

  bounded_limit := least(greatest(coalesce(p_result_limit, 10), 1), 50);

  if p_embedding_model_id is null then
    select count(*)
    into approved_model_count
    from private.knowledge_embedding_models kem
    where kem.is_retrieval_approved
      and kem.is_active;

    if approved_model_count = 0 then
      raise exception 'no active retrieval-approved embedding model is registered'
        using errcode = 'P0001';
    end if;

    if approved_model_count > 1 then
      raise exception 'multiple active retrieval-approved embedding models are registered'
        using errcode = 'P0001';
    end if;

    select
      kem.id,
      kem.embedding_dimensions
    into resolved_embedding_model_id, resolved_embedding_dimensions
    from private.knowledge_embedding_models kem
    where kem.is_retrieval_approved
      and kem.is_active;
  else
    select
      kem.id,
      kem.embedding_dimensions
    into resolved_embedding_model_id, resolved_embedding_dimensions
    from private.knowledge_embedding_models kem
    where kem.id = p_embedding_model_id
      and kem.is_active;

    if resolved_embedding_model_id is null then
      raise exception 'embedding model % is not an active registered model',
        p_embedding_model_id
        using errcode = '23503';
    end if;
  end if;

  actual_query_dimensions := vector_dims(p_query_embedding);

  if actual_query_dimensions <> resolved_embedding_dimensions then
    raise exception 'query embedding dimensions % do not match model % dimensions %',
      actual_query_dimensions,
      resolved_embedding_model_id,
      resolved_embedding_dimensions
      using errcode = '23514';
  end if;

  return query
  with scored as (
    select
      ckei.chunk_id,
      ckei.document_code,
      ckei.document_title,
      ckei.document_version_id,
      ckei.document_version_number,
      ckei.chunk_set_id,
      ckei.chunk_ordinal,
      ckei.section_heading,
      ckei.heading_path,
      ckei.question_label,
      ckei.body_text,
      1 - (ke.embedding <=> p_query_embedding) as similarity_score,
      ke.embedding <=> p_query_embedding as cosine_distance,
      ckei.content_hash,
      ke.input_content_hash,
      kem.id as embedding_model_id,
      kem.provider_code,
      kem.model_code,
      kem.model_version,
      ckei.primary_chunk_source_id,
      ckei.primary_document_version_source_object_id,
      ckei.primary_source_locator,
      ckei.primary_category_code,
      ckei.rental_type_codes
    from private.current_knowledge_chunk_embedding_inputs ckei
    join private.knowledge_embeddings ke
      on ke.chunk_id = ckei.chunk_id
     and ke.embedding_model_id = resolved_embedding_model_id
     and ke.input_content_hash = ckei.embedding_input_hash
    join private.knowledge_embedding_models kem
      on kem.id = ke.embedding_model_id
    where (p_document_code is null or ckei.document_code = p_document_code)
      and (p_category_code is null or ckei.primary_category_code = p_category_code)
      and (
        p_rental_type_code is null
        or p_rental_type_code = any(coalesce(ckei.rental_type_codes, array[]::text[]))
      )
  )
  select
    scored.chunk_id,
    scored.document_code,
    scored.document_title,
    scored.document_version_id,
    scored.document_version_number,
    scored.chunk_set_id,
    scored.chunk_ordinal,
    scored.section_heading,
    scored.heading_path,
    scored.question_label,
    scored.body_text,
    scored.similarity_score,
    scored.cosine_distance,
    scored.content_hash,
    scored.input_content_hash,
    scored.embedding_model_id,
    scored.provider_code,
    scored.model_code,
    scored.model_version,
    scored.primary_chunk_source_id,
    scored.primary_document_version_source_object_id,
    scored.primary_source_locator,
    scored.primary_category_code,
    scored.rental_type_codes
  from scored
  order by scored.cosine_distance asc, scored.document_code, scored.chunk_ordinal
  limit bounded_limit;
end;
$$;

drop trigger if exists trg_knowledge_embedding_models_touch_updated_at on private.knowledge_embedding_models;
create trigger trg_knowledge_embedding_models_touch_updated_at
before update on private.knowledge_embedding_models
for each row
execute function private.touch_updated_at();

drop trigger if exists trg_knowledge_embeddings_validate_embedding on private.knowledge_embeddings;
create trigger trg_knowledge_embeddings_validate_embedding
before insert or update of embedding_model_id, embedding on private.knowledge_embeddings
for each row
execute function private.validate_knowledge_embedding();

alter table private.knowledge_embedding_models enable row level security;
alter table private.knowledge_embeddings enable row level security;

revoke all on table private.knowledge_embedding_models from public, anon, authenticated, service_role;
revoke all on table private.knowledge_embeddings from public, anon, authenticated, service_role;
revoke all on table private.current_knowledge_chunk_embedding_inputs from public, anon, authenticated, service_role;
revoke execute on function private.build_knowledge_chunk_embedding_input(text, text, text, text, text)
  from public, anon, authenticated, service_role;
revoke execute on function private.build_knowledge_chunk_embedding_input_hash(text, text, text, text, text)
  from public, anon, authenticated, service_role;
revoke execute on function private.search_knowledge_chunks_semantic(extensions.vector, integer, bigint, text, text, text)
  from public, anon, authenticated, service_role;
