create extension if not exists pgcrypto with schema extensions;

create or replace function private.workflow_text_array_values_nonempty(p_values text[])
returns boolean
language sql
immutable
as $$
  select coalesce(
    (
      select bool_and(value is not null and btrim(value) <> '')
      from unnest(coalesce(p_values, '{}'::text[])) as value
    ),
    true
  );
$$;

create or replace function private.workflow_text_array_values_allowed(p_values text[], p_allowed text[])
returns boolean
language sql
immutable
as $$
  select coalesce(
    (
      select bool_and(
        value is not null
        and btrim(value) <> ''
        and value = any(coalesce(p_allowed, '{}'::text[]))
      )
      from unnest(coalesce(p_values, '{}'::text[])) as value
    ),
    true
  );
$$;

create or replace function private.workflow_append_only_guard()
returns trigger
language plpgsql
as $$
begin
  raise exception '% is append-only; % is not allowed', tg_table_name, lower(tg_op)
    using errcode = '23514';
end;
$$;

create table if not exists public.rental_cases (
  id bigint generated by default as identity primary key,
  rental_case_uuid uuid not null default extensions.gen_random_uuid(),
  case_reference_code text not null,
  lifecycle_state text not null,
  case_revision integer not null default 0,
  active_event_start timestamptz,
  active_event_end timestamptz,
  rental_type_code text not null references public.rental_types(rental_type_code) on delete restrict,
  service_level_or_type text,
  client_account_ref text,
  primary_contact_ref text,
  commercial_summary_status text not null default 'unknown',
  operational_summary_status text not null default 'unknown',
  dormant_origin_state text,
  resume_target_state text,
  dormant_reason_code text,
  dormant_review_at timestamptz,
  current_proposal_artifact_id bigint,
  current_agreement_artifact_id bigint,
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint rental_cases_uuid_unique unique (rental_case_uuid),
  constraint rental_cases_case_reference_code_unique unique (case_reference_code),
  constraint rental_cases_case_reference_code_nonempty
    check (btrim(case_reference_code) <> ''),
  constraint rental_cases_case_reference_code_format_check
    check (case_reference_code ~ '^RC-[0-9]{3,}$'),
  constraint rental_cases_lifecycle_state_check
    check (
      lifecycle_state in (
        'inquiry_active',
        'proposal_in_progress',
        'proposal_pending_client',
        'confirmation_pending',
        'confirmed_pre_event',
        'event_ready',
        'event_in_progress',
        'close_out_in_progress',
        'dormant',
        'closed',
        'closed_lost',
        'cancelled'
      )
    ),
  constraint rental_cases_case_revision_nonnegative
    check (case_revision >= 0),
  constraint rental_cases_active_event_date_range_check
    check (active_event_end is null or active_event_start is null or active_event_end >= active_event_start),
  constraint rental_cases_service_level_or_type_nonempty
    check (service_level_or_type is null or btrim(service_level_or_type) <> ''),
  constraint rental_cases_client_account_ref_nonempty
    check (client_account_ref is null or btrim(client_account_ref) <> ''),
  constraint rental_cases_primary_contact_ref_nonempty
    check (primary_contact_ref is null or btrim(primary_contact_ref) <> ''),
  constraint rental_cases_commercial_summary_status_nonempty
    check (btrim(commercial_summary_status) <> ''),
  constraint rental_cases_operational_summary_status_nonempty
    check (btrim(operational_summary_status) <> ''),
  constraint rental_cases_dormant_origin_state_check
    check (
      dormant_origin_state is null or dormant_origin_state in (
        'inquiry_active',
        'proposal_in_progress',
        'proposal_pending_client',
        'confirmation_pending',
        'confirmed_pre_event',
        'event_ready',
        'event_in_progress',
        'close_out_in_progress',
        'dormant',
        'closed',
        'closed_lost',
        'cancelled'
      )
    ),
  constraint rental_cases_resume_target_state_check
    check (
      resume_target_state is null or resume_target_state in (
        'inquiry_active',
        'proposal_in_progress',
        'proposal_pending_client',
        'confirmation_pending',
        'confirmed_pre_event',
        'event_ready',
        'event_in_progress',
        'close_out_in_progress',
        'dormant',
        'closed',
        'closed_lost',
        'cancelled'
      )
    ),
  constraint rental_cases_dormant_reason_code_nonempty
    check (dormant_reason_code is null or btrim(dormant_reason_code) <> '')
);

create index if not exists rental_cases_active_lifecycle_state_idx
  on public.rental_cases (lifecycle_state, case_reference_code)
  where is_active;

create index if not exists rental_cases_active_event_start_idx
  on public.rental_cases (active_event_start)
  where active_event_start is not null;

create table if not exists public.workflow_events (
  id bigint generated by default as identity primary key,
  workflow_event_uuid uuid not null default extensions.gen_random_uuid(),
  rental_case_id bigint not null references public.rental_cases(id) on delete restrict,
  event_type_code text not null,
  source_type text not null,
  source_reference text,
  actor_type text,
  actor_reference text,
  occurred_at timestamptz not null,
  recorded_at timestamptz not null default timezone('utc', now()),
  structured_payload jsonb not null default '{}'::jsonb,
  event_identity_key text,
  origin_metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  constraint workflow_events_uuid_unique unique (workflow_event_uuid),
  constraint workflow_events_case_and_identity_unique unique (rental_case_id, event_identity_key),
  constraint workflow_events_case_event_type_nonempty check (btrim(event_type_code) <> ''),
  constraint workflow_events_source_type_nonempty check (btrim(source_type) <> ''),
  constraint workflow_events_source_reference_nonempty
    check (source_reference is null or btrim(source_reference) <> ''),
  constraint workflow_events_actor_type_nonempty
    check (actor_type is null or btrim(actor_type) <> ''),
  constraint workflow_events_actor_reference_nonempty
    check (actor_reference is null or btrim(actor_reference) <> ''),
  constraint workflow_events_recorded_after_occurred_check
    check (recorded_at >= occurred_at),
  constraint workflow_events_structured_payload_object_check
    check (jsonb_typeof(structured_payload) = 'object'),
  constraint workflow_events_event_identity_key_nonempty
    check (event_identity_key is null or btrim(event_identity_key) <> ''),
  constraint workflow_events_origin_metadata_object_check
    check (jsonb_typeof(origin_metadata) = 'object'),
  constraint workflow_events_case_id_unique unique (id, rental_case_id)
);

create index if not exists workflow_events_case_occurred_at_idx
  on public.workflow_events (rental_case_id, occurred_at desc);

create table if not exists public.rental_case_lifecycle_transitions (
  id bigint generated by default as identity primary key,
  rental_case_lifecycle_transition_uuid uuid not null default extensions.gen_random_uuid(),
  rental_case_id bigint not null references public.rental_cases(id) on delete restrict,
  from_lifecycle_state text,
  to_lifecycle_state text not null,
  triggering_event_id bigint,
  source_type text,
  source_reference text,
  actor_type text,
  actor_reference text,
  transition_reason_code text not null,
  override_applied boolean not null default false,
  case_revision_before integer not null,
  case_revision_after integer not null,
  occurred_at timestamptz not null default timezone('utc', now()),
  created_at timestamptz not null default timezone('utc', now()),
  constraint rental_case_lifecycle_transitions_uuid_unique unique (rental_case_lifecycle_transition_uuid),
  constraint rental_case_lifecycle_transitions_from_state_check
    check (
      from_lifecycle_state is null or from_lifecycle_state in (
        'inquiry_active',
        'proposal_in_progress',
        'proposal_pending_client',
        'confirmation_pending',
        'confirmed_pre_event',
        'event_ready',
        'event_in_progress',
        'close_out_in_progress',
        'dormant',
        'closed',
        'closed_lost',
        'cancelled'
      )
    ),
  constraint rental_case_lifecycle_transitions_to_state_check
    check (
      to_lifecycle_state in (
        'inquiry_active',
        'proposal_in_progress',
        'proposal_pending_client',
        'confirmation_pending',
        'confirmed_pre_event',
        'event_ready',
        'event_in_progress',
        'close_out_in_progress',
        'dormant',
        'closed',
        'closed_lost',
        'cancelled'
      )
    ),
  constraint rental_case_lifecycle_transitions_source_type_nonempty
    check (source_type is null or btrim(source_type) <> ''),
  constraint rental_case_lifecycle_transitions_source_reference_nonempty
    check (source_reference is null or btrim(source_reference) <> ''),
  constraint rental_case_lifecycle_transitions_actor_type_nonempty
    check (actor_type is null or btrim(actor_type) <> ''),
  constraint rental_case_lifecycle_transitions_actor_reference_nonempty
    check (actor_reference is null or btrim(actor_reference) <> ''),
  constraint rental_case_lifecycle_transitions_reason_code_nonempty
    check (btrim(transition_reason_code) <> ''),
  constraint rental_case_lifecycle_transitions_case_revision_before_nonnegative
    check (case_revision_before >= 0),
  constraint rental_case_lifecycle_transitions_case_revision_after_nonnegative
    check (case_revision_after >= 0),
  constraint rental_case_lifecycle_transitions_case_revision_order_check
    check (case_revision_after >= case_revision_before),
  constraint rental_case_lifecycle_transitions_case_id_unique unique (id, rental_case_id),
  constraint rental_case_lifecycle_transitions_triggering_event_fkey
    foreign key (triggering_event_id, rental_case_id)
    references public.workflow_events(id, rental_case_id)
    on delete restrict
);

create index if not exists rental_case_lifecycle_transitions_case_occurred_at_idx
  on public.rental_case_lifecycle_transitions (rental_case_id, occurred_at desc);

create table if not exists public.rental_case_decisions (
  id bigint generated by default as identity primary key,
  rental_case_decision_uuid uuid not null default extensions.gen_random_uuid(),
  rental_case_id bigint not null references public.rental_cases(id) on delete restrict,
  decision_type text not null,
  domain_code text not null,
  baseline_reference text not null,
  proposed_value_payload jsonb not null,
  effective_value_payload jsonb,
  scope_key text not null,
  scope_description text not null,
  evidence_reference text,
  authority_basis text not null,
  approval_posture text not null,
  approval_request_id bigint,
  status text not null,
  effective_at timestamptz,
  supersedes_case_decision_id bigint,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint rental_case_decisions_uuid_unique unique (rental_case_decision_uuid),
  constraint rental_case_decisions_case_id_unique unique (id, rental_case_id),
  constraint rental_case_decisions_decision_type_nonempty check (btrim(decision_type) <> ''),
  constraint rental_case_decisions_domain_code_nonempty check (btrim(domain_code) <> ''),
  constraint rental_case_decisions_baseline_reference_nonempty check (btrim(baseline_reference) <> ''),
  constraint rental_case_decisions_scope_key_nonempty check (btrim(scope_key) <> ''),
  constraint rental_case_decisions_scope_description_nonempty check (btrim(scope_description) <> ''),
  constraint rental_case_decisions_evidence_reference_nonempty
    check (evidence_reference is null or btrim(evidence_reference) <> ''),
  constraint rental_case_decisions_authority_basis_nonempty check (btrim(authority_basis) <> ''),
  constraint rental_case_decisions_approval_posture_check
    check (approval_posture in ('automatic_allowed', 'approval_required', 'human_only', 'blocked')),
  constraint rental_case_decisions_status_check
    check (status in ('proposed', 'pending_approval', 'active', 'rejected', 'superseded', 'withdrawn')),
  constraint rental_case_decisions_active_requires_effective_fields_check
    check (
      status <> 'active'
      or (
        effective_at is not null
        and effective_value_payload is not null
        and approval_posture <> 'blocked'
      )
    ),
  constraint rental_case_decisions_active_approval_required_reference_check
    check (
      not (status = 'active' and approval_posture = 'approval_required')
      or approval_request_id is not null
    ),
  constraint rental_case_decisions_supersedes_self_check
    check (supersedes_case_decision_id is null or supersedes_case_decision_id <> id),
  constraint rental_case_decisions_supersedes_fkey
    foreign key (supersedes_case_decision_id, rental_case_id)
    references public.rental_case_decisions(id, rental_case_id)
    on delete restrict
);

create unique index if not exists rental_case_decisions_active_scope_unique_idx
  on public.rental_case_decisions (rental_case_id, domain_code, scope_key)
  where status = 'active';

create index if not exists rental_case_decisions_case_status_idx
  on public.rental_case_decisions (rental_case_id, status);

create table if not exists public.rental_case_requirements (
  id bigint generated by default as identity primary key,
  rental_case_requirement_uuid uuid not null default extensions.gen_random_uuid(),
  rental_case_id bigint not null references public.rental_cases(id) on delete restrict,
  requirement_type text not null,
  domain_code text not null,
  applicability_basis text not null,
  owner_role text,
  owner_reference text,
  due_at timestamptz,
  status text not null,
  blocking_scope text not null,
  evidence_reference text,
  waiver_case_decision_id bigint,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  resolved_at timestamptz,
  constraint rental_case_requirements_uuid_unique unique (rental_case_requirement_uuid),
  constraint rental_case_requirements_case_id_unique unique (id, rental_case_id),
  constraint rental_case_requirements_requirement_type_nonempty check (btrim(requirement_type) <> ''),
  constraint rental_case_requirements_domain_code_nonempty check (btrim(domain_code) <> ''),
  constraint rental_case_requirements_applicability_basis_nonempty check (btrim(applicability_basis) <> ''),
  constraint rental_case_requirements_owner_role_nonempty check (owner_role is null or btrim(owner_role) <> ''),
  constraint rental_case_requirements_owner_reference_nonempty check (owner_reference is null or btrim(owner_reference) <> ''),
  constraint rental_case_requirements_status_check
    check (status in ('not_applicable', 'required', 'in_progress', 'satisfied', 'waived', 'unresolved')),
  constraint rental_case_requirements_blocking_scope_check
    check (blocking_scope in ('none', 'action', 'transition', 'readiness', 'commercial_scope')),
  constraint rental_case_requirements_evidence_reference_nonempty
    check (evidence_reference is null or btrim(evidence_reference) <> ''),
  constraint rental_case_requirements_resolved_state_timestamp_check
    check (
      status not in ('not_applicable', 'satisfied', 'waived')
      or resolved_at is not null
    ),
  constraint rental_case_requirements_waiver_case_decision_fkey
    foreign key (waiver_case_decision_id, rental_case_id)
    references public.rental_case_decisions(id, rental_case_id)
    on delete restrict
);

create index if not exists rental_case_requirements_open_due_idx
  on public.rental_case_requirements (status, due_at)
  where status in ('required', 'in_progress', 'unresolved');

create table if not exists public.rental_case_open_questions (
  id bigint generated by default as identity primary key,
  rental_case_open_question_uuid uuid not null default extensions.gen_random_uuid(),
  rental_case_id bigint not null references public.rental_cases(id) on delete restrict,
  question_type text not null,
  domain_code text not null,
  human_question_text text not null,
  blocking_scope text not null,
  requested_from_role text,
  status text not null,
  proposed_answer_payload jsonb,
  source_reference text,
  supersedes_open_question_id bigint,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  resolved_at timestamptz,
  constraint rental_case_open_questions_uuid_unique unique (rental_case_open_question_uuid),
  constraint rental_case_open_questions_case_id_unique unique (id, rental_case_id),
  constraint rental_case_open_questions_question_type_nonempty check (btrim(question_type) <> ''),
  constraint rental_case_open_questions_domain_code_nonempty check (btrim(domain_code) <> ''),
  constraint rental_case_open_questions_human_question_text_nonempty check (btrim(human_question_text) <> ''),
  constraint rental_case_open_questions_blocking_scope_check
    check (blocking_scope in ('none', 'action', 'transition', 'readiness', 'commercial_scope')),
  constraint rental_case_open_questions_requested_from_role_nonempty
    check (requested_from_role is null or btrim(requested_from_role) <> ''),
  constraint rental_case_open_questions_status_check
    check (status in ('open', 'answered_pending_validation', 'resolved', 'closed_not_needed', 'superseded')),
  constraint rental_case_open_questions_source_reference_nonempty
    check (source_reference is null or btrim(source_reference) <> ''),
  constraint rental_case_open_questions_resolved_state_timestamp_check
    check (
      status not in ('resolved', 'closed_not_needed', 'superseded')
      or resolved_at is not null
    ),
  constraint rental_case_open_questions_supersedes_self_check
    check (supersedes_open_question_id is null or supersedes_open_question_id <> id),
  constraint rental_case_open_questions_supersedes_fkey
    foreign key (supersedes_open_question_id, rental_case_id)
    references public.rental_case_open_questions(id, rental_case_id)
    on delete restrict
);

create index if not exists rental_case_open_questions_unresolved_idx
  on public.rental_case_open_questions (status, rental_case_id)
  where status in ('open', 'answered_pending_validation');

create table if not exists public.rental_case_blockers (
  id bigint generated by default as identity primary key,
  rental_case_blocker_uuid uuid not null default extensions.gen_random_uuid(),
  rental_case_id bigint not null references public.rental_cases(id) on delete restrict,
  blocker_type text not null,
  blocked_subject_type text not null,
  blocked_subject_id bigint,
  blocked_subject_reference text,
  origin_entity_type text not null,
  origin_entity_id bigint,
  origin_entity_reference text,
  severity text not null,
  status text not null,
  resolution_condition_text text not null,
  resolution_reference text,
  supersedes_blocker_id bigint,
  opened_at timestamptz not null default timezone('utc', now()),
  resolved_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint rental_case_blockers_uuid_unique unique (rental_case_blocker_uuid),
  constraint rental_case_blockers_case_id_unique unique (id, rental_case_id),
  constraint rental_case_blockers_blocker_type_nonempty check (btrim(blocker_type) <> ''),
  constraint rental_case_blockers_blocked_subject_type_check
    check (blocked_subject_type in ('transition', 'action', 'readiness', 'decision', 'artifact_refresh')),
  constraint rental_case_blockers_blocked_subject_reference_nonempty
    check (blocked_subject_reference is null or btrim(blocked_subject_reference) <> ''),
  constraint rental_case_blockers_blocked_subject_present_check
    check (blocked_subject_id is not null or blocked_subject_reference is not null),
  constraint rental_case_blockers_origin_entity_type_nonempty check (btrim(origin_entity_type) <> ''),
  constraint rental_case_blockers_origin_entity_reference_nonempty
    check (origin_entity_reference is null or btrim(origin_entity_reference) <> ''),
  constraint rental_case_blockers_origin_entity_present_check
    check (origin_entity_id is not null or origin_entity_reference is not null),
  constraint rental_case_blockers_severity_check
    check (severity in ('low', 'medium', 'high')),
  constraint rental_case_blockers_status_check
    check (status in ('open', 'resolved', 'superseded', 'cancelled')),
  constraint rental_case_blockers_resolution_condition_text_nonempty
    check (btrim(resolution_condition_text) <> ''),
  constraint rental_case_blockers_resolution_reference_nonempty
    check (resolution_reference is null or btrim(resolution_reference) <> ''),
  constraint rental_case_blockers_resolved_state_timestamp_check
    check (
      status = 'open'
      or resolved_at is not null
    ),
  constraint rental_case_blockers_supersedes_self_check
    check (supersedes_blocker_id is null or supersedes_blocker_id <> id),
  constraint rental_case_blockers_supersedes_fkey
    foreign key (supersedes_blocker_id, rental_case_id)
    references public.rental_case_blockers(id, rental_case_id)
    on delete restrict
);

create index if not exists rental_case_blockers_open_idx
  on public.rental_case_blockers (rental_case_id, severity, opened_at desc)
  where status = 'open';

create table if not exists public.rental_case_proposed_changes (
  id bigint generated by default as identity primary key,
  rental_case_proposed_change_uuid uuid not null default extensions.gen_random_uuid(),
  rental_case_id bigint not null references public.rental_cases(id) on delete restrict,
  change_kind text not null,
  domain_code text not null,
  prior_value_payload jsonb,
  proposed_value_payload jsonb not null,
  source_reference text,
  detected_at timestamptz not null default timezone('utc', now()),
  impact_classification text,
  affected_domain_codes text[] not null default '{}'::text[],
  review_posture text,
  status text not null,
  final_value_payload jsonb,
  supersedes_proposed_change_id bigint,
  accepted_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint rental_case_proposed_changes_uuid_unique unique (rental_case_proposed_change_uuid),
  constraint rental_case_proposed_changes_case_id_unique unique (id, rental_case_id),
  constraint rental_case_proposed_changes_change_kind_nonempty check (btrim(change_kind) <> ''),
  constraint rental_case_proposed_changes_domain_code_nonempty check (btrim(domain_code) <> ''),
  constraint rental_case_proposed_changes_source_reference_nonempty
    check (source_reference is null or btrim(source_reference) <> ''),
  constraint rental_case_proposed_changes_impact_classification_check
    check (
      impact_classification is null
      or impact_classification in ('low_impact', 'material_impact', 'fundamental_scope_change')
    ),
  constraint rental_case_proposed_changes_affected_domain_codes_check
    check (private.workflow_text_array_values_nonempty(affected_domain_codes)),
  constraint rental_case_proposed_changes_review_posture_check
    check (
      review_posture is null
      or review_posture in ('automatic_allowed', 'approval_required', 'human_only', 'blocked')
    ),
  constraint rental_case_proposed_changes_status_check
    check (status in ('proposed', 'under_review', 'accepted', 'rejected', 'superseded', 'withdrawn')),
  constraint rental_case_proposed_changes_accepted_requires_final_value_check
    check (
      status <> 'accepted'
      or (final_value_payload is not null and accepted_at is not null)
    ),
  constraint rental_case_proposed_changes_supersedes_self_check
    check (supersedes_proposed_change_id is null or supersedes_proposed_change_id <> id),
  constraint rental_case_proposed_changes_supersedes_fkey
    foreign key (supersedes_proposed_change_id, rental_case_id)
    references public.rental_case_proposed_changes(id, rental_case_id)
    on delete restrict
);

create index if not exists rental_case_proposed_changes_active_idx
  on public.rental_case_proposed_changes (rental_case_id, status, detected_at desc)
  where status in ('proposed', 'under_review');

create table if not exists public.rental_case_reschedule_requests (
  id bigint generated by default as identity primary key,
  rental_case_reschedule_request_uuid uuid not null default extensions.gen_random_uuid(),
  rental_case_id bigint not null references public.rental_cases(id) on delete restrict,
  current_active_date_snapshot jsonb not null,
  requested_date_payload jsonb not null,
  candidate_dates_payload jsonb not null default '[]'::jsonb,
  consequence_summary_payload jsonb not null default '{}'::jsonb,
  status text not null,
  urgency_class text not null,
  confirmed_proposed_change_id bigint,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  confirmed_at timestamptz,
  constraint rental_case_reschedule_requests_uuid_unique unique (rental_case_reschedule_request_uuid),
  constraint rental_case_reschedule_requests_case_id_unique unique (id, rental_case_id),
  constraint rental_case_reschedule_requests_current_snapshot_object_check
    check (jsonb_typeof(current_active_date_snapshot) = 'object'),
  constraint rental_case_reschedule_requests_requested_date_object_check
    check (jsonb_typeof(requested_date_payload) = 'object'),
  constraint rental_case_reschedule_requests_candidate_dates_array_check
    check (jsonb_typeof(candidate_dates_payload) = 'array'),
  constraint rental_case_reschedule_requests_consequence_summary_object_check
    check (jsonb_typeof(consequence_summary_payload) = 'object'),
  constraint rental_case_reschedule_requests_status_check
    check (
      status in (
        'proposed',
        'evaluating',
        'offered',
        'awaiting_client_confirmation',
        'confirmed',
        'rejected',
        'withdrawn',
        'superseded'
      )
    ),
  constraint rental_case_reschedule_requests_urgency_class_check
    check (urgency_class in ('normal', 'urgent_impact')),
  constraint rental_case_reschedule_requests_confirmed_requires_change_check
    check (
      status <> 'confirmed'
      or (confirmed_proposed_change_id is not null and confirmed_at is not null)
    ),
  constraint rental_case_reschedule_requests_confirmed_change_fkey
    foreign key (confirmed_proposed_change_id, rental_case_id)
    references public.rental_case_proposed_changes(id, rental_case_id)
    on delete restrict
);

create index if not exists rental_case_reschedule_requests_active_idx
  on public.rental_case_reschedule_requests (rental_case_id, status, created_at desc)
  where status in ('proposed', 'evaluating', 'offered', 'awaiting_client_confirmation');

create table if not exists public.rental_case_approval_requests (
  id bigint generated by default as identity primary key,
  rental_case_approval_request_uuid uuid not null default extensions.gen_random_uuid(),
  rental_case_id bigint not null references public.rental_cases(id) on delete restrict,
  target_entity_type text not null,
  target_entity_id bigint,
  target_entity_reference text,
  approval_type text not null,
  reason_text text not null,
  evidence_reference_keys text[] not null default '{}'::text[],
  required_approver_role text,
  required_approver_reference text,
  status text not null,
  decision_payload jsonb,
  decided_at timestamptz,
  decided_by_reference text,
  decision_notes text,
  supersedes_approval_request_id bigint,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint rental_case_approval_requests_uuid_unique unique (rental_case_approval_request_uuid),
  constraint rental_case_approval_requests_case_id_unique unique (id, rental_case_id),
  constraint rental_case_approval_requests_target_entity_type_nonempty check (btrim(target_entity_type) <> ''),
  constraint rental_case_approval_requests_target_entity_reference_nonempty
    check (target_entity_reference is null or btrim(target_entity_reference) <> ''),
  constraint rental_case_approval_requests_target_entity_present_check
    check (target_entity_id is not null or target_entity_reference is not null),
  constraint rental_case_approval_requests_approval_type_nonempty check (btrim(approval_type) <> ''),
  constraint rental_case_approval_requests_reason_text_nonempty check (btrim(reason_text) <> ''),
  constraint rental_case_approval_requests_evidence_reference_keys_check
    check (private.workflow_text_array_values_nonempty(evidence_reference_keys)),
  constraint rental_case_approval_requests_required_approver_role_nonempty
    check (required_approver_role is null or btrim(required_approver_role) <> ''),
  constraint rental_case_approval_requests_required_approver_reference_nonempty
    check (required_approver_reference is null or btrim(required_approver_reference) <> ''),
  constraint rental_case_approval_requests_status_check
    check (status in ('open', 'approved', 'rejected', 'expired', 'cancelled', 'superseded')),
  constraint rental_case_approval_requests_decision_payload_object_or_array_check
    check (
      decision_payload is null
      or jsonb_typeof(decision_payload) in ('object', 'array')
    ),
  constraint rental_case_approval_requests_decided_by_reference_nonempty
    check (decided_by_reference is null or btrim(decided_by_reference) <> ''),
  constraint rental_case_approval_requests_decision_notes_nonempty
    check (decision_notes is null or btrim(decision_notes) <> ''),
  constraint rental_case_approval_requests_decided_states_timestamp_check
    check (
      status not in ('approved', 'rejected')
      or decided_at is not null
    ),
  constraint rental_case_approval_requests_supersedes_self_check
    check (supersedes_approval_request_id is null or supersedes_approval_request_id <> id),
  constraint rental_case_approval_requests_supersedes_fkey
    foreign key (supersedes_approval_request_id, rental_case_id)
    references public.rental_case_approval_requests(id, rental_case_id)
    on delete restrict
);

create index if not exists rental_case_approval_requests_pending_idx
  on public.rental_case_approval_requests (rental_case_id, status, created_at desc)
  where status = 'open';

alter table public.rental_case_decisions
  add constraint rental_case_decisions_approval_request_fkey
  foreign key (approval_request_id, rental_case_id)
  references public.rental_case_approval_requests(id, rental_case_id)
  on delete restrict;

create table if not exists public.workflow_actions (
  id bigint generated by default as identity primary key,
  workflow_action_uuid uuid not null default extensions.gen_random_uuid(),
  rental_case_id bigint not null references public.rental_cases(id) on delete restrict,
  action_type text not null,
  action_category text not null,
  target_adapter_code text not null,
  reason_entity_type text not null,
  reason_entity_id bigint,
  reason_entity_reference text,
  structured_payload jsonb not null default '{}'::jsonb,
  approval_posture text not null,
  status text not null,
  semantic_subject_hash text not null,
  source_case_revision integer not null,
  target_scope_key text,
  idempotency_key text not null,
  due_at timestamptz,
  supersedes_workflow_action_id bigint,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint workflow_actions_uuid_unique unique (workflow_action_uuid),
  constraint workflow_actions_case_and_idempotency_unique unique (rental_case_id, idempotency_key),
  constraint workflow_actions_case_id_unique unique (id, rental_case_id),
  constraint workflow_actions_action_type_check
    check (
      action_type in (
        'REQUEST_CLIENT_INFORMATION',
        'SEND_DISCOVERY_CALL_INVITE',
        'SEND_SITE_VISIT_PROPOSAL',
        'SEND_PROPOSAL_MESSAGE',
        'SEND_PROPOSAL_FOLLOW_UP',
        'REQUEST_CONFIRMATION_PAYMENT',
        'REQUEST_SIGNED_AGREEMENT',
        'REQUEST_FINAL_EVENT_INFORMATION',
        'REQUEST_SUPPLIER_INFORMATION',
        'ESCALATE_COMPLIANCE_REVIEW',
        'REQUEST_EXCEPTION_APPROVAL',
        'CREATE_INTERNAL_TASK_ITEM',
        'CREATE_CALENDAR_HOLD',
        'CREATE_PAYMENT_REQUEST',
        'DRAFT_PROPOSAL_ARTIFACT',
        'DRAFT_AGREEMENT_ARTIFACT',
        'DRAFT_INTERNAL_EVENT_BRIEF',
        'SYNC_ARTIFACT_PROJECTION',
        'MARK_ARTIFACT_REFRESH_REQUIRED',
        'SCHEDULE_FOLLOW_UP_REVIEW',
        'ESCALATE_DORMANT_CASE_REVIEW',
        'SUPERSEDE_STALE_ACTIONS',
        'RECORD_MANUAL_CLOSE_PACKET'
      )
    ),
  constraint workflow_actions_action_category_check
    check (
      action_category in (
        'communication',
        'document',
        'commercial',
        'coordination',
        'compliance',
        'approval',
        'follow_up',
        'sync',
        'internal_control'
      )
    ),
  constraint workflow_actions_target_adapter_code_nonempty check (btrim(target_adapter_code) <> ''),
  constraint workflow_actions_reason_entity_type_nonempty check (btrim(reason_entity_type) <> ''),
  constraint workflow_actions_reason_entity_reference_nonempty
    check (reason_entity_reference is null or btrim(reason_entity_reference) <> ''),
  constraint workflow_actions_reason_entity_present_check
    check (reason_entity_id is not null or reason_entity_reference is not null),
  constraint workflow_actions_structured_payload_object_check
    check (jsonb_typeof(structured_payload) = 'object'),
  constraint workflow_actions_approval_posture_check
    check (approval_posture in ('automatic_allowed', 'approval_required', 'human_only', 'blocked')),
  constraint workflow_actions_status_check
    check (
      status in (
        'proposed',
        'awaiting_approval',
        'approved',
        'ready_to_execute',
        'executing',
        'succeeded',
        'failed',
        'cancelled',
        'superseded'
      )
    ),
  constraint workflow_actions_semantic_subject_hash_nonempty check (btrim(semantic_subject_hash) <> ''),
  constraint workflow_actions_source_case_revision_nonnegative check (source_case_revision >= 0),
  constraint workflow_actions_target_scope_key_nonempty
    check (target_scope_key is null or btrim(target_scope_key) <> ''),
  constraint workflow_actions_idempotency_key_nonempty check (btrim(idempotency_key) <> ''),
  constraint workflow_actions_supersedes_self_check
    check (supersedes_workflow_action_id is null or supersedes_workflow_action_id <> id),
  constraint workflow_actions_supersedes_fkey
    foreign key (supersedes_workflow_action_id, rental_case_id)
    references public.workflow_actions(id, rental_case_id)
    on delete restrict
);

create index if not exists workflow_actions_pending_execution_idx
  on public.workflow_actions (status, due_at)
  where status in ('awaiting_approval', 'approved', 'ready_to_execute', 'executing');

create index if not exists workflow_actions_failed_idx
  on public.workflow_actions (rental_case_id, updated_at desc)
  where status = 'failed';

create table if not exists public.workflow_execution_attempts (
  id bigint generated by default as identity primary key,
  workflow_execution_attempt_uuid uuid not null default extensions.gen_random_uuid(),
  workflow_action_id bigint not null,
  rental_case_id bigint not null,
  attempt_number integer not null,
  adapter_code text not null,
  started_at timestamptz not null default timezone('utc', now()),
  completed_at timestamptz,
  external_reference text,
  status text not null,
  failure_code text,
  retry_eligible boolean not null default false,
  response_snapshot jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  constraint workflow_execution_attempts_uuid_unique unique (workflow_execution_attempt_uuid),
  constraint workflow_execution_attempts_workflow_action_attempt_unique unique (workflow_action_id, attempt_number),
  constraint workflow_execution_attempts_attempt_number_positive check (attempt_number > 0),
  constraint workflow_execution_attempts_adapter_code_nonempty check (btrim(adapter_code) <> ''),
  constraint workflow_execution_attempts_completed_after_started_check
    check (completed_at is null or completed_at >= started_at),
  constraint workflow_execution_attempts_external_reference_nonempty
    check (external_reference is null or btrim(external_reference) <> ''),
  constraint workflow_execution_attempts_status_check
    check (status in ('started', 'succeeded', 'failed', 'timeout', 'cancelled')),
  constraint workflow_execution_attempts_failure_code_nonempty
    check (failure_code is null or btrim(failure_code) <> ''),
  constraint workflow_execution_attempts_terminal_states_require_completed_at_check
    check (
      status = 'started'
      or completed_at is not null
    ),
  constraint workflow_execution_attempts_response_snapshot_object_or_array_check
    check (jsonb_typeof(response_snapshot) in ('object', 'array')),
  constraint workflow_execution_attempts_workflow_action_fkey
    foreign key (workflow_action_id, rental_case_id)
    references public.workflow_actions(id, rental_case_id)
    on delete restrict
);

create index if not exists workflow_execution_attempts_action_started_at_idx
  on public.workflow_execution_attempts (workflow_action_id, started_at desc);

create table if not exists public.rental_case_follow_ups (
  id bigint generated by default as identity primary key,
  rental_case_follow_up_uuid uuid not null default extensions.gen_random_uuid(),
  rental_case_id bigint not null references public.rental_cases(id) on delete restrict,
  reason_code text not null,
  waiting_for_role text,
  waiting_for_reference text,
  due_at timestamptz not null,
  urgency_level text not null,
  cadence_policy_code text,
  attempt_count integer not null default 0,
  escalate_after integer,
  status text not null,
  next_action_type text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  completed_at timestamptz,
  constraint rental_case_follow_ups_uuid_unique unique (rental_case_follow_up_uuid),
  constraint rental_case_follow_ups_case_id_unique unique (id, rental_case_id),
  constraint rental_case_follow_ups_reason_code_nonempty check (btrim(reason_code) <> ''),
  constraint rental_case_follow_ups_waiting_for_role_nonempty
    check (waiting_for_role is null or btrim(waiting_for_role) <> ''),
  constraint rental_case_follow_ups_waiting_for_reference_nonempty
    check (waiting_for_reference is null or btrim(waiting_for_reference) <> ''),
  constraint rental_case_follow_ups_urgency_level_check
    check (urgency_level in ('low', 'medium', 'high', 'urgent')),
  constraint rental_case_follow_ups_cadence_policy_code_nonempty
    check (cadence_policy_code is null or btrim(cadence_policy_code) <> ''),
  constraint rental_case_follow_ups_attempt_count_nonnegative
    check (attempt_count >= 0),
  constraint rental_case_follow_ups_escalate_after_positive
    check (escalate_after is null or escalate_after > 0),
  constraint rental_case_follow_ups_status_check
    check (status in ('scheduled', 'due', 'overdue', 'escalated', 'completed', 'cancelled')),
  constraint rental_case_follow_ups_next_action_type_check
    check (
      next_action_type is null
      or next_action_type in (
        'REQUEST_CLIENT_INFORMATION',
        'SEND_DISCOVERY_CALL_INVITE',
        'SEND_SITE_VISIT_PROPOSAL',
        'SEND_PROPOSAL_MESSAGE',
        'SEND_PROPOSAL_FOLLOW_UP',
        'REQUEST_CONFIRMATION_PAYMENT',
        'REQUEST_SIGNED_AGREEMENT',
        'REQUEST_FINAL_EVENT_INFORMATION',
        'REQUEST_SUPPLIER_INFORMATION',
        'ESCALATE_COMPLIANCE_REVIEW',
        'REQUEST_EXCEPTION_APPROVAL',
        'CREATE_INTERNAL_TASK_ITEM',
        'CREATE_CALENDAR_HOLD',
        'CREATE_PAYMENT_REQUEST',
        'DRAFT_PROPOSAL_ARTIFACT',
        'DRAFT_AGREEMENT_ARTIFACT',
        'DRAFT_INTERNAL_EVENT_BRIEF',
        'SYNC_ARTIFACT_PROJECTION',
        'MARK_ARTIFACT_REFRESH_REQUIRED',
        'SCHEDULE_FOLLOW_UP_REVIEW',
        'ESCALATE_DORMANT_CASE_REVIEW',
        'SUPERSEDE_STALE_ACTIONS',
        'RECORD_MANUAL_CLOSE_PACKET'
      )
    ),
  constraint rental_case_follow_ups_completed_state_timestamp_check
    check (
      status not in ('completed', 'cancelled')
      or completed_at is not null
    )
);

create index if not exists rental_case_follow_ups_due_idx
  on public.rental_case_follow_ups (status, due_at)
  where status in ('scheduled', 'due', 'overdue', 'escalated');

create table if not exists public.rental_case_milestones (
  id bigint generated by default as identity primary key,
  rental_case_milestone_uuid uuid not null default extensions.gen_random_uuid(),
  rental_case_id bigint not null references public.rental_cases(id) on delete restrict,
  milestone_type text not null,
  target_at timestamptz not null,
  status text not null,
  basis_reference text,
  related_requirement_id bigint,
  related_workflow_action_id bigint,
  supersedes_milestone_id bigint,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  completed_at timestamptz,
  constraint rental_case_milestones_uuid_unique unique (rental_case_milestone_uuid),
  constraint rental_case_milestones_case_id_unique unique (id, rental_case_id),
  constraint rental_case_milestones_milestone_type_nonempty check (btrim(milestone_type) <> ''),
  constraint rental_case_milestones_status_check
    check (status in ('scheduled', 'reached', 'completed', 'missed', 'superseded')),
  constraint rental_case_milestones_basis_reference_nonempty
    check (basis_reference is null or btrim(basis_reference) <> ''),
  constraint rental_case_milestones_completed_state_timestamp_check
    check (
      status not in ('completed', 'missed', 'superseded')
      or completed_at is not null
    ),
  constraint rental_case_milestones_supersedes_self_check
    check (supersedes_milestone_id is null or supersedes_milestone_id <> id),
  constraint rental_case_milestones_related_requirement_fkey
    foreign key (related_requirement_id, rental_case_id)
    references public.rental_case_requirements(id, rental_case_id)
    on delete restrict,
  constraint rental_case_milestones_related_workflow_action_fkey
    foreign key (related_workflow_action_id, rental_case_id)
    references public.workflow_actions(id, rental_case_id)
    on delete restrict,
  constraint rental_case_milestones_supersedes_fkey
    foreign key (supersedes_milestone_id, rental_case_id)
    references public.rental_case_milestones(id, rental_case_id)
    on delete restrict
);

create index if not exists rental_case_milestones_target_idx
  on public.rental_case_milestones (status, target_at)
  where status in ('scheduled', 'reached');

create table if not exists public.rental_case_artifacts (
  id bigint generated by default as identity primary key,
  rental_case_artifact_uuid uuid not null default extensions.gen_random_uuid(),
  rental_case_id bigint not null references public.rental_cases(id) on delete restrict,
  artifact_type text not null,
  storage_reference text,
  external_reference text,
  derived_from_case_revision integer not null,
  relevant_scope_fingerprint text,
  freshness_status text not null,
  last_generated_at timestamptz,
  last_synced_at timestamptz,
  supersedes_artifact_id bigint,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint rental_case_artifacts_uuid_unique unique (rental_case_artifact_uuid),
  constraint rental_case_artifacts_case_id_unique unique (id, rental_case_id),
  constraint rental_case_artifacts_artifact_type_check
    check (
      artifact_type in (
        'proposal',
        'agreement',
        'internal_event_brief',
        'readiness_summary',
        'staffing_plan',
        'supplier_plan',
        'task_surface_projection',
        'calendar_projection'
      )
    ),
  constraint rental_case_artifacts_storage_reference_nonempty
    check (storage_reference is null or btrim(storage_reference) <> ''),
  constraint rental_case_artifacts_external_reference_nonempty
    check (external_reference is null or btrim(external_reference) <> ''),
  constraint rental_case_artifacts_derived_from_case_revision_nonnegative
    check (derived_from_case_revision >= 0),
  constraint rental_case_artifacts_relevant_scope_fingerprint_nonempty
    check (relevant_scope_fingerprint is null or btrim(relevant_scope_fingerprint) <> ''),
  constraint rental_case_artifacts_freshness_status_check
    check (freshness_status in ('current', 'stale', 'refresh_required', 'superseded')),
  constraint rental_case_artifacts_last_synced_after_generated_check
    check (last_synced_at is null or last_generated_at is null or last_synced_at >= last_generated_at),
  constraint rental_case_artifacts_supersedes_self_check
    check (supersedes_artifact_id is null or supersedes_artifact_id <> id),
  constraint rental_case_artifacts_supersedes_fkey
    foreign key (supersedes_artifact_id, rental_case_id)
    references public.rental_case_artifacts(id, rental_case_id)
    on delete restrict
);

create index if not exists rental_case_artifacts_freshness_idx
  on public.rental_case_artifacts (rental_case_id, freshness_status, artifact_type)
  where freshness_status in ('stale', 'refresh_required', 'current');

alter table public.rental_cases
  add constraint rental_cases_current_proposal_artifact_fkey
  foreign key (current_proposal_artifact_id, id)
  references public.rental_case_artifacts(id, rental_case_id)
  on delete restrict;

alter table public.rental_cases
  add constraint rental_cases_current_agreement_artifact_fkey
  foreign key (current_agreement_artifact_id, id)
  references public.rental_case_artifacts(id, rental_case_id)
  on delete restrict;

create table if not exists public.rental_case_reasoning_projections (
  id bigint generated by default as identity primary key,
  rental_case_reasoning_projection_uuid uuid not null default extensions.gen_random_uuid(),
  rental_case_id bigint not null references public.rental_cases(id) on delete restrict,
  reasoning_purpose text not null,
  phase_7_context_contract_version integer not null,
  phase_8_workflow_contract_version integer not null default 1,
  source_case_revision integer not null,
  authority_outcome_classification text not null,
  relevant_current_truth_item_ids text[] not null default '{}'::text[],
  relevant_guidance_item_ids text[] not null default '{}'::text[],
  relevant_historical_item_ids text[] not null default '{}'::text[],
  conflict_codes text[] not null default '{}'::text[],
  contamination_codes text[] not null default '{}'::text[],
  unresolved_authority_codes text[] not null default '{}'::text[],
  warning_codes text[] not null default '{}'::text[],
  degraded_retrieval_summary jsonb not null default '{}'::jsonb,
  grounding_reference_keys text[] not null default '{}'::text[],
  created_at timestamptz not null default timezone('utc', now()),
  constraint rental_case_reasoning_projections_uuid_unique unique (rental_case_reasoning_projection_uuid),
  constraint rental_case_reasoning_projections_reasoning_purpose_nonempty
    check (btrim(reasoning_purpose) <> ''),
  constraint rental_case_reasoning_projections_phase_7_context_contract_version_positive
    check (phase_7_context_contract_version > 0),
  constraint rental_case_reasoning_projections_phase_8_workflow_contract_version_positive
    check (phase_8_workflow_contract_version > 0),
  constraint rental_case_reasoning_projections_source_case_revision_nonnegative
    check (source_case_revision >= 0),
  constraint rental_case_reasoning_projections_authority_outcome_check
    check (
      authority_outcome_classification in (
        'DETERMINISTIC_CURRENT',
        'CURRENT_GUIDANCE',
        'HISTORICAL_PRECEDENT',
        'MIXED_WITH_CURRENT_PRIORITY',
        'REQUIRES_CONFIRMATION',
        'INSUFFICIENT_CURRENT_AUTHORITY'
      )
    ),
  constraint rental_case_reasoning_projections_current_truth_ids_check
    check (private.workflow_text_array_values_nonempty(relevant_current_truth_item_ids)),
  constraint rental_case_reasoning_projections_guidance_ids_check
    check (private.workflow_text_array_values_nonempty(relevant_guidance_item_ids)),
  constraint rental_case_reasoning_projections_historical_ids_check
    check (private.workflow_text_array_values_nonempty(relevant_historical_item_ids)),
  constraint rental_case_reasoning_projections_conflict_codes_check
    check (
      private.workflow_text_array_values_allowed(
        conflict_codes,
        array[
          'TYPE_A_P4_BEATS_P6',
          'TYPE_B_P5_BEATS_P6',
          'TYPE_C_P6_EXISTS_BUT_CURRENT_MISSING',
          'TYPE_D_P4_REQUIRES_CONFIRMATION',
          'TYPE_E_P5_FAILURE_P4_SURVIVES',
          'TYPE_F_LIMITED_OR_UNKNOWN_PRECEDENT',
          'TYPE_G_CONFIDENTIALITY_ESCALATION'
        ]::text[]
      )
    ),
  constraint rental_case_reasoning_projections_contamination_codes_check
    check (
      private.workflow_text_array_values_allowed(
        contamination_codes,
        array[
          'historical_price_to_current_price',
          'historical_person_capability_to_current_service',
          'historical_concession_to_current_policy',
          'historical_legal_solution_to_current_guidance',
          'historical_overtime_handling_to_current_rate',
          'historical_room_use_to_current_access_right'
        ]::text[]
      )
    ),
  constraint rental_case_reasoning_projections_unresolved_authority_codes_check
    check (private.workflow_text_array_values_nonempty(unresolved_authority_codes)),
  constraint rental_case_reasoning_projections_warning_codes_check
    check (private.workflow_text_array_values_nonempty(warning_codes)),
  constraint rental_case_reasoning_projections_degraded_summary_object_check
    check (jsonb_typeof(degraded_retrieval_summary) = 'object'),
  constraint rental_case_reasoning_projections_grounding_reference_keys_check
    check (private.workflow_text_array_values_nonempty(grounding_reference_keys))
);

create index if not exists rental_case_reasoning_projections_case_created_at_idx
  on public.rental_case_reasoning_projections (rental_case_id, created_at desc);

drop trigger if exists trg_rental_cases_touch_updated_at on public.rental_cases;
create trigger trg_rental_cases_touch_updated_at
before update on public.rental_cases
for each row
execute function private.touch_updated_at();

drop trigger if exists trg_rental_case_decisions_touch_updated_at on public.rental_case_decisions;
create trigger trg_rental_case_decisions_touch_updated_at
before update on public.rental_case_decisions
for each row
execute function private.touch_updated_at();

drop trigger if exists trg_rental_case_requirements_touch_updated_at on public.rental_case_requirements;
create trigger trg_rental_case_requirements_touch_updated_at
before update on public.rental_case_requirements
for each row
execute function private.touch_updated_at();

drop trigger if exists trg_rental_case_open_questions_touch_updated_at on public.rental_case_open_questions;
create trigger trg_rental_case_open_questions_touch_updated_at
before update on public.rental_case_open_questions
for each row
execute function private.touch_updated_at();

drop trigger if exists trg_rental_case_blockers_touch_updated_at on public.rental_case_blockers;
create trigger trg_rental_case_blockers_touch_updated_at
before update on public.rental_case_blockers
for each row
execute function private.touch_updated_at();

drop trigger if exists trg_rental_case_proposed_changes_touch_updated_at on public.rental_case_proposed_changes;
create trigger trg_rental_case_proposed_changes_touch_updated_at
before update on public.rental_case_proposed_changes
for each row
execute function private.touch_updated_at();

drop trigger if exists trg_rental_case_reschedule_requests_touch_updated_at on public.rental_case_reschedule_requests;
create trigger trg_rental_case_reschedule_requests_touch_updated_at
before update on public.rental_case_reschedule_requests
for each row
execute function private.touch_updated_at();

drop trigger if exists trg_rental_case_approval_requests_touch_updated_at on public.rental_case_approval_requests;
create trigger trg_rental_case_approval_requests_touch_updated_at
before update on public.rental_case_approval_requests
for each row
execute function private.touch_updated_at();

drop trigger if exists trg_workflow_actions_touch_updated_at on public.workflow_actions;
create trigger trg_workflow_actions_touch_updated_at
before update on public.workflow_actions
for each row
execute function private.touch_updated_at();

drop trigger if exists trg_rental_case_follow_ups_touch_updated_at on public.rental_case_follow_ups;
create trigger trg_rental_case_follow_ups_touch_updated_at
before update on public.rental_case_follow_ups
for each row
execute function private.touch_updated_at();

drop trigger if exists trg_rental_case_milestones_touch_updated_at on public.rental_case_milestones;
create trigger trg_rental_case_milestones_touch_updated_at
before update on public.rental_case_milestones
for each row
execute function private.touch_updated_at();

drop trigger if exists trg_rental_case_artifacts_touch_updated_at on public.rental_case_artifacts;
create trigger trg_rental_case_artifacts_touch_updated_at
before update on public.rental_case_artifacts
for each row
execute function private.touch_updated_at();

drop trigger if exists trg_workflow_events_append_only_update on public.workflow_events;
create trigger trg_workflow_events_append_only_update
before update on public.workflow_events
for each row
execute function private.workflow_append_only_guard();

drop trigger if exists trg_workflow_events_append_only_delete on public.workflow_events;
create trigger trg_workflow_events_append_only_delete
before delete on public.workflow_events
for each row
execute function private.workflow_append_only_guard();

drop trigger if exists trg_rental_case_lifecycle_transitions_append_only_update on public.rental_case_lifecycle_transitions;
create trigger trg_rental_case_lifecycle_transitions_append_only_update
before update on public.rental_case_lifecycle_transitions
for each row
execute function private.workflow_append_only_guard();

drop trigger if exists trg_rental_case_lifecycle_transitions_append_only_delete on public.rental_case_lifecycle_transitions;
create trigger trg_rental_case_lifecycle_transitions_append_only_delete
before delete on public.rental_case_lifecycle_transitions
for each row
execute function private.workflow_append_only_guard();

drop trigger if exists trg_workflow_execution_attempts_append_only_update on public.workflow_execution_attempts;
create trigger trg_workflow_execution_attempts_append_only_update
before update on public.workflow_execution_attempts
for each row
execute function private.workflow_append_only_guard();

drop trigger if exists trg_workflow_execution_attempts_append_only_delete on public.workflow_execution_attempts;
create trigger trg_workflow_execution_attempts_append_only_delete
before delete on public.workflow_execution_attempts
for each row
execute function private.workflow_append_only_guard();

drop trigger if exists trg_rental_case_reasoning_projections_append_only_update on public.rental_case_reasoning_projections;
create trigger trg_rental_case_reasoning_projections_append_only_update
before update on public.rental_case_reasoning_projections
for each row
execute function private.workflow_append_only_guard();

drop trigger if exists trg_rental_case_reasoning_projections_append_only_delete on public.rental_case_reasoning_projections;
create trigger trg_rental_case_reasoning_projections_append_only_delete
before delete on public.rental_case_reasoning_projections
for each row
execute function private.workflow_append_only_guard();

alter table public.rental_cases enable row level security;
alter table public.workflow_events enable row level security;
alter table public.rental_case_lifecycle_transitions enable row level security;
alter table public.rental_case_open_questions enable row level security;
alter table public.rental_case_requirements enable row level security;
alter table public.rental_case_blockers enable row level security;
alter table public.rental_case_decisions enable row level security;
alter table public.rental_case_proposed_changes enable row level security;
alter table public.rental_case_reschedule_requests enable row level security;
alter table public.rental_case_approval_requests enable row level security;
alter table public.workflow_actions enable row level security;
alter table public.workflow_execution_attempts enable row level security;
alter table public.rental_case_follow_ups enable row level security;
alter table public.rental_case_milestones enable row level security;
alter table public.rental_case_artifacts enable row level security;
alter table public.rental_case_reasoning_projections enable row level security;

revoke all on table
  public.rental_cases,
  public.workflow_events,
  public.rental_case_lifecycle_transitions,
  public.rental_case_open_questions,
  public.rental_case_requirements,
  public.rental_case_blockers,
  public.rental_case_decisions,
  public.rental_case_proposed_changes,
  public.rental_case_reschedule_requests,
  public.rental_case_approval_requests,
  public.workflow_actions,
  public.workflow_execution_attempts,
  public.rental_case_follow_ups,
  public.rental_case_milestones,
  public.rental_case_artifacts,
  public.rental_case_reasoning_projections
from anon, authenticated, service_role;
