create or replace function private.normalize_historical_case_source_locator(p_source_locator text)
returns text
language sql
immutable
as $$
  select lower(regexp_replace(btrim(p_source_locator), '\s+', ' ', 'g'));
$$;

create or replace function private.historical_case_evidence_support_dimensions_valid(p_support_dimensions text[])
returns boolean
language sql
immutable
as $$
  select
    p_support_dimensions is not null
    and cardinality(p_support_dimensions) > 0
    and p_support_dimensions <@ array[
      'identity',
      'date',
      'responsibility',
      'decision',
      'lesson',
      'context'
    ]::text[]
    and not exists (
      select 1
      from unnest(p_support_dimensions) as support_dimension
      where support_dimension is null
        or btrim(support_dimension) = ''
    )
    and cardinality(p_support_dimensions) = (
      select count(distinct support_dimension)
      from unnest(p_support_dimensions) as support_dimension
    );
$$;

create table if not exists public.historical_case_evidence_roles (
  id bigint generated by default as identity primary key,
  role_code text not null unique,
  display_name text not null,
  description text not null,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint historical_case_evidence_roles_code_nonempty
    check (btrim(role_code) <> ''),
  constraint historical_case_evidence_roles_display_name_nonempty
    check (btrim(display_name) <> ''),
  constraint historical_case_evidence_roles_description_nonempty
    check (btrim(description) <> ''),
  constraint historical_case_evidence_roles_sort_order_nonnegative
    check (sort_order >= 0)
);

create table if not exists public.historical_case_version_source_objects (
  id bigint generated by default as identity primary key,
  historical_case_version_id bigint not null references public.historical_case_versions(id) on delete cascade,
  source_object_id bigint not null references public.knowledge_source_objects(id) on delete restrict,
  evidence_role_id bigint not null references public.historical_case_evidence_roles(id) on delete restrict,
  confidentiality_level_id bigint not null references public.knowledge_confidentiality_levels(id) on delete restrict,
  evidence_strength text not null,
  source_locator text not null,
  supported_claim_dimensions text[] not null,
  relationship_notes text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint historical_case_version_source_objects_evidence_strength_check
    check (evidence_strength in ('strong', 'moderate', 'limited')),
  constraint historical_case_version_source_objects_source_locator_nonempty
    check (btrim(source_locator) <> ''),
  constraint hcvso_supported_claim_dimensions_check
    check (private.historical_case_evidence_support_dimensions_valid(supported_claim_dimensions)),
  constraint hcvso_relationship_notes_nonempty
    check (relationship_notes is null or btrim(relationship_notes) <> '')
);

create unique index if not exists historical_case_version_source_objects_unique_idx
  on public.historical_case_version_source_objects (
    historical_case_version_id,
    source_object_id,
    evidence_role_id,
    private.normalize_historical_case_source_locator(source_locator)
  );

create index if not exists historical_case_version_source_objects_source_object_idx
  on public.historical_case_version_source_objects (source_object_id);

create or replace function private.enforce_historical_case_version_source_object_editability()
returns trigger
language plpgsql
as $$
declare
  target_historical_case_version_id bigint := coalesce(new.historical_case_version_id, old.historical_case_version_id);
  target_governance_status text;
begin
  select hcv.governance_status
  into target_governance_status
  from public.historical_case_versions hcv
  where hcv.id = target_historical_case_version_id;

  if target_governance_status is not null and target_governance_status <> 'draft' then
    raise exception 'historical case evidence associations are immutable once the parent case version is no longer draft'
      using errcode = '23514';
  end if;

  return coalesce(new, old);
end;
$$;

drop trigger if exists trg_historical_case_evidence_roles_touch_updated_at on public.historical_case_evidence_roles;
create trigger trg_historical_case_evidence_roles_touch_updated_at
before update on public.historical_case_evidence_roles
for each row
execute function private.touch_updated_at();

drop trigger if exists trg_historical_case_version_source_objects_touch_updated_at on public.historical_case_version_source_objects;
create trigger trg_historical_case_version_source_objects_touch_updated_at
before update on public.historical_case_version_source_objects
for each row
execute function private.touch_updated_at();

drop trigger if exists trg_enforce_historical_case_version_source_object_editability on public.historical_case_version_source_objects;
create trigger trg_enforce_historical_case_version_source_object_editability
before insert or update or delete on public.historical_case_version_source_objects
for each row
execute function private.enforce_historical_case_version_source_object_editability();

insert into public.historical_case_evidence_roles (
  role_code,
  display_name,
  description,
  sort_order
)
values
  (
    'curated_case_library_source',
    'Curated Case Library Source',
    'Retrospective curated case-library source used as governed historical reconstruction input rather than as original contemporaneous evidence.',
    10
  ),
  (
    'primary_supporting_evidence',
    'Primary Supporting Evidence',
    'Primary source artifact that materially supports the governed historical reconstruction for the case version.',
    20
  ),
  (
    'secondary_supporting_evidence',
    'Secondary Supporting Evidence',
    'Secondary source artifact that supports or corroborates parts of the governed historical reconstruction for the case version.',
    30
  ),
  (
    'context_only_support',
    'Context-Only Support',
    'Contextual source artifact retained for background interpretation without being treated as direct primary evidence for the governed reconstruction.',
    40
  )
on conflict (role_code) do update
set display_name = excluded.display_name,
    description = excluded.description,
    sort_order = excluded.sort_order,
    is_active = true;

alter table public.historical_case_evidence_roles enable row level security;
alter table public.historical_case_version_source_objects enable row level security;

revoke all on table public.historical_case_evidence_roles from public, anon, authenticated, service_role;
revoke all on table public.historical_case_version_source_objects from public, anon, authenticated, service_role;
