create table if not exists private.historical_case_version_processing (
  historical_case_version_id bigint primary key references public.historical_case_versions(id) on delete cascade,
  search_unit_generation_status text not null default 'not_started',
  last_attempted_at timestamptz,
  last_succeeded_at timestamptz,
  retry_count integer not null default 0,
  last_error_code text,
  last_error_message text,
  updated_at timestamptz not null default timezone('utc', now()),
  constraint historical_case_version_processing_generation_status_check
    check (search_unit_generation_status in ('not_started', 'ready', 'in_progress', 'succeeded', 'failed', 'not_applicable')),
  constraint historical_case_version_processing_retry_count_nonnegative
    check (retry_count >= 0),
  constraint historical_case_version_processing_last_error_code_nonempty
    check (last_error_code is null or btrim(last_error_code) <> ''),
  constraint historical_case_version_processing_last_error_message_nonempty
    check (last_error_message is null or btrim(last_error_message) <> ''),
  constraint historical_case_version_processing_success_after_attempt
    check (
      search_unit_generation_status not in ('succeeded', 'not_applicable')
      or last_succeeded_at is null
      or last_attempted_at is null
      or last_succeeded_at >= last_attempted_at
    )
);

create or replace function private.strictest_knowledge_confidentiality_level_id(p_level_ids bigint[])
returns bigint
language sql
stable
as $$
  with normalized_level_ids as (
    select distinct level_id
    from unnest(coalesce(p_level_ids, '{}'::bigint[])) as level_id
    where level_id is not null
  )
  select kcl.id
  from normalized_level_ids nli
  join public.knowledge_confidentiality_levels kcl
    on kcl.id = nli.level_id
  order by kcl.sort_order desc, kcl.id desc
  limit 1;
$$;

create or replace function private.strictest_personal_information_status(p_statuses text[])
returns text
language sql
immutable
as $$
  select
    case
      when exists (
        select 1
        from unnest(coalesce(p_statuses, '{}'::text[])) as status_value
        where status_value = 'yes'
      ) then 'yes'
      when exists (
        select 1
        from unnest(coalesce(p_statuses, '{}'::text[])) as status_value
        where status_value = 'unknown'
      ) then 'unknown'
      else 'no'
    end;
$$;

create or replace function private.historical_case_search_unit_expected_source_key(
  p_unit_type text,
  p_historical_case_version_id bigint,
  p_responsibility_id bigint,
  p_decision_id bigint,
  p_lesson_id bigint
)
returns text
language sql
immutable
as $$
  select
    case p_unit_type
      when 'case_narrative' then format('case_narrative:%s', p_historical_case_version_id)
      when 'responsibility' then format('responsibility:%s', p_responsibility_id)
      when 'decision' then format('decision:%s', p_decision_id)
      when 'lesson' then format('lesson:%s', p_lesson_id)
      else null
    end;
$$;

create table if not exists private.historical_case_search_units (
  id bigint generated by default as identity primary key,
  source_key text not null unique,
  historical_case_version_id bigint not null references public.historical_case_versions(id) on delete cascade,
  historical_case_id bigint not null references public.historical_cases(id) on delete restrict,
  source_layer_role text not null default 'historical_precedent',
  unit_type text not null,
  case_code_snapshot text not null,
  case_title_snapshot text not null,
  precedent_type_snapshot text not null,
  precedent_availability_snapshot text not null,
  case_evidence_strength_snapshot text not null,
  case_contains_historical_value_only_content boolean not null,
  case_personal_information_status text not null,
  source_object_personal_information_status text not null,
  effective_confidentiality_level_id bigint not null references public.knowledge_confidentiality_levels(id) on delete restrict,
  unit_evidence_strength text not null,
  search_text text not null,
  actor_type text,
  lesson_kind text,
  historical_value_only boolean,
  contamination_risk_level text,
  current_authority_disposition text,
  responsibility_id bigint references public.historical_case_version_responsibilities(id) on delete cascade,
  decision_id bigint references public.historical_case_version_decisions(id) on delete cascade,
  lesson_id bigint references public.historical_case_version_lessons(id) on delete cascade,
  generation_strategy_code text not null,
  generation_strategy_version text not null,
  generated_at timestamptz not null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint historical_case_search_units_source_key_nonempty
    check (btrim(source_key) <> ''),
  constraint historical_case_search_units_source_layer_role_check
    check (source_layer_role = 'historical_precedent'),
  constraint historical_case_search_units_unit_type_check
    check (unit_type in ('case_narrative', 'responsibility', 'decision', 'lesson')),
  constraint historical_case_search_units_case_code_snapshot_nonempty
    check (btrim(case_code_snapshot) <> ''),
  constraint historical_case_search_units_case_title_snapshot_nonempty
    check (btrim(case_title_snapshot) <> ''),
  constraint historical_case_search_units_precedent_type_snapshot_check
    check (precedent_type_snapshot in ('full_case', 'limited_precedent', 'cautionary_precedent')),
  constraint historical_case_search_units_precedent_availability_snapshot_check
    check (precedent_availability_snapshot in ('active', 'limited', 'held', 'archived')),
  constraint historical_case_search_units_case_evidence_strength_snapshot_check
    check (case_evidence_strength_snapshot in ('strong', 'moderate', 'limited')),
  constraint historical_case_search_units_case_personal_information_status_check
    check (case_personal_information_status in ('yes', 'no', 'unknown')),
  constraint historical_case_search_units_source_object_personal_information_status_check
    check (source_object_personal_information_status in ('yes', 'no', 'unknown')),
  constraint historical_case_search_units_unit_evidence_strength_check
    check (unit_evidence_strength in ('strong', 'moderate', 'limited')),
  constraint historical_case_search_units_search_text_nonempty
    check (btrim(search_text) <> ''),
  constraint historical_case_search_units_actor_type_check
    check (actor_type is null or actor_type in ('wnc', 'client', 'external_supplier')),
  constraint historical_case_search_units_lesson_kind_check
    check (lesson_kind is null or lesson_kind in ('source_explicit', 'curated_lesson', 'analyst_inference', 'caution_warning')),
  constraint historical_case_search_units_statement_metadata_check
    check (
      (
        unit_type = 'case_narrative'
        and responsibility_id is null
        and decision_id is null
        and lesson_id is null
        and actor_type is null
        and lesson_kind is null
        and historical_value_only is null
        and contamination_risk_level is null
        and current_authority_disposition is null
      )
      or (
        unit_type = 'responsibility'
        and responsibility_id is not null
        and decision_id is null
        and lesson_id is null
        and actor_type is not null
        and lesson_kind is null
        and private.historical_case_statement_contamination_metadata_valid(
          historical_value_only,
          contamination_risk_level,
          current_authority_disposition
        )
      )
      or (
        unit_type = 'decision'
        and responsibility_id is null
        and decision_id is not null
        and lesson_id is null
        and actor_type is null
        and lesson_kind is null
        and private.historical_case_statement_contamination_metadata_valid(
          historical_value_only,
          contamination_risk_level,
          current_authority_disposition
        )
      )
      or (
        unit_type = 'lesson'
        and responsibility_id is null
        and decision_id is null
        and lesson_id is not null
        and actor_type is null
        and lesson_kind is not null
        and private.historical_case_statement_contamination_metadata_valid(
          historical_value_only,
          contamination_risk_level,
          current_authority_disposition
        )
      )
    ),
  constraint historical_case_search_units_generation_strategy_code_nonempty
    check (btrim(generation_strategy_code) <> ''),
  constraint historical_case_search_units_generation_strategy_version_nonempty
    check (btrim(generation_strategy_version) <> '')
);

create unique index if not exists historical_case_search_units_one_narrative_per_version_idx
  on private.historical_case_search_units (historical_case_version_id)
  where unit_type = 'case_narrative';

create unique index if not exists historical_case_search_units_one_responsibility_source_idx
  on private.historical_case_search_units (responsibility_id)
  where responsibility_id is not null;

create unique index if not exists historical_case_search_units_one_decision_source_idx
  on private.historical_case_search_units (decision_id)
  where decision_id is not null;

create unique index if not exists historical_case_search_units_one_lesson_source_idx
  on private.historical_case_search_units (lesson_id)
  where lesson_id is not null;

create index if not exists historical_case_search_units_version_type_idx
  on private.historical_case_search_units (historical_case_version_id, unit_type);

create index if not exists historical_case_search_units_case_idx
  on private.historical_case_search_units (historical_case_id, unit_type);

create table if not exists private.historical_case_unit_sources (
  id bigint generated by default as identity primary key,
  historical_case_search_unit_id bigint not null references private.historical_case_search_units(id) on delete cascade,
  historical_case_version_source_object_id bigint not null references public.historical_case_version_source_objects(id) on delete restrict,
  responsibility_source_id bigint references public.historical_case_version_responsibility_sources(id) on delete cascade,
  decision_source_id bigint references public.historical_case_version_decision_sources(id) on delete cascade,
  lesson_source_id bigint references public.historical_case_version_lesson_sources(id) on delete cascade,
  is_primary_trace boolean not null default false,
  created_at timestamptz not null default timezone('utc', now()),
  constraint historical_case_unit_sources_lineage_shape_check
    check (
      (
        responsibility_source_id is null
        and decision_source_id is null
        and lesson_source_id is null
      )
      or (
        responsibility_source_id is not null
        and decision_source_id is null
        and lesson_source_id is null
      )
      or (
        responsibility_source_id is null
        and decision_source_id is not null
        and lesson_source_id is null
      )
      or (
        responsibility_source_id is null
        and decision_source_id is null
        and lesson_source_id is not null
      )
    ),
  constraint historical_case_unit_sources_unique
    unique (
      historical_case_search_unit_id,
      historical_case_version_source_object_id,
      responsibility_source_id,
      decision_source_id,
      lesson_source_id
    )
);

create unique index if not exists historical_case_unit_sources_one_primary_idx
  on private.historical_case_unit_sources (historical_case_search_unit_id)
  where is_primary_trace;

create index if not exists historical_case_unit_sources_unit_idx
  on private.historical_case_unit_sources (historical_case_search_unit_id);

create index if not exists historical_case_unit_sources_source_object_idx
  on private.historical_case_unit_sources (historical_case_version_source_object_id);

create or replace function private.validate_historical_case_search_unit()
returns trigger
language plpgsql
as $$
declare
  parent_case_id bigint;
  expected_source_key text;
  linked_version_id bigint;
begin
  select hcv.historical_case_id
  into parent_case_id
  from public.historical_case_versions hcv
  where hcv.id = new.historical_case_version_id;

  if parent_case_id is null then
    return new;
  end if;

  if parent_case_id <> new.historical_case_id then
    raise exception 'historical search unit case % does not match parent historical case version % case %',
      new.historical_case_id,
      new.historical_case_version_id,
      parent_case_id
      using errcode = '23514';
  end if;

  expected_source_key := private.historical_case_search_unit_expected_source_key(
    new.unit_type,
    new.historical_case_version_id,
    new.responsibility_id,
    new.decision_id,
    new.lesson_id
  );

  if expected_source_key is null or new.source_key <> expected_source_key then
    raise exception 'historical search unit source_key % does not match the controlled source identity for unit type %',
      new.source_key,
      new.unit_type
      using errcode = '23514';
  end if;

  if new.responsibility_id is not null then
    select hcvr.historical_case_version_id
    into linked_version_id
    from public.historical_case_version_responsibilities hcvr
    where hcvr.id = new.responsibility_id;

    if linked_version_id <> new.historical_case_version_id then
      raise exception 'responsibility-backed historical search unit must remain within one historical case version'
        using errcode = '23514';
    end if;
  end if;

  if new.decision_id is not null then
    select hcvd.historical_case_version_id
    into linked_version_id
    from public.historical_case_version_decisions hcvd
    where hcvd.id = new.decision_id;

    if linked_version_id <> new.historical_case_version_id then
      raise exception 'decision-backed historical search unit must remain within one historical case version'
        using errcode = '23514';
    end if;
  end if;

  if new.lesson_id is not null then
    select hcvl.historical_case_version_id
    into linked_version_id
    from public.historical_case_version_lessons hcvl
    where hcvl.id = new.lesson_id;

    if linked_version_id <> new.historical_case_version_id then
      raise exception 'lesson-backed historical search unit must remain within one historical case version'
        using errcode = '23514';
    end if;
  end if;

  return new;
end;
$$;

create or replace function private.validate_historical_case_unit_source()
returns trigger
language plpgsql
as $$
declare
  unit_record private.historical_case_search_units%rowtype;
  source_object_version_id bigint;
  linked_version_id bigint;
  linked_source_object_id bigint;
begin
  select *
  into unit_record
  from private.historical_case_search_units hcsu
  where hcsu.id = new.historical_case_search_unit_id;

  if not found then
    return new;
  end if;

  select hcvso.historical_case_version_id
  into source_object_version_id
  from public.historical_case_version_source_objects hcvso
  where hcvso.id = new.historical_case_version_source_object_id;

  if source_object_version_id <> unit_record.historical_case_version_id then
    raise exception 'historical unit lineage source object must belong to the same historical case version as the search unit'
      using errcode = '23514';
  end if;

  if unit_record.unit_type = 'case_narrative' then
    if new.responsibility_source_id is not null
       or new.decision_source_id is not null
       or new.lesson_source_id is not null then
      raise exception 'case_narrative units must trace directly to case-version evidence associations'
        using errcode = '23514';
    end if;

    return new;
  end if;

  if unit_record.unit_type = 'responsibility' then
    if new.responsibility_source_id is null
       or new.decision_source_id is not null
       or new.lesson_source_id is not null then
      raise exception 'responsibility units must trace through responsibility provenance only'
        using errcode = '23514';
    end if;

    select
      hcvrs.historical_case_version_id,
      hcvrs.historical_case_version_source_object_id
    into linked_version_id, linked_source_object_id
    from public.historical_case_version_responsibility_sources hcvrs
    where hcvrs.id = new.responsibility_source_id;

    if linked_version_id <> unit_record.historical_case_version_id
       or linked_source_object_id <> new.historical_case_version_source_object_id then
      raise exception 'responsibility unit lineage must resolve to the same version-scoped evidence association'
        using errcode = '23514';
    end if;

    return new;
  end if;

  if unit_record.unit_type = 'decision' then
    if new.responsibility_source_id is not null
       or new.decision_source_id is null
       or new.lesson_source_id is not null then
      raise exception 'decision units must trace through decision provenance only'
        using errcode = '23514';
    end if;

    select
      hcvds.historical_case_version_id,
      hcvds.historical_case_version_source_object_id
    into linked_version_id, linked_source_object_id
    from public.historical_case_version_decision_sources hcvds
    where hcvds.id = new.decision_source_id;

    if linked_version_id <> unit_record.historical_case_version_id
       or linked_source_object_id <> new.historical_case_version_source_object_id then
      raise exception 'decision unit lineage must resolve to the same version-scoped evidence association'
        using errcode = '23514';
    end if;

    return new;
  end if;

  if unit_record.unit_type = 'lesson' then
    if new.responsibility_source_id is not null
       or new.decision_source_id is not null
       or new.lesson_source_id is null then
      raise exception 'lesson units must trace through lesson provenance only'
        using errcode = '23514';
    end if;

    select
      hcvls.historical_case_version_id,
      hcvls.historical_case_version_source_object_id
    into linked_version_id, linked_source_object_id
    from public.historical_case_version_lesson_sources hcvls
    where hcvls.id = new.lesson_source_id;

    if linked_version_id <> unit_record.historical_case_version_id
       or linked_source_object_id <> new.historical_case_version_source_object_id then
      raise exception 'lesson unit lineage must resolve to the same version-scoped evidence association'
        using errcode = '23514';
    end if;

    return new;
  end if;

  return new;
end;
$$;

create or replace function private.assert_historical_case_search_unit_has_sources(
  p_historical_case_search_unit_id bigint
)
returns void
language plpgsql
as $$
declare
  source_count bigint;
begin
  if p_historical_case_search_unit_id is null then
    return;
  end if;

  select count(*)
  into source_count
  from private.historical_case_unit_sources hcus
  where hcus.historical_case_search_unit_id = p_historical_case_search_unit_id;

  if source_count = 0 then
    raise exception 'historical search unit % must retain at least one provenance lineage row',
      p_historical_case_search_unit_id
      using errcode = '23514';
  end if;
end;
$$;

create or replace function private.enforce_historical_case_search_unit_has_sources_from_unit()
returns trigger
language plpgsql
as $$
begin
  perform private.assert_historical_case_search_unit_has_sources(new.id);
  return null;
end;
$$;

create or replace function private.enforce_historical_case_search_unit_has_sources_from_unit_source()
returns trigger
language plpgsql
as $$
begin
  if tg_op in ('DELETE', 'UPDATE') then
    perform private.assert_historical_case_search_unit_has_sources(old.historical_case_search_unit_id);
  end if;

  if tg_op = 'UPDATE' then
    perform private.assert_historical_case_search_unit_has_sources(new.historical_case_search_unit_id);
  end if;

  return null;
end;
$$;

create or replace function private.rebuild_historical_case_search_units_for_version(
  p_historical_case_version_id bigint
)
returns bigint
language plpgsql
as $$
declare
  version_record record;
  rebuild_started_at timestamptz := timezone('utc', now());
  generated_unit_count bigint := 0;
begin
  insert into private.historical_case_version_processing (
    historical_case_version_id,
    search_unit_generation_status
  )
  values (
    p_historical_case_version_id,
    'not_started'
  )
  on conflict (historical_case_version_id) do nothing;

  update private.historical_case_version_processing
  set search_unit_generation_status = 'in_progress',
      last_attempted_at = rebuild_started_at,
      last_error_code = null,
      last_error_message = null
  where historical_case_version_id = p_historical_case_version_id;

  select
    hcv.id as historical_case_version_id,
    hcv.historical_case_id,
    hc.case_code,
    hc.canonical_title,
    hcv.governance_status,
    hcv.precedent_availability,
    hcv.precedent_type,
    hcv.evidence_strength,
    hcv.curated_narrative,
    hcv.confidentiality_level_id,
    hcv.personal_information_status,
    hcv.contains_historical_value_only_content
  into version_record
  from public.historical_case_versions hcv
  join public.historical_cases hc
    on hc.id = hcv.historical_case_id
  where hcv.id = p_historical_case_version_id;

  if not found then
    raise exception 'historical case version % does not exist', p_historical_case_version_id
      using errcode = '23503';
  end if;

  if version_record.governance_status <> 'active'
     or version_record.precedent_availability not in ('active', 'limited') then
    update private.historical_case_version_processing
    set search_unit_generation_status = 'not_applicable',
        last_succeeded_at = rebuild_started_at
    where historical_case_version_id = p_historical_case_version_id;

    return 0;
  end if;

  if not exists (
    select 1
    from public.historical_case_version_source_objects hcvso
    where hcvso.historical_case_version_id = p_historical_case_version_id
  ) then
    raise exception 'active historical case version % cannot materialize search units without at least one case-version evidence association',
      p_historical_case_version_id
      using errcode = '23514';
  end if;

  with narrative_source_meta as (
    select
      hcvso.historical_case_version_id,
      private.strictest_knowledge_confidentiality_level_id(
        array_append(array_agg(distinct hcvso.confidentiality_level_id), version_record.confidentiality_level_id)
      ) as effective_confidentiality_level_id,
      private.strictest_personal_information_status(
        array_agg(distinct kso.personal_information_status)
      ) as source_object_personal_information_status
    from public.historical_case_version_source_objects hcvso
    join public.knowledge_source_objects kso
      on kso.id = hcvso.source_object_id
    where hcvso.historical_case_version_id = p_historical_case_version_id
    group by hcvso.historical_case_version_id
  )
  insert into private.historical_case_search_units (
    source_key,
    historical_case_version_id,
    historical_case_id,
    source_layer_role,
    unit_type,
    case_code_snapshot,
    case_title_snapshot,
    precedent_type_snapshot,
    precedent_availability_snapshot,
    case_evidence_strength_snapshot,
    case_contains_historical_value_only_content,
    case_personal_information_status,
    source_object_personal_information_status,
    effective_confidentiality_level_id,
    unit_evidence_strength,
    search_text,
    actor_type,
    lesson_kind,
    historical_value_only,
    contamination_risk_level,
    current_authority_disposition,
    responsibility_id,
    decision_id,
    lesson_id,
    generation_strategy_code,
    generation_strategy_version,
    generated_at
  )
  select
    private.historical_case_search_unit_expected_source_key(
      'case_narrative',
      version_record.historical_case_version_id,
      null,
      null,
      null
    ),
    version_record.historical_case_version_id,
    version_record.historical_case_id,
    'historical_precedent',
    'case_narrative',
    version_record.case_code,
    version_record.canonical_title,
    version_record.precedent_type,
    version_record.precedent_availability,
    version_record.evidence_strength,
    version_record.contains_historical_value_only_content,
    version_record.personal_information_status,
    narrative_source_meta.source_object_personal_information_status,
    narrative_source_meta.effective_confidentiality_level_id,
    version_record.evidence_strength,
    version_record.curated_narrative,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    null,
    'phase_6_governed_search_units',
    '6.4A_v1',
    rebuild_started_at
  from narrative_source_meta
  on conflict (source_key) do update
  set historical_case_version_id = excluded.historical_case_version_id,
      historical_case_id = excluded.historical_case_id,
      case_code_snapshot = excluded.case_code_snapshot,
      case_title_snapshot = excluded.case_title_snapshot,
      precedent_type_snapshot = excluded.precedent_type_snapshot,
      precedent_availability_snapshot = excluded.precedent_availability_snapshot,
      case_evidence_strength_snapshot = excluded.case_evidence_strength_snapshot,
      case_contains_historical_value_only_content = excluded.case_contains_historical_value_only_content,
      case_personal_information_status = excluded.case_personal_information_status,
      source_object_personal_information_status = excluded.source_object_personal_information_status,
      effective_confidentiality_level_id = excluded.effective_confidentiality_level_id,
      unit_evidence_strength = excluded.unit_evidence_strength,
      search_text = excluded.search_text,
      generation_strategy_code = excluded.generation_strategy_code,
      generation_strategy_version = excluded.generation_strategy_version,
      generated_at = excluded.generated_at;

  with responsibility_source_meta as (
    select
      hcvr.id as responsibility_id,
      private.strictest_knowledge_confidentiality_level_id(
        array_append(array_agg(distinct hcvso.confidentiality_level_id), version_record.confidentiality_level_id)
      ) as effective_confidentiality_level_id,
      private.strictest_personal_information_status(
        array_agg(distinct kso.personal_information_status)
      ) as source_object_personal_information_status
    from public.historical_case_version_responsibilities hcvr
    join public.historical_case_version_responsibility_sources hcvrs
      on hcvrs.responsibility_id = hcvr.id
    join public.historical_case_version_source_objects hcvso
      on hcvso.id = hcvrs.historical_case_version_source_object_id
    join public.knowledge_source_objects kso
      on kso.id = hcvso.source_object_id
    where hcvr.historical_case_version_id = p_historical_case_version_id
    group by hcvr.id
  )
  insert into private.historical_case_search_units (
    source_key,
    historical_case_version_id,
    historical_case_id,
    source_layer_role,
    unit_type,
    case_code_snapshot,
    case_title_snapshot,
    precedent_type_snapshot,
    precedent_availability_snapshot,
    case_evidence_strength_snapshot,
    case_contains_historical_value_only_content,
    case_personal_information_status,
    source_object_personal_information_status,
    effective_confidentiality_level_id,
    unit_evidence_strength,
    search_text,
    actor_type,
    lesson_kind,
    historical_value_only,
    contamination_risk_level,
    current_authority_disposition,
    responsibility_id,
    decision_id,
    lesson_id,
    generation_strategy_code,
    generation_strategy_version,
    generated_at
  )
  select
    private.historical_case_search_unit_expected_source_key(
      'responsibility',
      version_record.historical_case_version_id,
      hcvr.id,
      null,
      null
    ),
    version_record.historical_case_version_id,
    version_record.historical_case_id,
    'historical_precedent',
    'responsibility',
    version_record.case_code,
    version_record.canonical_title,
    version_record.precedent_type,
    version_record.precedent_availability,
    version_record.evidence_strength,
    version_record.contains_historical_value_only_content,
    version_record.personal_information_status,
    responsibility_source_meta.source_object_personal_information_status,
    responsibility_source_meta.effective_confidentiality_level_id,
    hcvr.evidence_strength,
    hcvr.responsibility_statement,
    hcvr.actor_type,
    null,
    hcvr.historical_value_only,
    hcvr.contamination_risk_level,
    hcvr.current_authority_disposition,
    hcvr.id,
    null,
    null,
    'phase_6_governed_search_units',
    '6.4A_v1',
    rebuild_started_at
  from public.historical_case_version_responsibilities hcvr
  join responsibility_source_meta
    on responsibility_source_meta.responsibility_id = hcvr.id
  where hcvr.historical_case_version_id = p_historical_case_version_id
  on conflict (source_key) do update
  set historical_case_version_id = excluded.historical_case_version_id,
      historical_case_id = excluded.historical_case_id,
      case_code_snapshot = excluded.case_code_snapshot,
      case_title_snapshot = excluded.case_title_snapshot,
      precedent_type_snapshot = excluded.precedent_type_snapshot,
      precedent_availability_snapshot = excluded.precedent_availability_snapshot,
      case_evidence_strength_snapshot = excluded.case_evidence_strength_snapshot,
      case_contains_historical_value_only_content = excluded.case_contains_historical_value_only_content,
      case_personal_information_status = excluded.case_personal_information_status,
      source_object_personal_information_status = excluded.source_object_personal_information_status,
      effective_confidentiality_level_id = excluded.effective_confidentiality_level_id,
      unit_evidence_strength = excluded.unit_evidence_strength,
      search_text = excluded.search_text,
      actor_type = excluded.actor_type,
      historical_value_only = excluded.historical_value_only,
      contamination_risk_level = excluded.contamination_risk_level,
      current_authority_disposition = excluded.current_authority_disposition,
      generation_strategy_code = excluded.generation_strategy_code,
      generation_strategy_version = excluded.generation_strategy_version,
      generated_at = excluded.generated_at;

  with decision_source_meta as (
    select
      hcvd.id as decision_id,
      private.strictest_knowledge_confidentiality_level_id(
        array_append(array_agg(distinct hcvso.confidentiality_level_id), version_record.confidentiality_level_id)
      ) as effective_confidentiality_level_id,
      private.strictest_personal_information_status(
        array_agg(distinct kso.personal_information_status)
      ) as source_object_personal_information_status
    from public.historical_case_version_decisions hcvd
    join public.historical_case_version_decision_sources hcvds
      on hcvds.decision_id = hcvd.id
    join public.historical_case_version_source_objects hcvso
      on hcvso.id = hcvds.historical_case_version_source_object_id
    join public.knowledge_source_objects kso
      on kso.id = hcvso.source_object_id
    where hcvd.historical_case_version_id = p_historical_case_version_id
    group by hcvd.id
  )
  insert into private.historical_case_search_units (
    source_key,
    historical_case_version_id,
    historical_case_id,
    source_layer_role,
    unit_type,
    case_code_snapshot,
    case_title_snapshot,
    precedent_type_snapshot,
    precedent_availability_snapshot,
    case_evidence_strength_snapshot,
    case_contains_historical_value_only_content,
    case_personal_information_status,
    source_object_personal_information_status,
    effective_confidentiality_level_id,
    unit_evidence_strength,
    search_text,
    actor_type,
    lesson_kind,
    historical_value_only,
    contamination_risk_level,
    current_authority_disposition,
    responsibility_id,
    decision_id,
    lesson_id,
    generation_strategy_code,
    generation_strategy_version,
    generated_at
  )
  select
    private.historical_case_search_unit_expected_source_key(
      'decision',
      version_record.historical_case_version_id,
      null,
      hcvd.id,
      null
    ),
    version_record.historical_case_version_id,
    version_record.historical_case_id,
    'historical_precedent',
    'decision',
    version_record.case_code,
    version_record.canonical_title,
    version_record.precedent_type,
    version_record.precedent_availability,
    version_record.evidence_strength,
    version_record.contains_historical_value_only_content,
    version_record.personal_information_status,
    decision_source_meta.source_object_personal_information_status,
    decision_source_meta.effective_confidentiality_level_id,
    hcvd.evidence_strength,
    hcvd.decision_statement,
    null,
    null,
    hcvd.historical_value_only,
    hcvd.contamination_risk_level,
    hcvd.current_authority_disposition,
    null,
    hcvd.id,
    null,
    'phase_6_governed_search_units',
    '6.4A_v1',
    rebuild_started_at
  from public.historical_case_version_decisions hcvd
  join decision_source_meta
    on decision_source_meta.decision_id = hcvd.id
  where hcvd.historical_case_version_id = p_historical_case_version_id
  on conflict (source_key) do update
  set historical_case_version_id = excluded.historical_case_version_id,
      historical_case_id = excluded.historical_case_id,
      case_code_snapshot = excluded.case_code_snapshot,
      case_title_snapshot = excluded.case_title_snapshot,
      precedent_type_snapshot = excluded.precedent_type_snapshot,
      precedent_availability_snapshot = excluded.precedent_availability_snapshot,
      case_evidence_strength_snapshot = excluded.case_evidence_strength_snapshot,
      case_contains_historical_value_only_content = excluded.case_contains_historical_value_only_content,
      case_personal_information_status = excluded.case_personal_information_status,
      source_object_personal_information_status = excluded.source_object_personal_information_status,
      effective_confidentiality_level_id = excluded.effective_confidentiality_level_id,
      unit_evidence_strength = excluded.unit_evidence_strength,
      search_text = excluded.search_text,
      historical_value_only = excluded.historical_value_only,
      contamination_risk_level = excluded.contamination_risk_level,
      current_authority_disposition = excluded.current_authority_disposition,
      generation_strategy_code = excluded.generation_strategy_code,
      generation_strategy_version = excluded.generation_strategy_version,
      generated_at = excluded.generated_at;

  with lesson_source_meta as (
    select
      hcvl.id as lesson_id,
      private.strictest_knowledge_confidentiality_level_id(
        array_append(array_agg(distinct hcvso.confidentiality_level_id), version_record.confidentiality_level_id)
      ) as effective_confidentiality_level_id,
      private.strictest_personal_information_status(
        array_agg(distinct kso.personal_information_status)
      ) as source_object_personal_information_status
    from public.historical_case_version_lessons hcvl
    join public.historical_case_version_lesson_sources hcvls
      on hcvls.lesson_id = hcvl.id
    join public.historical_case_version_source_objects hcvso
      on hcvso.id = hcvls.historical_case_version_source_object_id
    join public.knowledge_source_objects kso
      on kso.id = hcvso.source_object_id
    where hcvl.historical_case_version_id = p_historical_case_version_id
    group by hcvl.id
  )
  insert into private.historical_case_search_units (
    source_key,
    historical_case_version_id,
    historical_case_id,
    source_layer_role,
    unit_type,
    case_code_snapshot,
    case_title_snapshot,
    precedent_type_snapshot,
    precedent_availability_snapshot,
    case_evidence_strength_snapshot,
    case_contains_historical_value_only_content,
    case_personal_information_status,
    source_object_personal_information_status,
    effective_confidentiality_level_id,
    unit_evidence_strength,
    search_text,
    actor_type,
    lesson_kind,
    historical_value_only,
    contamination_risk_level,
    current_authority_disposition,
    responsibility_id,
    decision_id,
    lesson_id,
    generation_strategy_code,
    generation_strategy_version,
    generated_at
  )
  select
    private.historical_case_search_unit_expected_source_key(
      'lesson',
      version_record.historical_case_version_id,
      null,
      null,
      hcvl.id
    ),
    version_record.historical_case_version_id,
    version_record.historical_case_id,
    'historical_precedent',
    'lesson',
    version_record.case_code,
    version_record.canonical_title,
    version_record.precedent_type,
    version_record.precedent_availability,
    version_record.evidence_strength,
    version_record.contains_historical_value_only_content,
    version_record.personal_information_status,
    lesson_source_meta.source_object_personal_information_status,
    lesson_source_meta.effective_confidentiality_level_id,
    hcvl.evidence_strength,
    hcvl.lesson_statement,
    null,
    hcvl.lesson_kind,
    hcvl.historical_value_only,
    hcvl.contamination_risk_level,
    hcvl.current_authority_disposition,
    null,
    null,
    hcvl.id,
    'phase_6_governed_search_units',
    '6.4A_v1',
    rebuild_started_at
  from public.historical_case_version_lessons hcvl
  join lesson_source_meta
    on lesson_source_meta.lesson_id = hcvl.id
  where hcvl.historical_case_version_id = p_historical_case_version_id
  on conflict (source_key) do update
  set historical_case_version_id = excluded.historical_case_version_id,
      historical_case_id = excluded.historical_case_id,
      case_code_snapshot = excluded.case_code_snapshot,
      case_title_snapshot = excluded.case_title_snapshot,
      precedent_type_snapshot = excluded.precedent_type_snapshot,
      precedent_availability_snapshot = excluded.precedent_availability_snapshot,
      case_evidence_strength_snapshot = excluded.case_evidence_strength_snapshot,
      case_contains_historical_value_only_content = excluded.case_contains_historical_value_only_content,
      case_personal_information_status = excluded.case_personal_information_status,
      source_object_personal_information_status = excluded.source_object_personal_information_status,
      effective_confidentiality_level_id = excluded.effective_confidentiality_level_id,
      unit_evidence_strength = excluded.unit_evidence_strength,
      search_text = excluded.search_text,
      lesson_kind = excluded.lesson_kind,
      historical_value_only = excluded.historical_value_only,
      contamination_risk_level = excluded.contamination_risk_level,
      current_authority_disposition = excluded.current_authority_disposition,
      generation_strategy_code = excluded.generation_strategy_code,
      generation_strategy_version = excluded.generation_strategy_version,
      generated_at = excluded.generated_at;

  with expected_source_keys as (
    select private.historical_case_search_unit_expected_source_key(
      'case_narrative',
      p_historical_case_version_id,
      null,
      null,
      null
    ) as source_key
    union all
    select private.historical_case_search_unit_expected_source_key(
      'responsibility',
      p_historical_case_version_id,
      hcvr.id,
      null,
      null
    )
    from public.historical_case_version_responsibilities hcvr
    where hcvr.historical_case_version_id = p_historical_case_version_id
    union all
    select private.historical_case_search_unit_expected_source_key(
      'decision',
      p_historical_case_version_id,
      null,
      hcvd.id,
      null
    )
    from public.historical_case_version_decisions hcvd
    where hcvd.historical_case_version_id = p_historical_case_version_id
    union all
    select private.historical_case_search_unit_expected_source_key(
      'lesson',
      p_historical_case_version_id,
      null,
      null,
      hcvl.id
    )
    from public.historical_case_version_lessons hcvl
    where hcvl.historical_case_version_id = p_historical_case_version_id
  )
  delete from private.historical_case_search_units hcsu
  where hcsu.historical_case_version_id = p_historical_case_version_id
    and not exists (
      select 1
      from expected_source_keys esk
      where esk.source_key = hcsu.source_key
    );

  delete from private.historical_case_unit_sources hcus
  using private.historical_case_search_units hcsu
  where hcsu.id = hcus.historical_case_search_unit_id
    and hcsu.historical_case_version_id = p_historical_case_version_id;

  insert into private.historical_case_unit_sources (
    historical_case_search_unit_id,
    historical_case_version_source_object_id,
    responsibility_source_id,
    decision_source_id,
    lesson_source_id,
    is_primary_trace
  )
  select
    hcsu.id,
    hcvso.id,
    null,
    null,
    null,
    row_number() over (partition by hcsu.id order by hcvso.id) = 1
  from private.historical_case_search_units hcsu
  join public.historical_case_version_source_objects hcvso
    on hcvso.historical_case_version_id = hcsu.historical_case_version_id
  where hcsu.historical_case_version_id = p_historical_case_version_id
    and hcsu.unit_type = 'case_narrative';

  insert into private.historical_case_unit_sources (
    historical_case_search_unit_id,
    historical_case_version_source_object_id,
    responsibility_source_id,
    decision_source_id,
    lesson_source_id,
    is_primary_trace
  )
  select
    hcsu.id,
    hcvrs.historical_case_version_source_object_id,
    hcvrs.id,
    null,
    null,
    row_number() over (partition by hcsu.id order by hcvrs.id) = 1
  from private.historical_case_search_units hcsu
  join public.historical_case_version_responsibility_sources hcvrs
    on hcvrs.responsibility_id = hcsu.responsibility_id
  where hcsu.historical_case_version_id = p_historical_case_version_id
    and hcsu.unit_type = 'responsibility';

  insert into private.historical_case_unit_sources (
    historical_case_search_unit_id,
    historical_case_version_source_object_id,
    responsibility_source_id,
    decision_source_id,
    lesson_source_id,
    is_primary_trace
  )
  select
    hcsu.id,
    hcvds.historical_case_version_source_object_id,
    null,
    hcvds.id,
    null,
    row_number() over (partition by hcsu.id order by hcvds.id) = 1
  from private.historical_case_search_units hcsu
  join public.historical_case_version_decision_sources hcvds
    on hcvds.decision_id = hcsu.decision_id
  where hcsu.historical_case_version_id = p_historical_case_version_id
    and hcsu.unit_type = 'decision';

  insert into private.historical_case_unit_sources (
    historical_case_search_unit_id,
    historical_case_version_source_object_id,
    responsibility_source_id,
    decision_source_id,
    lesson_source_id,
    is_primary_trace
  )
  select
    hcsu.id,
    hcvls.historical_case_version_source_object_id,
    null,
    null,
    hcvls.id,
    row_number() over (partition by hcsu.id order by hcvls.id) = 1
  from private.historical_case_search_units hcsu
  join public.historical_case_version_lesson_sources hcvls
    on hcvls.lesson_id = hcsu.lesson_id
  where hcsu.historical_case_version_id = p_historical_case_version_id
    and hcsu.unit_type = 'lesson';

  select count(*)
  into generated_unit_count
  from private.historical_case_search_units hcsu
  where hcsu.historical_case_version_id = p_historical_case_version_id;

  update private.historical_case_version_processing
  set search_unit_generation_status = 'succeeded',
      last_succeeded_at = rebuild_started_at,
      last_error_code = null,
      last_error_message = null
  where historical_case_version_id = p_historical_case_version_id;

  return generated_unit_count;
exception
  when others then
    update private.historical_case_version_processing
    set search_unit_generation_status = 'failed',
        retry_count = retry_count + 1,
        last_error_code = sqlstate,
        last_error_message = sqlerrm
    where historical_case_version_id = p_historical_case_version_id;
    raise;
end;
$$;

create or replace function private.rebuild_current_historical_case_search_units()
returns bigint
language plpgsql
as $$
declare
  target_version record;
  generated_unit_total bigint := 0;
begin
  for target_version in
    select hcv.id
    from public.historical_case_versions hcv
    where hcv.governance_status = 'active'
      and hcv.precedent_availability in ('active', 'limited')
    order by hcv.historical_case_id, hcv.version_number
  loop
    generated_unit_total :=
      generated_unit_total + private.rebuild_historical_case_search_units_for_version(target_version.id);
  end loop;

  return generated_unit_total;
end;
$$;

create or replace view private.current_historical_case_search_units as
select
  hcsu.id as search_unit_id,
  hcsu.source_key,
  hcsu.historical_case_version_id,
  hcsu.historical_case_id,
  hcsu.case_code_snapshot as case_code,
  hcsu.case_title_snapshot as case_title,
  hcsu.source_layer_role,
  hcsu.unit_type,
  hcsu.precedent_type_snapshot as precedent_type,
  hcsu.precedent_availability_snapshot as precedent_availability,
  hcsu.case_evidence_strength_snapshot as case_evidence_strength,
  hcsu.unit_evidence_strength,
  hcsu.search_text,
  hcsu.actor_type,
  hcsu.lesson_kind,
  hcsu.historical_value_only,
  hcsu.contamination_risk_level,
  hcsu.current_authority_disposition,
  hcsu.case_contains_historical_value_only_content,
  hcsu.case_personal_information_status,
  hcsu.source_object_personal_information_status,
  hcsu.effective_confidentiality_level_id,
  kcl.level_code as effective_confidentiality_level_code,
  primary_lineage.historical_case_version_source_object_id as primary_historical_case_version_source_object_id,
  primary_lineage.primary_source_object_id,
  primary_lineage.primary_source_locator,
  lineage_counts.source_link_count,
  hcsu.responsibility_id,
  hcsu.decision_id,
  hcsu.lesson_id,
  hcsu.generation_strategy_code,
  hcsu.generation_strategy_version,
  hcsu.generated_at,
  hcsu.created_at,
  hcsu.updated_at
from private.historical_case_search_units hcsu
join public.historical_case_versions hcv
  on hcv.id = hcsu.historical_case_version_id
join public.knowledge_confidentiality_levels kcl
  on kcl.id = hcsu.effective_confidentiality_level_id
join lateral (
  select
    hcus.historical_case_version_source_object_id,
    hcvso.source_object_id as primary_source_object_id,
    hcvso.source_locator as primary_source_locator
  from private.historical_case_unit_sources hcus
  join public.historical_case_version_source_objects hcvso
    on hcvso.id = hcus.historical_case_version_source_object_id
  where hcus.historical_case_search_unit_id = hcsu.id
  order by hcus.is_primary_trace desc, hcus.id
  limit 1
) primary_lineage on true
join lateral (
  select count(*)::bigint as source_link_count
  from private.historical_case_unit_sources hcus_count
  where hcus_count.historical_case_search_unit_id = hcsu.id
) lineage_counts on true
where hcv.governance_status = 'active'
  and hcv.precedent_availability in ('active', 'limited');

drop trigger if exists trg_historical_case_version_processing_touch_updated_at on private.historical_case_version_processing;
create trigger trg_historical_case_version_processing_touch_updated_at
before update on private.historical_case_version_processing
for each row
execute function private.touch_updated_at();

drop trigger if exists trg_historical_case_search_units_touch_updated_at on private.historical_case_search_units;
create trigger trg_historical_case_search_units_touch_updated_at
before update on private.historical_case_search_units
for each row
execute function private.touch_updated_at();

drop trigger if exists trg_validate_historical_case_search_unit on private.historical_case_search_units;
create trigger trg_validate_historical_case_search_unit
before insert or update of
  source_key,
  historical_case_version_id,
  historical_case_id,
  unit_type,
  responsibility_id,
  decision_id,
  lesson_id
on private.historical_case_search_units
for each row
execute function private.validate_historical_case_search_unit();

drop trigger if exists trg_validate_historical_case_unit_source on private.historical_case_unit_sources;
create trigger trg_validate_historical_case_unit_source
before insert or update of
  historical_case_search_unit_id,
  historical_case_version_source_object_id,
  responsibility_source_id,
  decision_source_id,
  lesson_source_id
on private.historical_case_unit_sources
for each row
execute function private.validate_historical_case_unit_source();

drop trigger if exists trg_historical_case_search_units_require_sources on private.historical_case_search_units;
create constraint trigger trg_historical_case_search_units_require_sources
after insert or update of source_key on private.historical_case_search_units
deferrable initially deferred
for each row
execute function private.enforce_historical_case_search_unit_has_sources_from_unit();

drop trigger if exists trg_historical_case_unit_sources_require_units on private.historical_case_unit_sources;
create constraint trigger trg_historical_case_unit_sources_require_units
after update of historical_case_search_unit_id or delete on private.historical_case_unit_sources
deferrable initially deferred
for each row
execute function private.enforce_historical_case_search_unit_has_sources_from_unit_source();

alter table private.historical_case_version_processing enable row level security;
alter table private.historical_case_search_units enable row level security;
alter table private.historical_case_unit_sources enable row level security;

revoke all on table private.historical_case_version_processing from public, anon, authenticated, service_role;
revoke all on table private.historical_case_search_units from public, anon, authenticated, service_role;
revoke all on table private.historical_case_unit_sources from public, anon, authenticated, service_role;
revoke all on table private.current_historical_case_search_units from public, anon, authenticated, service_role;

revoke execute on function private.rebuild_historical_case_search_units_for_version(bigint)
  from public, anon, authenticated, service_role;
revoke execute on function private.rebuild_current_historical_case_search_units()
  from public, anon, authenticated, service_role;
