create table if not exists public.logical_rules (
  rule_code text primary key,
  rule_domain text not null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint logical_rules_rule_code_nonempty check (btrim(rule_code) <> ''),
  constraint logical_rules_rule_domain_nonempty check (btrim(rule_domain) <> '')
);

create or replace function private.validate_rule_catalogue_logical_rule_domain()
returns trigger
language plpgsql
as $$
declare
  logical_rule_domain text;
begin
  select lr.rule_domain
  into logical_rule_domain
  from public.logical_rules lr
  where lr.rule_code = new.rule_code;

  if logical_rule_domain is not null and logical_rule_domain <> new.rule_domain then
    raise exception 'rule_code % must use logical rule domain %, not %', new.rule_code, logical_rule_domain, new.rule_domain
      using errcode = '23514';
  end if;

  return new;
end;
$$;

do $$
declare
  inconsistent_rule record;
begin
  select
    rc.rule_code,
    string_agg(distinct rc.rule_domain, ', ' order by rc.rule_domain) as domains
  into inconsistent_rule
  from public.rule_catalogue rc
  group by rc.rule_code
  having count(distinct rc.rule_domain) > 1
  limit 1;

  if found then
    raise exception 'logical_rules backfill blocked: rule_code % maps to multiple rule_domain values (%).',
      inconsistent_rule.rule_code,
      inconsistent_rule.domains
      using errcode = '23514';
  end if;
end;
$$;

insert into public.logical_rules (
  rule_code,
  rule_domain
)
select
  rc.rule_code,
  min(rc.rule_domain) as rule_domain
from public.rule_catalogue rc
group by rc.rule_code
on conflict (rule_code) do update
set rule_domain = excluded.rule_domain;

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'rule_catalogue_rule_code_fkey'
      and conrelid = 'public.rule_catalogue'::regclass
  ) then
    alter table public.rule_catalogue
      add constraint rule_catalogue_rule_code_fkey
      foreign key (rule_code)
      references public.logical_rules(rule_code)
      on update restrict
      on delete restrict;
  end if;
end;
$$;

drop trigger if exists trg_logical_rules_touch_updated_at on public.logical_rules;
create trigger trg_logical_rules_touch_updated_at
before update on public.logical_rules
for each row
execute function private.touch_updated_at();

drop trigger if exists trg_validate_rule_catalogue_logical_rule_domain on public.rule_catalogue;
create trigger trg_validate_rule_catalogue_logical_rule_domain
before insert or update of rule_code, rule_domain on public.rule_catalogue
for each row
execute function private.validate_rule_catalogue_logical_rule_domain();

create table if not exists public.knowledge_categories (
  id bigint generated by default as identity primary key,
  category_code text not null unique,
  display_name text not null,
  description text not null,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint knowledge_categories_code_nonempty check (btrim(category_code) <> ''),
  constraint knowledge_categories_display_name_nonempty check (btrim(display_name) <> ''),
  constraint knowledge_categories_description_nonempty check (btrim(description) <> ''),
  constraint knowledge_categories_sort_order_nonnegative check (sort_order >= 0)
);

create table if not exists public.knowledge_audiences (
  id bigint generated by default as identity primary key,
  audience_code text not null unique,
  display_name text not null,
  description text not null,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint knowledge_audiences_code_nonempty check (btrim(audience_code) <> ''),
  constraint knowledge_audiences_display_name_nonempty check (btrim(display_name) <> ''),
  constraint knowledge_audiences_description_nonempty check (btrim(description) <> ''),
  constraint knowledge_audiences_sort_order_nonnegative check (sort_order >= 0)
);

create table if not exists public.knowledge_confidentiality_levels (
  id bigint generated by default as identity primary key,
  level_code text not null unique,
  display_name text not null,
  description text not null,
  sort_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint knowledge_confidentiality_levels_code_nonempty check (btrim(level_code) <> ''),
  constraint knowledge_confidentiality_levels_display_name_nonempty check (btrim(display_name) <> ''),
  constraint knowledge_confidentiality_levels_description_nonempty check (btrim(description) <> ''),
  constraint knowledge_confidentiality_levels_sort_order_nonnegative check (sort_order >= 0)
);

create table if not exists public.knowledge_documents (
  id bigint generated by default as identity primary key,
  document_code text not null unique,
  canonical_title text not null,
  primary_category_id bigint not null references public.knowledge_categories(id) on delete restrict,
  default_owner_role text,
  notes text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint knowledge_documents_code_nonempty check (btrim(document_code) <> ''),
  constraint knowledge_documents_title_nonempty check (btrim(canonical_title) <> ''),
  constraint knowledge_documents_default_owner_role_nonempty
    check (default_owner_role is null or btrim(default_owner_role) <> '')
);

create table if not exists public.knowledge_document_versions (
  id bigint generated by default as identity primary key,
  document_id bigint not null references public.knowledge_documents(id) on delete restrict,
  version_number integer not null,
  source_version_label text,
  governance_status text not null,
  authority_classification text not null,
  lifecycle_note text,
  confidentiality_level_id bigint not null references public.knowledge_confidentiality_levels(id) on delete restrict,
  effective_from date,
  effective_until date,
  supersedes_version_id bigint references public.knowledge_document_versions(id) on delete restrict,
  approved_at timestamptz,
  approval_notes text,
  last_reviewed_at timestamptz,
  last_review_notes text,
  version_owner_role text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint knowledge_document_versions_version_positive check (version_number > 0),
  constraint knowledge_document_versions_governance_status_check
    check (governance_status in ('draft', 'approved', 'active', 'superseded', 'retired')),
  constraint knowledge_document_versions_authority_classification_check
    check (authority_classification in ('authoritative', 'guidance', 'reference_only', 'unverified')),
  constraint knowledge_document_versions_date_range_check
    check (effective_until is null or effective_from is null or effective_until >= effective_from),
  constraint knowledge_document_versions_doc_version_unique unique (document_id, version_number),
  constraint knowledge_document_versions_source_version_label_nonempty
    check (source_version_label is null or btrim(source_version_label) <> ''),
  constraint knowledge_document_versions_version_owner_role_nonempty
    check (version_owner_role is null or btrim(version_owner_role) <> '')
);

create unique index if not exists knowledge_document_versions_one_active_version_per_doc_idx
  on public.knowledge_document_versions (document_id)
  where governance_status = 'active';

create table if not exists public.knowledge_document_corpus_states (
  id bigint generated by default as identity primary key,
  document_id bigint not null references public.knowledge_documents(id) on delete cascade,
  corpus_status text not null,
  is_current boolean not null default false,
  decided_at timestamptz,
  decision_note text,
  decided_by_role text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint knowledge_document_corpus_states_status_check
    check (corpus_status in ('include', 'defer', 'exclude')),
  constraint knowledge_document_corpus_states_decided_by_role_nonempty
    check (decided_by_role is null or btrim(decided_by_role) <> '')
);

create unique index if not exists knowledge_document_corpus_states_one_current_per_doc_idx
  on public.knowledge_document_corpus_states (document_id)
  where is_current;

create table if not exists public.knowledge_document_version_audiences (
  id bigint generated by default as identity primary key,
  document_version_id bigint not null references public.knowledge_document_versions(id) on delete cascade,
  audience_id bigint not null references public.knowledge_audiences(id) on delete restrict,
  created_at timestamptz not null default timezone('utc', now()),
  constraint knowledge_document_version_audiences_unique unique (document_version_id, audience_id)
);

create table if not exists public.knowledge_document_version_rental_types (
  id bigint generated by default as identity primary key,
  document_version_id bigint not null references public.knowledge_document_versions(id) on delete cascade,
  rental_type_id bigint not null references public.rental_types(id) on delete restrict,
  created_at timestamptz not null default timezone('utc', now()),
  constraint knowledge_document_version_rental_types_unique unique (document_version_id, rental_type_id)
);

create or replace function private.validate_knowledge_document_version_supersession()
returns trigger
language plpgsql
as $$
declare
  superseded_document_id bigint;
begin
  if new.supersedes_version_id is null then
    return new;
  end if;

  if new.id is not null and new.supersedes_version_id = new.id then
    raise exception 'knowledge document version cannot supersede itself'
      using errcode = '23514';
  end if;

  select kdv.document_id
  into superseded_document_id
  from public.knowledge_document_versions kdv
  where kdv.id = new.supersedes_version_id;

  if superseded_document_id is not null and superseded_document_id <> new.document_id then
    raise exception 'knowledge document version can only supersede a prior version from the same document'
      using errcode = '23514';
  end if;

  return new;
end;
$$;

drop trigger if exists trg_knowledge_categories_touch_updated_at on public.knowledge_categories;
create trigger trg_knowledge_categories_touch_updated_at
before update on public.knowledge_categories
for each row
execute function private.touch_updated_at();

drop trigger if exists trg_knowledge_audiences_touch_updated_at on public.knowledge_audiences;
create trigger trg_knowledge_audiences_touch_updated_at
before update on public.knowledge_audiences
for each row
execute function private.touch_updated_at();

drop trigger if exists trg_knowledge_confidentiality_levels_touch_updated_at on public.knowledge_confidentiality_levels;
create trigger trg_knowledge_confidentiality_levels_touch_updated_at
before update on public.knowledge_confidentiality_levels
for each row
execute function private.touch_updated_at();

drop trigger if exists trg_knowledge_documents_touch_updated_at on public.knowledge_documents;
create trigger trg_knowledge_documents_touch_updated_at
before update on public.knowledge_documents
for each row
execute function private.touch_updated_at();

drop trigger if exists trg_knowledge_document_versions_touch_updated_at on public.knowledge_document_versions;
create trigger trg_knowledge_document_versions_touch_updated_at
before update on public.knowledge_document_versions
for each row
execute function private.touch_updated_at();

drop trigger if exists trg_validate_knowledge_document_version_supersession on public.knowledge_document_versions;
create trigger trg_validate_knowledge_document_version_supersession
before insert or update on public.knowledge_document_versions
for each row
execute function private.validate_knowledge_document_version_supersession();

drop trigger if exists trg_knowledge_document_corpus_states_touch_updated_at on public.knowledge_document_corpus_states;
create trigger trg_knowledge_document_corpus_states_touch_updated_at
before update on public.knowledge_document_corpus_states
for each row
execute function private.touch_updated_at();

revoke all on table public.logical_rules from anon, authenticated;
revoke all on table public.knowledge_categories from anon, authenticated;
revoke all on table public.knowledge_audiences from anon, authenticated;
revoke all on table public.knowledge_confidentiality_levels from anon, authenticated;
revoke all on table public.knowledge_documents from anon, authenticated;
revoke all on table public.knowledge_document_versions from anon, authenticated;
revoke all on table public.knowledge_document_corpus_states from anon, authenticated;
revoke all on table public.knowledge_document_version_audiences from anon, authenticated;
revoke all on table public.knowledge_document_version_rental_types from anon, authenticated;
