create table if not exists public.inquiry_response_draft_revisions (
  id bigint generated by default as identity primary key,
  inquiry_response_draft_revision_uuid uuid not null default gen_random_uuid(),
  rental_case_id bigint not null references public.rental_cases(id) on delete cascade,
  workflow_action_id bigint not null references public.workflow_actions(id) on delete cascade,
  conversation_key text not null,
  source_case_revision integer not null check (source_case_revision >= 0),
  draft_status text not null check (
    draft_status in (
      'draft',
      'needs_approval',
      'approved',
      'rejected',
      'simulated_sent',
      'send_failed',
      'send_outcome_uncertain'
    )
  ),
  draft_source text not null check (
    draft_source in ('generated', 'regenerated', 'human_edited')
  ),
  is_current boolean not null default true,
  approval_request_id bigint references public.rental_case_approval_requests(id) on delete set null,
  subject text not null,
  salutation text not null,
  intro_text text not null,
  question_lines jsonb not null default '[]'::jsonb,
  closing_text text not null,
  signoff_text text not null,
  body_text text not null,
  context_payload jsonb not null default '{}'::jsonb,
  context_hash text not null,
  content_hash text not null,
  recipient_email text not null,
  recipient_label text,
  sender_email text not null,
  sender_label text not null,
  sender_display_name text,
  supersedes_draft_revision_id bigint references public.inquiry_response_draft_revisions(id) on delete set null,
  delivered_at timestamptz,
  delivery_external_reference text,
  delivery_failure_code text,
  approved_at timestamptz,
  rejected_at timestamptz,
  created_by_reference text not null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  check (btrim(conversation_key) <> ''),
  check (btrim(subject) <> ''),
  check (btrim(body_text) <> ''),
  check (jsonb_typeof(question_lines) = 'array'),
  check (jsonb_array_length(question_lines) > 0),
  check (jsonb_typeof(context_payload) = 'object')
);

create unique index if not exists uq_workflow_actions_id_rental_case
  on public.workflow_actions (id, rental_case_id);

create unique index if not exists uq_approval_requests_id_rental_case
  on public.rental_case_approval_requests (id, rental_case_id);

create index if not exists idx_inquiry_response_drafts_case_created
  on public.inquiry_response_draft_revisions (rental_case_id, created_at desc, id desc);

create index if not exists idx_inquiry_response_drafts_workflow_action
  on public.inquiry_response_draft_revisions (workflow_action_id, created_at desc, id desc);

create index if not exists idx_inquiry_response_drafts_conversation
  on public.inquiry_response_draft_revisions (rental_case_id, conversation_key, created_at desc, id desc);

create unique index if not exists uq_inquiry_response_drafts_current_conversation
  on public.inquiry_response_draft_revisions (rental_case_id, conversation_key)
  where is_current = true;

create unique index if not exists uq_inquiry_response_drafts_current_approval
  on public.inquiry_response_draft_revisions (approval_request_id)
  where approval_request_id is not null;

create or replace function private.guard_inquiry_response_draft_revision_write()
returns trigger
language plpgsql
as $$
declare
  v_action_rental_case_id bigint;
  v_superseded_rental_case_id bigint;
  v_superseded_conversation_key text;
  v_approval_rental_case_id bigint;
  v_approval_target_type text;
  v_approval_target_id bigint;
  v_approval_target_reference text;
begin
  select workflow_action.rental_case_id
  into v_action_rental_case_id
  from public.workflow_actions as workflow_action
  where workflow_action.id = new.workflow_action_id;

  if v_action_rental_case_id is null then
    raise exception 'workflow action % does not exist', new.workflow_action_id
      using errcode = '23503';
  end if;

  if v_action_rental_case_id <> new.rental_case_id then
    raise exception 'workflow action % belongs to rental_case_id %, not %',
      new.workflow_action_id,
      v_action_rental_case_id,
      new.rental_case_id
      using errcode = '23514';
  end if;

  if new.supersedes_draft_revision_id is not null then
    select draft.rental_case_id, draft.conversation_key
    into v_superseded_rental_case_id, v_superseded_conversation_key
    from public.inquiry_response_draft_revisions as draft
    where draft.id = new.supersedes_draft_revision_id;

    if v_superseded_rental_case_id is null then
      raise exception 'superseded draft revision % does not exist', new.supersedes_draft_revision_id
        using errcode = '23503';
    end if;

    if v_superseded_rental_case_id <> new.rental_case_id then
      raise exception 'superseded draft revision % belongs to rental_case_id %, not %',
        new.supersedes_draft_revision_id,
        v_superseded_rental_case_id,
        new.rental_case_id
        using errcode = '23514';
    end if;

    if v_superseded_conversation_key <> new.conversation_key then
      raise exception 'superseded draft revision % must remain in conversation %',
        new.supersedes_draft_revision_id,
        new.conversation_key
        using errcode = '23514';
    end if;
  end if;

  if new.approval_request_id is not null then
    select approval.rental_case_id,
           approval.target_entity_type,
           approval.target_entity_id,
           approval.target_entity_reference
    into v_approval_rental_case_id,
         v_approval_target_type,
         v_approval_target_id,
         v_approval_target_reference
    from public.rental_case_approval_requests as approval
    where approval.id = new.approval_request_id;

    if v_approval_rental_case_id is null then
      raise exception 'approval request % does not exist', new.approval_request_id
        using errcode = '23503';
    end if;

    if v_approval_rental_case_id <> new.rental_case_id then
      raise exception 'approval request % belongs to rental_case_id %, not %',
        new.approval_request_id,
        v_approval_rental_case_id,
        new.rental_case_id
        using errcode = '23514';
    end if;

    if v_approval_target_type <> 'workflow_action' then
      raise exception 'approval request % must target workflow_action, found %',
        new.approval_request_id,
        v_approval_target_type
        using errcode = '23514';
    end if;

    if v_approval_target_id is distinct from new.workflow_action_id then
      raise exception 'approval request % targets workflow_action %, not %',
        new.approval_request_id,
        v_approval_target_id,
        new.workflow_action_id
        using errcode = '23514';
    end if;

    if coalesce(v_approval_target_reference, '') <> format(
      'workflow_action:%s:draft_revision:%s',
      new.workflow_action_id,
      new.id
    ) then
      raise exception 'approval request % must reference workflow_action:%s:draft_revision:%s, found %',
        new.approval_request_id,
        new.workflow_action_id,
        new.id,
        coalesce(v_approval_target_reference, '<null>')
        using errcode = '23514';
    end if;
  end if;

  if tg_op = 'UPDATE' then
    if new.rental_case_id <> old.rental_case_id
      or new.workflow_action_id <> old.workflow_action_id
      or new.conversation_key <> old.conversation_key
      or new.source_case_revision <> old.source_case_revision
      or new.draft_source <> old.draft_source
      or new.subject <> old.subject
      or new.salutation <> old.salutation
      or new.intro_text <> old.intro_text
      or new.question_lines <> old.question_lines
      or new.closing_text <> old.closing_text
      or new.signoff_text <> old.signoff_text
      or new.body_text <> old.body_text
      or new.context_payload <> old.context_payload
      or new.context_hash <> old.context_hash
      or new.content_hash <> old.content_hash
      or new.recipient_email <> old.recipient_email
      or coalesce(new.recipient_label, '') <> coalesce(old.recipient_label, '')
      or new.sender_email <> old.sender_email
      or new.sender_label <> old.sender_label
      or coalesce(new.sender_display_name, '') <> coalesce(old.sender_display_name, '')
      or coalesce(new.supersedes_draft_revision_id, 0) <> coalesce(old.supersedes_draft_revision_id, 0)
      or new.created_by_reference <> old.created_by_reference
      or new.created_at <> old.created_at
    then
      raise exception 'inquiry_response_draft_revisions are immutable; create a new revision instead of mutating content'
        using errcode = '23514';
    end if;
  end if;

  return new;
end;
$$;

drop trigger if exists trg_guard_inquiry_response_draft_revision_write
  on public.inquiry_response_draft_revisions;

create trigger trg_guard_inquiry_response_draft_revision_write
before insert or update on public.inquiry_response_draft_revisions
for each row
execute function private.guard_inquiry_response_draft_revision_write();
