create table if not exists private.knowledge_document_version_processing (
  document_version_id bigint primary key references public.knowledge_document_versions(id) on delete cascade,
  extraction_status text not null default 'not_started',
  chunking_status text not null default 'not_started',
  indexing_status text not null default 'not_applicable',
  last_attempted_at timestamptz,
  last_succeeded_at timestamptz,
  retry_count integer not null default 0,
  last_error_code text,
  last_error_message text,
  updated_at timestamptz not null default timezone('utc', now()),
  constraint knowledge_document_version_processing_extraction_status_check
    check (extraction_status in ('not_started', 'ready', 'in_progress', 'succeeded', 'failed', 'not_applicable')),
  constraint knowledge_document_version_processing_chunking_status_check
    check (chunking_status in ('not_started', 'ready', 'in_progress', 'succeeded', 'failed', 'not_applicable')),
  constraint knowledge_document_version_processing_indexing_status_check
    check (indexing_status in ('not_started', 'ready', 'in_progress', 'succeeded', 'failed', 'not_applicable')),
  constraint knowledge_document_version_processing_retry_count_nonnegative
    check (retry_count >= 0),
  constraint knowledge_document_version_processing_last_error_code_nonempty
    check (last_error_code is null or btrim(last_error_code) <> ''),
  constraint kdvp_last_error_message_nonempty
    check (last_error_message is null or btrim(last_error_message) <> ''),
  constraint knowledge_document_version_processing_success_after_attempt
    check (last_succeeded_at is null or last_attempted_at is null or last_succeeded_at >= last_attempted_at)
);

create table if not exists private.knowledge_chunk_sets (
  id bigint generated by default as identity primary key,
  document_version_id bigint not null references public.knowledge_document_versions(id) on delete cascade,
  chunking_strategy_code text not null,
  chunking_strategy_version text not null,
  parser_version text not null,
  generation_status text not null,
  generated_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  constraint knowledge_chunk_sets_strategy_code_nonempty
    check (btrim(chunking_strategy_code) <> ''),
  constraint knowledge_chunk_sets_strategy_version_nonempty
    check (btrim(chunking_strategy_version) <> ''),
  constraint knowledge_chunk_sets_parser_version_nonempty
    check (btrim(parser_version) <> ''),
  constraint knowledge_chunk_sets_generation_status_check
    check (generation_status in ('pending', 'current', 'superseded', 'failed'))
);

create unique index if not exists knowledge_chunk_sets_one_current_per_doc_version_idx
  on private.knowledge_chunk_sets (document_version_id)
  where generation_status = 'current';

create index if not exists knowledge_chunk_sets_document_version_idx
  on private.knowledge_chunk_sets (document_version_id, created_at desc);

create table if not exists private.knowledge_chunk_set_sources (
  id bigint generated by default as identity primary key,
  chunk_set_id bigint not null references private.knowledge_chunk_sets(id) on delete cascade,
  document_version_source_object_id bigint not null references public.knowledge_document_version_source_objects(id) on delete restrict,
  source_usage_role text not null,
  created_at timestamptz not null default timezone('utc', now()),
  constraint knowledge_chunk_set_sources_source_usage_role_check
    check (source_usage_role in ('primary_extraction', 'supporting_extraction')),
  constraint knowledge_chunk_set_sources_unique
    unique (chunk_set_id, document_version_source_object_id)
);

create unique index if not exists knowledge_chunk_set_sources_one_primary_idx
  on private.knowledge_chunk_set_sources (chunk_set_id)
  where source_usage_role = 'primary_extraction';

create index if not exists knowledge_chunk_set_sources_source_object_idx
  on private.knowledge_chunk_set_sources (document_version_source_object_id);

create table if not exists private.knowledge_chunks (
  id bigint generated by default as identity primary key,
  chunk_set_id bigint not null references private.knowledge_chunk_sets(id) on delete cascade,
  chunk_ordinal integer not null,
  section_heading text,
  heading_path text,
  question_label text,
  document_title_snapshot text not null,
  body_text text not null,
  content_hash text not null,
  token_count integer,
  created_at timestamptz not null default timezone('utc', now()),
  constraint knowledge_chunks_chunk_ordinal_positive
    check (chunk_ordinal > 0),
  constraint knowledge_chunks_section_heading_nonempty
    check (section_heading is null or btrim(section_heading) <> ''),
  constraint knowledge_chunks_heading_path_nonempty
    check (heading_path is null or btrim(heading_path) <> ''),
  constraint knowledge_chunks_question_label_nonempty
    check (question_label is null or btrim(question_label) <> ''),
  constraint knowledge_chunks_document_title_snapshot_nonempty
    check (btrim(document_title_snapshot) <> ''),
  constraint knowledge_chunks_body_text_nonempty
    check (btrim(body_text) <> ''),
  constraint knowledge_chunks_content_hash_nonempty
    check (btrim(content_hash) <> ''),
  constraint knowledge_chunks_token_count_positive
    check (token_count is null or token_count > 0),
  constraint knowledge_chunks_unique_ordinal
    unique (chunk_set_id, chunk_ordinal),
  constraint knowledge_chunks_unique_content_hash
    unique (chunk_set_id, content_hash)
);

create index if not exists knowledge_chunks_chunk_set_idx
  on private.knowledge_chunks (chunk_set_id, chunk_ordinal);

create table if not exists private.knowledge_chunk_sources (
  id bigint generated by default as identity primary key,
  chunk_id bigint not null references private.knowledge_chunks(id) on delete cascade,
  document_version_source_object_id bigint not null references public.knowledge_document_version_source_objects(id) on delete restrict,
  source_locator text not null,
  is_primary_trace boolean not null default false,
  created_at timestamptz not null default timezone('utc', now()),
  constraint knowledge_chunk_sources_source_locator_nonempty
    check (btrim(source_locator) <> ''),
  constraint knowledge_chunk_sources_unique
    unique (chunk_id, document_version_source_object_id, source_locator)
);

create unique index if not exists knowledge_chunk_sources_one_primary_idx
  on private.knowledge_chunk_sources (chunk_id)
  where is_primary_trace;

create index if not exists knowledge_chunk_sources_source_object_idx
  on private.knowledge_chunk_sources (document_version_source_object_id);

create or replace function private.validate_knowledge_chunk_set_source()
returns trigger
language plpgsql
as $$
declare
  chunk_set_document_version_id bigint;
  linked_document_version_id bigint;
  linked_source_disposition text;
begin
  select kcs.document_version_id
  into chunk_set_document_version_id
  from private.knowledge_chunk_sets kcs
  where kcs.id = new.chunk_set_id;

  select
    kdvso.document_version_id,
    kdvso.source_usage_disposition
  into linked_document_version_id, linked_source_disposition
  from public.knowledge_document_version_source_objects kdvso
  where kdvso.id = new.document_version_source_object_id;

  if chunk_set_document_version_id is null or linked_document_version_id is null then
    return new;
  end if;

  if linked_document_version_id <> chunk_set_document_version_id then
    raise exception 'chunk set % belongs to document version %, but source link % belongs to document version %',
      new.chunk_set_id,
      chunk_set_document_version_id,
      new.document_version_source_object_id,
      linked_document_version_id
      using errcode = '23514';
  end if;

  if linked_source_disposition = 'excluded_from_extraction' then
    raise exception 'source link % is excluded from extraction and cannot be used for chunk generation',
      new.document_version_source_object_id
      using errcode = '23514';
  end if;

  if new.source_usage_role = 'primary_extraction'
     and linked_source_disposition <> 'eligible_for_extraction' then
    raise exception 'primary extraction source link % must be eligible_for_extraction, not %',
      new.document_version_source_object_id,
      linked_source_disposition
      using errcode = '23514';
  end if;

  return new;
end;
$$;

create or replace function private.assert_current_chunk_set_has_sources(p_chunk_set_id bigint)
returns void
language plpgsql
as $$
declare
  current_status text;
  source_count bigint;
begin
  select kcs.generation_status
  into current_status
  from private.knowledge_chunk_sets kcs
  where kcs.id = p_chunk_set_id;

  if current_status is distinct from 'current' then
    return;
  end if;

  select count(*)
  into source_count
  from private.knowledge_chunk_set_sources kcss
  where kcss.chunk_set_id = p_chunk_set_id;

  if source_count = 0 then
    raise exception 'current chunk set % must have at least one extraction source',
      p_chunk_set_id
      using errcode = '23514';
  end if;
end;
$$;

create or replace function private.enforce_current_chunk_set_has_sources_from_chunk_set()
returns trigger
language plpgsql
as $$
begin
  perform private.assert_current_chunk_set_has_sources(new.id);
  return null;
end;
$$;

create or replace function private.enforce_current_chunk_set_has_sources_from_chunk_set_source()
returns trigger
language plpgsql
as $$
begin
  if tg_op in ('DELETE', 'UPDATE') then
    perform private.assert_current_chunk_set_has_sources(old.chunk_set_id);
  end if;

  if tg_op = 'UPDATE' then
    perform private.assert_current_chunk_set_has_sources(new.chunk_set_id);
  end if;

  return null;
end;
$$;

create or replace function private.validate_knowledge_chunk_source()
returns trigger
language plpgsql
as $$
declare
  parent_chunk_set_id bigint;
  chunk_document_version_id bigint;
  linked_document_version_id bigint;
  has_chunk_set_source boolean;
begin
  select
    kc.chunk_set_id,
    kcs.document_version_id
  into parent_chunk_set_id, chunk_document_version_id
  from private.knowledge_chunks kc
  join private.knowledge_chunk_sets kcs
    on kcs.id = kc.chunk_set_id
  where kc.id = new.chunk_id;

  select kdvso.document_version_id
  into linked_document_version_id
  from public.knowledge_document_version_source_objects kdvso
  where kdvso.id = new.document_version_source_object_id;

  if chunk_document_version_id is null or linked_document_version_id is null then
    return new;
  end if;

  if linked_document_version_id <> chunk_document_version_id then
    raise exception 'chunk % belongs to document version %, but source link % belongs to document version %',
      new.chunk_id,
      chunk_document_version_id,
      new.document_version_source_object_id,
      linked_document_version_id
      using errcode = '23514';
  end if;

  select exists (
    select 1
    from private.knowledge_chunk_set_sources kcss
    where kcss.chunk_set_id = parent_chunk_set_id
      and kcss.document_version_source_object_id = new.document_version_source_object_id
  )
  into has_chunk_set_source;

  if not has_chunk_set_source then
    raise exception 'chunk % cannot trace to source link % because the parent chunk set does not reference it',
      new.chunk_id,
      new.document_version_source_object_id
      using errcode = '23514';
  end if;

  return new;
end;
$$;

drop trigger if exists trg_knowledge_document_version_processing_touch_updated_at on private.knowledge_document_version_processing;
create trigger trg_knowledge_document_version_processing_touch_updated_at
before update on private.knowledge_document_version_processing
for each row
execute function private.touch_updated_at();

drop trigger if exists trg_knowledge_chunk_set_sources_validate_source on private.knowledge_chunk_set_sources;
create trigger trg_knowledge_chunk_set_sources_validate_source
before insert or update of chunk_set_id, document_version_source_object_id, source_usage_role
on private.knowledge_chunk_set_sources
for each row
execute function private.validate_knowledge_chunk_set_source();

drop trigger if exists trg_knowledge_chunk_sources_validate_source on private.knowledge_chunk_sources;
create trigger trg_knowledge_chunk_sources_validate_source
before insert or update of chunk_id, document_version_source_object_id
on private.knowledge_chunk_sources
for each row
execute function private.validate_knowledge_chunk_source();

drop trigger if exists trg_knowledge_chunk_sets_require_sources on private.knowledge_chunk_sets;
create constraint trigger trg_knowledge_chunk_sets_require_sources
after insert or update of generation_status on private.knowledge_chunk_sets
deferrable initially immediate
for each row
execute function private.enforce_current_chunk_set_has_sources_from_chunk_set();

drop trigger if exists trg_knowledge_chunk_set_sources_require_current_sources on private.knowledge_chunk_set_sources;
create constraint trigger trg_knowledge_chunk_set_sources_require_current_sources
after update of chunk_set_id or delete on private.knowledge_chunk_set_sources
deferrable initially immediate
for each row
execute function private.enforce_current_chunk_set_has_sources_from_chunk_set_source();

alter table private.knowledge_document_version_processing enable row level security;
alter table private.knowledge_chunk_sets enable row level security;
alter table private.knowledge_chunk_set_sources enable row level security;
alter table private.knowledge_chunks enable row level security;
alter table private.knowledge_chunk_sources enable row level security;

revoke all on table private.knowledge_document_version_processing from public, anon, authenticated, service_role;
revoke all on table private.knowledge_chunk_sets from public, anon, authenticated, service_role;
revoke all on table private.knowledge_chunk_set_sources from public, anon, authenticated, service_role;
revoke all on table private.knowledge_chunks from public, anon, authenticated, service_role;
revoke all on table private.knowledge_chunk_sources from public, anon, authenticated, service_role;
