from __future__ import annotations

from .contracts import (
    APPROVAL_POSTURE_APPROVAL_REQUIRED,
    APPROVAL_POSTURE_HUMAN_ONLY,
    CHANGE_IMPACT_LOW,
    CHANGE_IMPACT_MATERIAL,
)
from .observation_contracts import (
    OBSERVATION_TARGET_KIND_CASE_DECISION,
    OBSERVATION_TARGET_KIND_CONFIRMATION_EVIDENCE,
    OBSERVATION_TARGET_KIND_RENTAL_CASE_FACT,
    OBSERVATION_TARGET_KIND_RENTAL_CASE_SCHEDULE,
    OBSERVATION_TARGET_KIND_REQUIREMENT_EVIDENCE,
    OBSERVATION_TYPE_CASE_DECISION_CANDIDATE,
    OBSERVATION_TYPE_CHANGE_CANDIDATE,
    OBSERVATION_TYPE_CONFIRMATION_CANDIDATE,
    OBSERVATION_TYPE_FACT_CANDIDATE,
    OBSERVATION_TYPE_REQUEST_CANDIDATE,
    OBSERVATION_TYPE_REQUIREMENT_EVIDENCE_CANDIDATE,
    OBSERVATION_VALUE_TYPE_BOOLEAN,
    OBSERVATION_VALUE_TYPE_ENUM,
    OBSERVATION_VALUE_TYPE_ENUM_ARRAY,
    OBSERVATION_VALUE_TYPE_INTEGER,
    OBSERVATION_VALUE_TYPE_JSON_OBJECT,
    OBSERVATION_VALUE_TYPE_TEXT,
    ObservationFieldDefinition,
)


CATERING_ARRANGEMENT_VALUES = frozenset(
    {
        "none",
        "client_external_caterer",
        "wnc_vendor",
        "wnc_coordinated",
        "drinks_refreshments_only",
        "under_consideration",
        "unknown",
    }
)

FACILITATOR_ARRANGEMENT_VALUES = frozenset(
    {
        "none",
        "client_provided",
        "wnc_provided",
        "recommendation_requested",
        "custom_experience_design",
        "under_consideration",
        "unknown",
    }
)

TECHNICAL_REQUIREMENT_VALUES = frozenset(
    {
        "none",
        "projection_display",
        "audio_playback",
        "microphones",
        "dj_sound_booth",
        "enhanced_sound_system",
        "lighting",
        "photo_video_production",
        "livestream_recording",
        "internet_connectivity",
        "power_requirements",
        "branding_signage",
        "set_build_installation",
        "special_furniture_layout",
        "acoustic_noise",
        "other_technical",
    }
)

REQUESTED_RENTAL_SCOPE_VALUES = frozenset(
    {
        "studio_space",
        "entire_venue",
        "custom_scope",
    }
)

OBSERVATION_FIELD_DEFINITIONS = (
    ObservationFieldDefinition(
        field_code="guest_count",
        domain_code="event_profile",
        display_label="Guest Count",
        value_type_code=OBSERVATION_VALUE_TYPE_INTEGER,
        allowed_observation_types=(
            OBSERVATION_TYPE_FACT_CANDIDATE,
            OBSERVATION_TYPE_CHANGE_CANDIDATE,
            OBSERVATION_TYPE_CONFIRMATION_CANDIDATE,
        ),
        materiality_default=CHANGE_IMPACT_MATERIAL,
        client_input_allowed=True,
        human_validation_required=True,
        canonical_target_kind=OBSERVATION_TARGET_KIND_RENTAL_CASE_FACT,
        canonical_target_reference="rental_case_facts.guest_count",
        related_open_question_types=("expected_guest_count",),
        default_review_posture=APPROVAL_POSTURE_HUMAN_ONLY,
        notes="Governed current factual field used in planning and readiness.",
    ),
    ObservationFieldDefinition(
        field_code="active_event_window",
        domain_code="timing",
        display_label="Active Event Window",
        value_type_code=OBSERVATION_VALUE_TYPE_JSON_OBJECT,
        allowed_observation_types=(
            OBSERVATION_TYPE_FACT_CANDIDATE,
            OBSERVATION_TYPE_CHANGE_CANDIDATE,
            OBSERVATION_TYPE_REQUEST_CANDIDATE,
            OBSERVATION_TYPE_CONFIRMATION_CANDIDATE,
        ),
        materiality_default=CHANGE_IMPACT_MATERIAL,
        client_input_allowed=True,
        human_validation_required=True,
        canonical_target_kind=OBSERVATION_TARGET_KIND_RENTAL_CASE_SCHEDULE,
        canonical_target_reference="rental_cases.active_event_start|active_event_end",
        related_open_question_types=("requested_event_timing", "event_timeline_confirmation"),
        default_review_posture=APPROVAL_POSTURE_HUMAN_ONLY,
        notes="Requested or confirmed timing changes must route through reschedule handling.",
    ),
    ObservationFieldDefinition(
        field_code="requested_rental_scope",
        domain_code="event_profile",
        display_label="Requested Rental Scope",
        value_type_code=OBSERVATION_VALUE_TYPE_ENUM,
        allowed_observation_types=(
            OBSERVATION_TYPE_FACT_CANDIDATE,
            OBSERVATION_TYPE_CHANGE_CANDIDATE,
            OBSERVATION_TYPE_REQUEST_CANDIDATE,
            OBSERVATION_TYPE_CONFIRMATION_CANDIDATE,
        ),
        materiality_default=CHANGE_IMPACT_MATERIAL,
        client_input_allowed=True,
        human_validation_required=True,
        canonical_target_kind=OBSERVATION_TARGET_KIND_RENTAL_CASE_FACT,
        canonical_target_reference="rental_cases.rental_type_code",
        allowed_enum_values=tuple(sorted(REQUESTED_RENTAL_SCOPE_VALUES)),
        related_open_question_types=("requested_rental_scope",),
        default_review_posture=APPROVAL_POSTURE_HUMAN_ONLY,
        notes="Specific requested scope may later become current rental scope through the inquiry-intake runtime.",
    ),
    ObservationFieldDefinition(
        field_code="event_type",
        domain_code="event_profile",
        display_label="Event Type",
        value_type_code=OBSERVATION_VALUE_TYPE_TEXT,
        allowed_observation_types=(
            OBSERVATION_TYPE_FACT_CANDIDATE,
            OBSERVATION_TYPE_CHANGE_CANDIDATE,
            OBSERVATION_TYPE_REQUEST_CANDIDATE,
            OBSERVATION_TYPE_CONFIRMATION_CANDIDATE,
        ),
        materiality_default=CHANGE_IMPACT_MATERIAL,
        client_input_allowed=True,
        human_validation_required=True,
        canonical_target_kind=OBSERVATION_TARGET_KIND_RENTAL_CASE_FACT,
        canonical_target_reference="rental_case_facts.event_type",
        related_open_question_types=("requested_event_type",),
        default_review_posture=APPROVAL_POSTURE_HUMAN_ONLY,
        notes="The current repository does not expose a stricter event-type catalogue, so the normalized code is stored as text.",
    ),
    ObservationFieldDefinition(
        field_code="catering_arrangement",
        domain_code="catering",
        display_label="Catering Arrangement",
        value_type_code=OBSERVATION_VALUE_TYPE_ENUM,
        allowed_observation_types=(
            OBSERVATION_TYPE_FACT_CANDIDATE,
            OBSERVATION_TYPE_CHANGE_CANDIDATE,
            OBSERVATION_TYPE_REQUEST_CANDIDATE,
        ),
        materiality_default=CHANGE_IMPACT_MATERIAL,
        client_input_allowed=True,
        human_validation_required=True,
        canonical_target_kind=OBSERVATION_TARGET_KIND_RENTAL_CASE_FACT,
        canonical_target_reference="rental_case_facts.catering_arrangement",
        allowed_enum_values=tuple(sorted(CATERING_ARRANGEMENT_VALUES)),
        default_review_posture=APPROVAL_POSTURE_HUMAN_ONLY,
    ),
    ObservationFieldDefinition(
        field_code="facilitator_arrangement",
        domain_code="facilitator",
        display_label="Facilitator Arrangement",
        value_type_code=OBSERVATION_VALUE_TYPE_ENUM,
        allowed_observation_types=(
            OBSERVATION_TYPE_FACT_CANDIDATE,
            OBSERVATION_TYPE_CHANGE_CANDIDATE,
            OBSERVATION_TYPE_REQUEST_CANDIDATE,
        ),
        materiality_default=CHANGE_IMPACT_MATERIAL,
        client_input_allowed=True,
        human_validation_required=True,
        canonical_target_kind=OBSERVATION_TARGET_KIND_RENTAL_CASE_FACT,
        canonical_target_reference="rental_case_facts.facilitator_arrangement",
        allowed_enum_values=tuple(sorted(FACILITATOR_ARRANGEMENT_VALUES)),
        default_review_posture=APPROVAL_POSTURE_HUMAN_ONLY,
    ),
    ObservationFieldDefinition(
        field_code="technical_requirements",
        domain_code="technical",
        display_label="Technical Requirements",
        value_type_code=OBSERVATION_VALUE_TYPE_ENUM_ARRAY,
        allowed_observation_types=(
            OBSERVATION_TYPE_FACT_CANDIDATE,
            OBSERVATION_TYPE_CHANGE_CANDIDATE,
            OBSERVATION_TYPE_REQUEST_CANDIDATE,
        ),
        materiality_default=CHANGE_IMPACT_MATERIAL,
        client_input_allowed=True,
        human_validation_required=True,
        canonical_target_kind=OBSERVATION_TARGET_KIND_RENTAL_CASE_FACT,
        canonical_target_reference="rental_case_facts.technical_requirements",
        allowed_enum_values=tuple(sorted(TECHNICAL_REQUIREMENT_VALUES)),
        related_open_question_types=("technical_requirements_confirmation",),
        default_review_posture=APPROVAL_POSTURE_HUMAN_ONLY,
    ),
    ObservationFieldDefinition(
        field_code="supplier_details",
        domain_code="supplier",
        display_label="Supplier Details",
        value_type_code=OBSERVATION_VALUE_TYPE_JSON_OBJECT,
        allowed_observation_types=(
            OBSERVATION_TYPE_FACT_CANDIDATE,
            OBSERVATION_TYPE_CHANGE_CANDIDATE,
            OBSERVATION_TYPE_REQUIREMENT_EVIDENCE_CANDIDATE,
        ),
        materiality_default=CHANGE_IMPACT_MATERIAL,
        client_input_allowed=True,
        human_validation_required=True,
        canonical_target_kind=OBSERVATION_TARGET_KIND_REQUIREMENT_EVIDENCE,
        canonical_target_reference="rental_case_requirements.supplier_details_required",
        related_requirement_types=("supplier_details_required",),
        default_review_posture=APPROVAL_POSTURE_HUMAN_ONLY,
    ),
    ObservationFieldDefinition(
        field_code="event_day_contact",
        domain_code="contacts",
        display_label="Event-Day Contact",
        value_type_code=OBSERVATION_VALUE_TYPE_JSON_OBJECT,
        allowed_observation_types=(
            OBSERVATION_TYPE_FACT_CANDIDATE,
            OBSERVATION_TYPE_CHANGE_CANDIDATE,
        ),
        materiality_default=CHANGE_IMPACT_LOW,
        client_input_allowed=True,
        human_validation_required=True,
        canonical_target_kind=OBSERVATION_TARGET_KIND_RENTAL_CASE_FACT,
        canonical_target_reference="rental_case_facts.event_day_contact",
        related_open_question_types=("final_event_day_contact",),
        default_review_posture=APPROVAL_POSTURE_HUMAN_ONLY,
    ),
    ObservationFieldDefinition(
        field_code="layout_requirements",
        domain_code="layout",
        display_label="Layout Requirements",
        value_type_code=OBSERVATION_VALUE_TYPE_JSON_OBJECT,
        allowed_observation_types=(
            OBSERVATION_TYPE_FACT_CANDIDATE,
            OBSERVATION_TYPE_CHANGE_CANDIDATE,
            OBSERVATION_TYPE_REQUEST_CANDIDATE,
        ),
        materiality_default=CHANGE_IMPACT_MATERIAL,
        client_input_allowed=True,
        human_validation_required=True,
        canonical_target_kind=OBSERVATION_TARGET_KIND_RENTAL_CASE_FACT,
        canonical_target_reference="rental_case_facts.layout_requirements",
        related_open_question_types=("layout_requirements_confirmation",),
        default_review_posture=APPROVAL_POSTURE_HUMAN_ONLY,
    ),
    ObservationFieldDefinition(
        field_code="booking_fee_override",
        domain_code="commercial",
        display_label="Booking Fee Override",
        value_type_code=OBSERVATION_VALUE_TYPE_JSON_OBJECT,
        allowed_observation_types=(OBSERVATION_TYPE_CASE_DECISION_CANDIDATE,),
        materiality_default=CHANGE_IMPACT_MATERIAL,
        client_input_allowed=False,
        human_validation_required=True,
        canonical_target_kind=OBSERVATION_TARGET_KIND_CASE_DECISION,
        canonical_target_reference="phase4:booking_fee",
        default_review_posture=APPROVAL_POSTURE_APPROVAL_REQUIRED,
        notes="Commercial exception candidate only; never activates directly from observation intake.",
    ),
    ObservationFieldDefinition(
        field_code="proposal_acceptance",
        domain_code="commercial",
        display_label="Proposal Acceptance",
        value_type_code=OBSERVATION_VALUE_TYPE_BOOLEAN,
        allowed_observation_types=(OBSERVATION_TYPE_CONFIRMATION_CANDIDATE,),
        materiality_default=CHANGE_IMPACT_MATERIAL,
        client_input_allowed=True,
        human_validation_required=True,
        canonical_target_kind=OBSERVATION_TARGET_KIND_CONFIRMATION_EVIDENCE,
        canonical_target_reference="workflow_event.confirmation_evidence",
        default_review_posture=APPROVAL_POSTURE_HUMAN_ONLY,
    ),
)

OBSERVATION_FIELD_DEFINITIONS_BY_CODE = {definition.field_code: definition for definition in OBSERVATION_FIELD_DEFINITIONS}


def get_field_definition(field_code: str) -> ObservationFieldDefinition | None:
    return OBSERVATION_FIELD_DEFINITIONS_BY_CODE.get(field_code)
